### ISSUE TITLE
Writing Delete flag fails

### ISSUE THREAD

**Issue by zk101** [emersion/go-imap#101]
I'm using the example of deleting a message, and it fails with the message "imap: cannot format field: [\Deleted]".  Seems its falling through the switch statement in the writeField func in write.go.  

```
package main

import (
  "github.com/emersion/go-imap/client"
  "github.com/emersion/go-imap"
  "fmt"
  "os"
)

func main() {
  imap_conn, err := client.DialTLS("server:993", nil)
  if err != nil {
    fmt.Println("IMAP Server Connect Failed")
    os.Exit(1)
  }

  defer imap_conn.Logout()

  if err := imap_conn.Login("user", "pass"); err != nil {
    fmt.Println("IMAP Server Login Failed")
    os.Exit(1)
  }

  mbox, err := imap_conn.Select("INBOX", false)
  if err != nil {
    fmt.Println("IMAP Select Mailbox Failed")
    os.Exit(1)
  }

  fmt.Println("Flags for INBOX:", mbox.Flags)
  fmt.Printf("%d\n", mbox.Messages)

  del_seqset := new(imap.SeqSet)
  del_seqset.AddRange(mbox.Messages, mbox.Messages)

  operation := "+FLAGS.SILENT"
  flags := []string{imap.DeletedFlag}
  if err := imap_conn.Store(del_seqset, operation, flags, nil); err != nil {
    fmt.Println("IMAP Message Flag Update Failed")
    fmt.Println(err)
    os.Exit(1)
  }

  if err := imap_conn.Expunge(nil); err != nil {
    fmt.Println("IMAP Message Delete Failed")
    os.Exit(1)
  }

  fmt.Println("IMAP Success")
}
```

Output:
$ ./imap
Flags for INBOX: [\Answered \Flagged \Deleted \Seen \Draft]
10
IMAP Message Flag Update Failed
imap: cannot format field: [\Deleted]

**Comment by emersion** [comment]
Ow, sorry about that, I made a typo! Please replace `flags := []string{imap.DeletedFlag}` with `flags := []interface{}{imap.DeletedFlag}`.

Let me know if you have other issues or if you need other examples!

**Comment by zk101** [comment]
Perfect, all working now.,  Thank you.

**Comment by jnabasny** [comment]
I'm trying to run this code (with the corrected line) and I keep getting this error:

`# command-line-arguments
./imap_delete.go:38:28: cannot use operation (type string) as type imap.StoreItem in argument to imap_conn.Store`

Has the syntax changed since it was written?

**Comment by emersion** [comment]
Yes, you now need to use `imap.FormatFlagsOp`.

**Comment by bsandy999** [comment]
I'm trying to run this code (with the corrected line) and I keep getting this error:


[root@stage1 emailreader]# go run imap.go stage
`./imap.go:106:22: cannot use operation (type string) as type imap.StoreItem in argument to c.Store`

**Here is my code:**


            operation := "+FLAGS.SILENT"
		  flags := []interface{}{imap.DeletedFlag}
		  if err := c.Store(del_seqset, operation, flags, nil); err != nil {
		        fmt.Println("IMAP Message Flag Update Failed")
		        fmt.Println(err)
		       os.Exit(1)
		  }

		  if err := c.Expunge(nil); err != nil {
		        fmt.Println("IMAP Message Delete Failed")
		       os.Exit(1)
              }

**Comment by alexjoedt** [comment]
@bsandy999 You have to use the correct type, like emersion and the error message said:

```go

        operation := imap.FormatFlagsOp(imap.AddFlags, true) // Notice this line

	flags := []interface{}{imap.DeletedFlag}
	err = c.Store(seqSet, operation, flags, nil)
	if err != nil {
		return nil, err
	}
	err = c.Expunge(nil)
	if err != nil {
		return nil, err
	}
```
