### ISSUE TITLE
Undefined Encoder/Decoder

### ISSUE THREAD

**Issue by ggitau** [emersion/go-imap#108]
Getting the error below. Not sure if I did something wrong or if there was an update to golang.org/x/text . 

**vendor/github.com/emersion/go-imap/utf7/decoder.go:14: undefined: encoding.Decoder
vendor/github.com/emersion/go-imap/utf7/encoder.go:11: undefined: encoding.Encoder**

**Comment by emersion** [comment]
That's pretty strange, `Encoder` and `Decoder` are still here: https://godoc.org/golang.org/x/text/encoding

What Go version are you using? Can you `go get -u golang.org/x/text/encoding`?

**Comment by emersion** [comment]
Actually, you're using vendoring. What tool are you using? Can you check the contents of `vendor/golang.org/x/text/encoding`?

**Comment by ggitau** [comment]
@emersion am using govendor. Tried it on a fresh project and it works..Must have messed something up somewhere
