### ISSUE TITLE
How to use StartTLS?

### ISSUE THREAD

**Issue by baskara8** [emersion/go-imap#109]
Hi, Your library is amazing, i can use for my gmail, but i want to testing for my office email, but my office's email using starttls, would you please to provide example code?

**Comment by emersion** [comment]
Hey! I added an example for `Client.StartTLS`: https://godoc.org/github.com/emersion/go-imap/client#example-Client-StartTLS

Hope this helps!

**Comment by baskara8** [comment]
Thanks for your quick response , but I got this : tls : either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by emersion** [comment]
Ahh, I forgot about that! Updated the example. ;-)

**Comment by baskara8** [comment]
x509 : certificate signed by unknown authority

**Comment by emersion** [comment]
That means your company's certificate is not signed by a trusted authority.

* For testing, you can set `InsecureSkipVerify` to `true` (**but this is insecure**)
* You should get your company's CA certificate and add it to [`tls/Config.RootCAs`](https://golang.org/pkg/crypto/tls/#Config.RootCAs)

**Comment by baskara8** [comment]
Thanks for your explanation, and How to set InsecureSkipVerify to true?

**Comment by emersion** [comment]
You can just replace

```go
tlsConfig := &tls.Config{ServerName: "mail.example.org"}
```

with

```go
tlsConfig := &tls.Config{InsecureSkipVerify: true}
```

Even if I repeat myself: I don't recommend using that with real credentials, as someone could MITM you connection and get your password.

**Comment by baskara8** [comment]
Amazinggggg :) thank you so much...
