### ISSUE TITLE
How to send email using imap?

### ISSUE THREAD

**Issue by baskara8** [emersion/go-imap#110]
Hi Emersion, would you please to share example code to send email using this plugin? :)

**Comment by emersion** [comment]
Sending emails is not possible with IMAP. You'll have to use SMTP for that. The standard library has a SMTP package: `net/smtp`. Though, it's in a frozen state (it won't receive any new feature, so I forked it here: https://github.com/emersion/go-smtp).

**Comment by baskara8** [comment]
If i send using go-smtp is it automatically send to my INBOX.sent-mail?

**Comment by emersion** [comment]
No, you'll have to append it to your Sent folder via IMAP, too.

**Comment by baskara8** [comment]
Ok i got it, thanks :)
