### ISSUE TITLE
multiple-value header.Date() in single-value context

### ISSUE THREAD

**Issue by baskara8** [emersion/go-imap#111]
Hi, Im Using this link https://github.com/emersion/go-imap/wiki/Fetching-messages#fetching-the-whole-message-body but return error like a subject and io in io.EOF

```go
package main

import (
	"io/ioutil"
	"log"
	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
	"github.com/emersion/go-message/mail"
)

func main() {
	log.Println("Connecting to server...")

	// Connect to server
	c, err := client.DialTLS("imap.gmail.com:993", nil)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")

	// Don't forget to logout
	defer c.Logout()

	// Login
	if err := c.Login(myemailuser, myemailpassword); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")

	// Select INBOX
	mbox, err := c.Select("INBOX", false)
	if err != nil {
		log.Fatal(err)
	}

	// Get the last message
	if mbox.Messages == 0 {
		log.Fatal("No message in mailbox")
	}
	seqset := new(imap.SeqSet)
	seqset.AddRange(mbox.Messages, mbox.Messages)

	// Get the whole message body
	attrs := []string{"BODY[]"}

	messages := make(chan *imap.Message, 1)
	go func() {
		if err := c.Fetch(seqset, attrs, messages); err != nil {
			log.Fatal(err)
		}
	}()

	msg := <-messages
	r := msg.GetBody("BODY[]")
	if r == nil {
		log.Fatal("Server didn't returned message body")
	}

	// Create a new mail reader
	mr, err := mail.CreateReader(r)
	if err != nil {
		log.Fatal(err)
	}

	// Print some info about the message
	header := mr.Header
	log.Println("Date:", header.Date())
	log.Println("From:", header.AddressList("From"))
	log.Println("To:", header.AddressList("To"))
	log.Println("Subject:", header.Subject())

	// Process each message's part
	for {
		p, err := mr.NextPart()
		if err == io.EOF {
			break
		} else if err != nil {
			log.Fatal(err)
		}

		switch h := p.Header.(type) {
		case mail.TextHeader:
			// This is the message's text (can be plain-text or HTML)
			b, _ := ioutil.ReadAll(p.Body)
			log.Println("Got text: %v", string(b))
		case mail.AttachmentHeader:
			// This is an attachment
			filename, _ := h.Filename()
			log.Println("Got attachment: %v", filename)
		}
	}
}
```

**Comment by emersion** [comment]
Yeah, I didn't tested this example, so it has a few mistakes.

Can you try to solve them yourself? You'll learn more by trying to fix them than by reading a fixed version. You can [read the docs](https://godoc.org/github.com/emersion/go-message/mail). I'm sure you can do it! ;-)

**Comment by baskara8** [comment]
I have try my best, but still error "multiple-value header.Date() in single-value context" :(

**Comment by emersion** [comment]
Let me give you more context.

The [`Header.Date`](https://godoc.org/github.com/emersion/go-message/mail#Header.Date) function signature is:

```go
func (h Header) Date() (time.Time, error)
```

You can see that it returns two values: the parsed time, and an error (if the date specified in the header is invalid and cannot be parsed).

But you can't pass two values directly to `log.Println`. You have to store the result of `Header.Date` in two variables, check if there is an error, and then you can print the returned date.

**Comment by baskara8** [comment]
ahhh i have found for solve it for different approach :) thanks emersion for give me inspiration

**Comment by emersion** [comment]
Well done! I updated the wiki so you can compare your solution and mine if you want.

**Comment by baskara8** [comment]
Yeah, i see your update code, but from your reference I try to update seqset.AddRange(1, 10) but return only 1 email

**Comment by emersion** [comment]
Yeah, that's because the `messages` channel is only read once. You'll have to put that in a loop to retrieve multiple messages.

**Comment by baskara8** [comment]
Put Loop code after header := mr.Header or before? Im try 
for msg := range messages {
  header := msg.mr.Header
}
but error
