### ISSUE TITLE
fetch specific UID email not working

### ISSUE THREAD

**Issue by rmrf** [emersion/go-imap#112]
Maybe I'm not using it correctly: 

I want to get UID==422 email (currently INBOX latest email UID==1000). 
but bellow code I will got  "the mail is: 1000"

```
	seqset := new(imap.SeqSet)
	seqset.AddNum(422)

	messages := make(chan *imap.Message, 10)
	done := make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []string{imap.EnvelopeMsgAttr, imap.UidMsgAttr}, messages)
	}()

	for msg := range messages {
		log.Printf("the mail is: %v", msg.Uid)
	}
```

seems the number inside seqset is email number (not UID which uniq inside IMAP server)

how to fetch specific UID email ?

**Comment by rmrf** [comment]
@emersion

**Comment by rmrf** [comment]
seems the number inside seqset is email number (not UID which uniq inside IMAP server)

**Comment by emersion** [comment]
Use Fetch to get by sequence number, and FetchUid to get by UID. ;)

(See the docs: https://godoc.org/github.com/emersion/go-imap/client)
