### ISSUE TITLE
login hanging for gmail

### ISSUE THREAD

**Issue by amalfra** [emersion/go-imap#116]
I was trying to login to gmail using the example code. But it seems that the login is hanging indefinitely
```
	if err := client.Login(imapUser, imapPassword); err != nil {
```
I read in another issue that gmail does not support login using user and password in their imap but can't get why the Login call is going on indefinitely

**Comment by amalfra** [comment]
never mind, this is working now. Was actually issue with how I was using goroutines. sorry for false alarm

**Comment by amalfra** [comment]
Actually it seems like an issue with library. If I do some random port like 
```
c, err := client.DialTLS("imap.gmail.com:34543", nil)
```
it hangs indefinitely. I tried with the example code given in docs and confirmed that its happening

**Comment by emersion** [comment]
Glad you found out what was wrong with your code. :)

If you want to login to Gmail, it's recommended to use OAuth: https://github.com/emersion/go-imap/wiki/Using-authentication-mechanisms#client
