### ISSUE TITLE
Delete flag

### ISSUE THREAD

**Issue by matiux** [emersion/go-imap#122]
Hi,
I have tried to mark a message deleted without expunge:

```
	_, err := imap.Client.Select(from, false)

	if err != nil {
		log.Fatal(err)
	}

	seqset := new(goimap.SeqSet)
	seqset.Add(toDelete)

	operation := "+FLAGS.SILENT"
	flags := []interface{}{goimap.DeletedFlag}
	if err := imap.Client.Store(seqset, operation, flags, nil); err != nil {
		log.Fatal(err)
	}
```

So in my webmail I see the message in the same folder but strikethrough. And this is ok...

Then, when I fetching the list (by go-imap) the message is in the list and I thought that `message.Flags` would show the `Deleted` flag on message that I was previously mark but `message.Flags` is empty.

It's a normal behavior?

**Comment by emersion** [comment]
How do you fetch messages? You have to add `FLAGS` to the list of attributes to fetch:

```go
attrs := []string{imap.FlagsMsgAttr}
c.Fetch(seqset, attrs, messages)
```

**Comment by matiux** [comment]
OK thanks, I was fetching only the Envelope
```
	attrs := []string{
		goimap.EnvelopeMsgAttr,
	}
	go func() {
		done <- listEmailService.imapClient.Fetch(seqset, attrs, imapMessages)
	}()
```

Now I have added this:

```
	attrs := []string{
		goimap.FlagsMsgAttr,
		goimap.EnvelopeMsgAttr,
		goimap.UidMsgAttr,
	}
	go func() {
		done <- listEmailService.imapClient.Fetch(seqset, attrs, imapMessages)
	}()
```

**Comment by emersion** [comment]
Glad it fixed your issue!
