### ISSUE TITLE
Missing subject

### ISSUE THREAD

**Issue by matiux** [emersion/go-imap#127]
Hi, I have noticed that in some messages the subject is missing. From a client like thunderbird, or from the webmail, the subject is there.

I don't understand what I can check to figure out the problem

**Comment by emersion** [comment]
Please paste your code here.

**Comment by matiux** [comment]
```
package main

import (
	"fmt"
	"log"

	imap "github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
)

func main() {

	c, err := client.DialTLS("in.postassl.it:993", nil)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout()

	if err := c.Login("matteo@adriasonline.it", "ZZzL23$-#2"); err != nil {
		log.Fatal(err)
	}

	mbox, err := c.Select("INBOX.Adrias.Colleghi.Francesco", false)
	if err != nil {
		log.Fatal(err)
	}

	done := make(chan error, 1)

	seqset := new(imap.SeqSet)
	seqset.AddRange(uint32(1), mbox.Messages)

	messages := make(chan *imap.Message, 10)
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []string{imap.EnvelopeMsgAttr}, messages)
	}()

	for msg := range messages {
		fmt.Printf("* %s - %v\n", msg.Envelope.Subject, msg.Envelope.Date.Format("02-01-2006 15:04:05"))
	}

	if err := <-done; err != nil {
		log.Fatal(err)
	}

}
```

**Comment by matiux** [comment]
package main

import (
	"fmt"
	"log"

	imap "github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
)

func main() {

	c, err := client.DialTLS("xyz:993", nil)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout()

	if err := c.Login("xyz", "xyz"); err != nil {
		log.Fatal(err)
	}

	mbox, err := c.Select("INBOX.Subfolder.Tom", false)
	if err != nil {
		log.Fatal(err)
	}

	done := make(chan error, 1)

	seqset := new(imap.SeqSet)
	seqset.AddRange(uint32(1), mbox.Messages)

	messages := make(chan *imap.Message, 10)
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []string{imap.EnvelopeMsgAttr}, messages)
	}()

	for msg := range messages {
		fmt.Printf("* %s - %v\n", msg.Envelope.Subject, msg.Envelope.Date.Format("02-01-2006 15:04:05"))
	}

	if err := <-done; err != nil {
		log.Fatal(err)
	}

}

**Comment by emersion** [comment]
Hum, that's strange, it doesn't seem to be a charset issue. Can you add `c.SetDebug(os.Stdout)`?

**Comment by matiux** [comment]
Sure. This is the output, limiting the range to a single message that not return the subject

```
zlaCDQ LOGIN matteo@domain.com ZZzL23$-#2
16SC6g SELECT INBOX.Subfolder.Tom
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk)
* OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk \*)] Flags permitted.
* 95 EXISTS
* 0 RECENT
* OK [UNSEEN 74] First unseen.
* OK [UIDVALIDITY 1414137590] UIDs valid
* OK [UIDNEXT 96] Predicted next UID
* OK [HIGHESTMODSEQ 200] Highest
16SC6g OK [READ-WRITE] Select completed (0.011 secs).
imap/client: 2017/07/10 12:55:59 response has not been handled: &{* OK HIGHESTMODSEQ [200] Highest}
5cEu7A FETCH 86 (ENVELOPE)
* 86 FETCH (ENVELOPE ("Thu, 8 Jun 2017 15:09:41 +0200" {33}
area riservata "nascondi grafico" (("Francesco" NIL "francesco" "domain.com")) (("Francesco" NIL "francesco" "domain.com")) (("Francesco" NIL "francesco" "domain.com")) (("Carlo" NIL "carlo" "domain.com")("Emanuele" NIL "emanuele" "domain.com")("Matteo" NIL "matteo" "domain.com")) NIL NIL NIL "<CAJ+68C3aY-BwLeY37sksSFwLKmAQASYoZrpzrBk3cFVnXisRjg@mail.gmail.com>"))
5cEu7A OK Fetch completed (0.007 secs).
Subject:  - Date: 08-06-2017 15:09:41
5xxiTQ LOGOUT
* BYE Logging out
5xxiTQ OK Logout completed.
```

**Comment by emersion** [comment]
Thanks! This bug should be fixed now.
