### ISSUE TITLE
Dialer's timeout reset

### ISSUE THREAD

**Issue by jakubdal** [emersion/go-imap#128]
Hello,

I've encountered a following (i think) bug:
I'm creating a client using `DialWithDialerTLS`. Dialer has a set timeout. The timeout is set on connection.
After that, I'm executing a `Login` command.
In `Login`, because my client doesn't have timeout set on itself, the connection's `Deadline` is reset, and so the command blocks, even if `Dialer`'s timeout is exceeded.

I do believe if it's not a bug, it's at least confusing, because of a comment saying `// Among other uses, this allows us to apply a connection timeout.` on `DialWithDialerTLS`.

I think about two solutions:
* Set `Dialer`'s timeout to `Client`
* Remove the comment, and possibly add an information to documentation about this case

Looking forward to your reply :)

**Comment by emersion** [comment]
`Dialer` timeouts only applies when the connection is being established: https://golang.org/pkg/net/#Dialer.Timeout

After that, the `Dialer` timeout has no effect anymore. You can set a connection timeout with `Client.Timeout`: https://godoc.org/github.com/emersion/go-imap/client#Client.Timeout

**Comment by jakubdal** [comment]
Yes, I am aware of that.

However that comment on `DialWithDialerTLS` got me misguided, and so I've assumed that the timeout propagates to the entire connection. I think that at least changing the comment should be enough. The bug itself was not obvious for me (maybe it should?), and so it took me a while to debug.

**Comment by emersion** [comment]
You're right, the wording is incorrect. I changed that in https://github.com/emersion/go-imap/commit/a81f6b0c00512da092560a1446be3131ba75c9ed
