### ISSUE TITLE
Fetch on timeout blocks reading messages - suggested documentation change

### ISSUE THREAD

**Issue by jakubdal** [emersion/go-imap#131]
Part of example I'm talking about:

```go
messages := make(chan *imap.Message, 10)
done = make(chan error, 1)
go func() {
  done <- c.Fetch(seqset, []string{imap.EnvelopeMsgAttr}, messages)
}()

log.Println("Last 4 messages:")
for msg := range messages {
  log.Println("* " + msg.Envelope.Subject)
}

if err := <-done; err != nil {
  log.Fatal(err)
}
```

If `Client.Timeout` is set and we're pulling a lot of emails, or doing a lot of processing on them, `c.Fetch(...)` can reach the `Timeout`. If so, it sends on `done`, and the loop is stuck waiting for a new message for infinity. My suggestion is closing the channel `msg` on timeout, because to my knowledge the only way around this issue for now is changing the loop to:

```go
loop:
for {
  select {
  case err := <-done:
    // probably get `err` out of scope of function and check if outside
    break loop
  case msg := <-messages:
    select {
      case err := <-done:
        // probably get `err` out of scope of function and check if outside
        break loop
      default:
    }
    log.Println("* " + msg.Envelope.Subject)
  }
}
```

However because the `messages` channel is buffered in the example, we can skip some messages (I think?).

Looking forward for your reply :)

**Comment by emersion** [comment]
Hum, that looks like a bug. The `messages` channel should be closed when `c.Fetch` returns an error.

**Comment by jakubdal** [comment]
Hey @emersion, until you find time to fix this issue (because I have troubles with working on the package, as my knowledge about IMAP itself is pretty poor), I have a quickfix for anyone else struggling with it:

```
		done <- c.Fetch(seqset, attrs, messages)
		select {
		case <-messages:
		case <-time.After(time.Second):
			close(messages)
		}
```

AFAIK you can skip the timeout on the second `case` (use `default` or set smaller timeout), however I'm not sure if that's the case, so I'd like a feedback on this workaround.

**Comment by emersion** [comment]
>If so, it sends on done, and the loop is stuck waiting for a new message for infinity.

That isn't possible. The `Fetch` code has a `defer close(messages)`. Thus, if the function returns, the `messages` channel has been closed, and `done` is closed afterwards.

>so I'd like a feedback on this workaround.

The workaround is not correct: `Fetch` is responsible for closing the channel. This can result in the channel being closed two times and a panic.

If you want to do a lot of work with messages you should use a large enough buffered channel or spawn goroutines:

```go
for msg := range messages {
  go doALotOfWork(msg)
}
```

**Comment by jakubdal** [comment]
Hey @emersion, sorry for my delayed response. I agree with your statements, that:

> Fetch is responsible for closing the channel

and 

> Thus, if the function returns, the messages channel has been closed

Those are both correct, however I've found out that the key to finding the solution for my problem is:

> if the function returns

I've noticed, that in file `responses/fetch.go` function `HandleFrom` returns only if `hdlr` is closed (because of range over channel in `responses/fetch.go#L16`). However if timeout occurs, it happens in  `client/client.go#L168`, the message is pushed to `c.loggedOut` and so the channel `hdlr` is never closed.

This prevents messages channel to close and as a result blocks my program. My suggestion is to add `close(hdlr)` in that `case` (like in `client/client.go#L197`).

If my explanations are unclear, I can try to provide a real-life example of this problem. I've tried writing tests for this, but my understanding of the protocol is not enough to write tests for your package, sorry.

I'm hope my feedback will prove itself useful, if not please message me (here or in private) for more clarifications.

**Comment by emersion** [comment]
Oh, I see, you're right. Thanks for your explanation!

However, this part has been re-written for v1, and I believe doesn't have this issue anymore because the channel is now closed in `client/client_selected.go` instead of `responses/fetch.go`. Can you give the v1 branch a try? (If you need to upgrade, there's a list of what changed in #123)

**Comment by jakubdal** [comment]
I've got a problem with the following error:

```
vendor/github.com/emersion/go-imap/mailbox.go:69: undefined: utf7.Encoding in utf7.Encoding.NewDecoder
vendor/github.com/emersion/go-imap/mailbox.go:80: undefined: utf7.Encoding in utf7.Encoding.NewEncoder
```

Could you tell me what is the reason and how to fix it?

**Comment by emersion** [comment]
It seems that you have a newer `go-imap` and an outdated subpackage `go-imap/utf7`. Try running `go get -u github.com/emersion/go-imap/...`. Or maybe you're using vendoring?

**Comment by jakubdal** [comment]
I have reinitialized my `vendor/`. No clue why, but I went into `vendor/github.com/emersion/go-imap/utf7/utf7.go`, pressed `Ctrl+S` (save), and it started working. Probably `install` ws needed to be done and is made by `Atom` with `goplus` on save? I don't know. Pushing this to production, will see if blocking will reoccur.

**Comment by jakubdal** [comment]
Hey @emersion, coming back with feedback :) `v1` seems to work so far, didn't block once, everything is just fine. Merge it ASAP and this problem should be fixed :)

Thanks for your help!

**Comment by emersion** [comment]
Thanks for the feedback!
