### ISSUE TITLE
More examples: how to handle attachments?

### ISSUE THREAD

**Issue by advancedlogic** [emersion/go-imap#133]
Hi,
thanks for the library but it would be great if you could create some simple wrapper over the complex protocol, in order to manage standard messages and standard attachments (txt, doc, pdf ... ). 
Thanks

**Comment by emersion** [comment]
You have an example for that in the wiki: https://github.com/emersion/go-imap/wiki/Fetching-messages

If you need more examples, I can write some.

**Comment by advancedlogic** [comment]
oh ... sorry for some reason the wiki was empty ... I really apologize ... thanks for your quick reply.

**Comment by emersion** [comment]
I just replaced the blank main wiki page with links to articles, that might help others. ;)

**Comment by tientp-floware** [comment]
Hi I give you example about download attachment inline and non inline.

[gist](https://gist.github.com/tientp-floware/8bff9aa7aca47fa1cb342bdb28f12136)
