### ISSUE TITLE
Support for GBK？

### ISSUE THREAD

**Issue by yqylovy** [emersion/go-imap#134]
when the mail got GBK message，it don't parse it to the right msg. 
example: If msg.Envelope.Subject were `=?GBK?B?d3d3?=`, it means `www`.

**Comment by emersion** [comment]
You can set `imap.CharsetReader`: https://godoc.org/github.com/emersion/go-imap#CharsetReader

Just created a wiki page to explain this: https://github.com/emersion/go-imap/wiki/Charset-handling

Feel free to ask more details! :)

**Comment by yqylovy** [comment]
Great! The   `github.com/emersion/go-message/charset` don't have a `GBK` decoder yet, but with the public `CharsetReader` ,I can handle it myself.

**Comment by emersion** [comment]
Ahah, sorry, I didn't check that!

**Comment by yqylovy** [comment]
It's fine,I added and make a pr.
