### ISSUE TITLE
Interaction between EXPUNGE and other responses

### ISSUE THREAD

**Issue by jim-minter** [emersion/go-imap#136]
Hi, first, many thanks indeed for a terrific library! :smile:

I've got a question about how to handle server responses in correct order using the go-imap client.  I'm concerned because EXPUNGE responses are sent to a different golang channel than, for example, FETCH responses.  I've seen an example with gmail where after sending a MOVE command to the server, both an EXPUNGE and a FETCH response (flags updated on some other message by another client) happen to be returned.  Clearly, the responses arrive in a defined order, and local state must be updated in that order otherwise corruption/de-synchronisation may occur.  But, by sending these responses to c.Expunges and c.MessageUpdates, I don't then know how to interpret them in the order that arrived, unless I make all these channels non-buffered, and have a channel reader selecting across these and the other relevant channels to reconstruct the ordering.  Is that the intended implementation pattern?  If so, it's moderately painful and non-obvious.  Would it make more sense to have a single channel to handle all server responses in order?

**Comment by emersion** [comment]
Hi!

Yeah, the intended usage is:

```go
for {
  select {
  case update := <-c.MessageUpdates:
    // Handle message update
  case expunge := <-c.Expunges:
    // Handle expunge
  }
}
```

That's because usually you won't handle these two notifications the same way. I chose that design because I didn't want to use a `chan interface{}` and users don't always want to receive all notifications, or want to receive different types of notifications in difference goroutines.

That said, I didn't think about your use case. Maybe keeping the existing channels and adding a new one for all notifications would be okay? I'm a little puzzled about having redundant channels. I'll think about it. If you have a better idea, I'm interested! :)

**Comment by jim-minter** [comment]
The trick with the intended usage you give is that both channels must be unbuffered, otherwise it's not guaranteed that the events are handled in the right order (see the Go spec: "If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection").  If not, it could lead to quite a tricky to find corruption.

If both channels are unbuffered, the user's handling code is then effectively synchronous with the library protocol handling code, so there's not much point in a channel at all.

Given the above, although the design looks great, I think it's actually a design flaw to have separate channels here - having the user read from a single channel (or slice) and switch either on the item type or on a struct field is really the implementation that is needed.

**Comment by emersion** [comment]
Merged in `v1`!
