### ISSUE TITLE
Error reading response: unexpected EOF

### ISSUE THREAD

**Issue by advancedlogic** [emersion/go-imap#140]
Hi,
this apparently happens on the client.go and the application gets stuck and must be restarted.
Sounds like there is a never ending for { } loop in some specific case.
```go
		res, err := imap.ReadResp(c.conn.Reader)
		if err == io.EOF || c.State == imap.LogoutState {
			return nil
		}
		if err != nil {
			c.ErrorLog.Println("error reading response:", err)
			if imap.IsParseError(err) {
				continue
			} else {
				return err
			}
		}
```

**Comment by ihippik** [comment]
any news?)

**Comment by emersion** [comment]
Sorry, I don't have time to investigate this issue right now. Please send a pull request fixing it!

**Comment by emersion** [comment]
This has been fixed in https://github.com/emersion/go-imap/pull/198
