### ISSUE TITLE
How to read Flags/Unseen mail

### ISSUE THREAD

**Issue by tito10047** [emersion/go-imap#141]
How I can read flags like if mail is Unseen
Thanks

**Comment by emersion** [comment]
You can use `c.Fetch` with `imap.FlagsMsgAttr`. The flags list for each message is in `Message.Flags`. Just check if there is `imap.SeenFlag` in the list.

**Comment by sauravmaropost** [comment]
Hi Emerson.
I am facing issue. How we could mark trail(Conversational) mails to seen. I am trying to change flag of email from seen to unseen. It is working fine for single email but not for emails who have replies. Could you please help me in same.
Thanks
	seqSet := new(imap.SeqSet)
	seqSet.AddNum(uids...)

	operation := imap.FormatFlagsOp("+FLAGS.SILENT", false)

	flags := []interface{}{imap.SeenFlag}
	if err := client.Store(seqSet, operation, flags, nil); err != nil {
		fmt.Println("SeenMailBoxEmail Flag Update Failed : ", err)
	}

	if err := client.Expunge(nil); err != nil {
		fmt.Println("SeenMailBoxEmail update Failed : ", err)
	}
