### ISSUE TITLE
fetch specifics messasge body by UID

### ISSUE THREAD

**Issue by tito10047** [emersion/go-imap#142]
I need find specifics emails. So I fetch all emails evelope and flags and by loop identify message by subject with regex. But when I find it, I need fetch message body and attachements. 

Ho I can fetch body message when I have `imap.Message` without body

**Comment by emersion** [comment]
You should use `c.Search` to find specific emails. There's [an example in the docs](https://godoc.org/github.com/emersion/go-imap/client#example-Client-Fetch) showing how to fetch messages, and [another example in the wiki](https://github.com/emersion/go-imap/wiki/Fetching-messages) showing how to fetch and parse message bodies.
