### ISSUE TITLE
I found some bcc  email only has 9 fields, So I  modify this file

### ISSUE THREAD

**Issue by vasth** [emersion/go-imap#143]
https://github.com/emersion/go-imap/blob/395a1a3bc89048049f09baa5204fbcbed414a972/message.go#L697

```
// Parse an envelope from fields.
func (e *Envelope) Parse(fields []interface{}) error {
         //fmt.Println("len(fields)", len(fields))
	  
	if len(fields) < 9 {  
		return errors.New("ENVELOPE doesn't contain 9 fields")
	}else{
		if len(fields) == 9{ //Email that does not contain BCC
		 
		}else if len(fields) < 10 {
			return errors.New("ENVELOPE doesn't contain 10 fields")
	    }
	}
	
	 
	if date, ok := fields[0].(string); ok {
		e.Date, _ = parseMessageDateTime(date)
	}
	if subject, err := ParseString(fields[1]); err == nil {
		e.Subject, _ = decodeHeader(subject)
	}
	if from, ok := fields[2].([]interface{}); ok {
		e.From = ParseAddressList(from)
	}
	if sender, ok := fields[3].([]interface{}); ok {
		e.Sender = ParseAddressList(sender)
	}
	if replyTo, ok := fields[4].([]interface{}); ok {
		e.ReplyTo = ParseAddressList(replyTo)
	}
	if to, ok := fields[5].([]interface{}); ok {
		e.To = ParseAddressList(to)
	}
	if cc, ok := fields[6].([]interface{}); ok {
		e.Cc = ParseAddressList(cc)
	}
	if len(fields) == 9{ 
		if bcc, ok := fields[7].([]interface{}); ok {
			e.Bcc = ParseAddressList(bcc)
		}
		if inReplyTo, ok := fields[7].(string); ok {
			e.InReplyTo = inReplyTo
		} 
		if msgId, ok := fields[8].(string); ok {
			e.MessageId = msgId
		}
	}else{
	    if bcc, ok := fields[7].([]interface{}); ok {
			e.Bcc = ParseAddressList(bcc)
		}
		if inReplyTo, ok := fields[8].(string); ok {
			e.InReplyTo = inReplyTo
		} 
		if msgId, ok := fields[9].(string); ok {
			e.MessageId = msgId
		}
	}
	

	return nil
}
```

**Comment by emersion** [comment]
Which server?

**Comment by vasth** [comment]
china  QQ mail server （The biggest mail service in China）

**Comment by emersion** [comment]
According to the RFC, this is non-standard: https://tools.ietf.org/html/rfc3501#page-77

**Comment by vgxbj** [comment]
Yes, I encountered this problem as well, thanks for your solution ... I hate irregular things

**Comment by chenjie4255** [comment]
@emersion 
However, I think there should be some ways to helping us to skip parsing such mail. it shouldn't just leave an error and stop code to handle the rest unparsed mail as it's behavior now.

**Comment by emersion** [comment]
This is a china QQ bug. Send them a bug report.

**Comment by chenjie4255** [comment]
Yes,  I did send them a report about this.
 
But what I mean is that if someone sent you an email with QQ mail server, the Fetch function will never work since it contains this invalid mail. It will be better if there is a proper way to handle this situation.

**Comment by iredmail** [comment]
Tip for users who're trying to use go-imap with QQ mail:

QQ IMAP server may return non RFC compliant response for the IMAP `FETCH` command, currently found parameters are:

- imap.FetchEnvelope
- imap.FetchInternalDate

The solution is try to avoid them, and use `imap.FetchRFC822*` instead.

------------
QQ IMAP 服务器在处理 IMAP 指令 `FETCH` 指定的一些内容时，返回的数据不符合 RFC 规范，
导致 go-imap 无法处理返回数据并出错。建议在 `Fetch()` 函数里尽可能不使用以下的参数：

- imap.FetchEnvelope
- imap.FetchInternalDate

另，QQ 的 SMTP 服务器也有一些不规范的地方。
