### ISSUE TITLE
Demo code at README does not show any email on iOS

### ISSUE THREAD

**Issue by tzickel** [emersion/go-imap#145]
Tested on iOS version 10.3 builtin mail.app. It tells me no messages in INBOX (from my understanding there should be an example email). The authentication part seems to work ok.

**Comment by emersion** [comment]
Can you set `Server.Debug = os.Stdout` and paste the network activity here?

**Comment by tzickel** [comment]
go run server.go
2017/11/01 20:47:25 Starting IMAP server at localhost:1143
* OK [CAPABILITY IMAP4rev1 AUTH=PLAIN] IMAP4rev1 Service Ready
1 LOGIN username password
1 OK [CAPABILITY IMAP4rev1] LOGIN completed
* OK [CAPABILITY IMAP4rev1 AUTH=PLAIN] IMAP4rev1 Service Ready
1 LOGIN username password
1 OK [CAPABILITY IMAP4rev1] LOGIN completed
2 LIST "" ""
* LIST (\Noselect) "/" /
2 OK LIST completed
3 LIST "" "*"
* LIST () "/" INBOX
3 OK LIST completed
4 SELECT INBOX
* FLAGS (\Seen)
* OK [PERMANENTFLAGS (\*)] Flags permitted.
* 1 EXISTS
* 0 RECENT
* OK [UNSEEN 0] Message 0 is first unseen
* OK [UIDNEXT 7] Predicted next UID
* OK [UIDVALIDITY 1] UIDs valid
4 OK [READ-WRITE] SELECT completed
5 UID SEARCH 1:* NOT DELETED
* SEARCH
5 OK UID SEARCH completed
6 UID SEARCH 1:* DELETED
* SEARCH
6 OK UID SEARCH completed
7 NOOP
7 OK NOOP completed
8 UID SEARCH 1:* NOT DELETED
* SEARCH
8 OK UID SEARCH completed
9 UID SEARCH 1:* DELETED
* SEARCH
9 OK UID SEARCH completed
10 NOOP
10 OK NOOP completed
11 UID SEARCH 1:* NOT DELETED
* SEARCH
11 OK UID SEARCH completed
12 UID SEARCH 1:* DELETED
* SEARCH
12 OK UID SEARCH completed

Shows no email in INBOX.

**Comment by emersion** [comment]
The `5 UID SEARCH` command seems broken with the `memory` backend.

**Comment by emersion** [comment]
Okay, the current `backendutil` design for search queries is broken. Basically search criteria are split into several groups: first sequence number and UID, then date, then flags, and then all remaining things. That doesn't work well with `NOT` and `OR` criteria because we can't do partial searches with them.

**Comment by emersion** [comment]
Fixed by https://github.com/emersion/go-imap/pull/241
