### ISSUE TITLE
Mailbox select | Unhandled response: &{* OK MYRIGHTS [acdilrsw] ACL}

### ISSUE THREAD

**Issue by c4ud3x** [emersion/go-imap#147]
Hi everyone.

I managed to log into my email account (www.freenet.de/index.html).
I'm selecting my inbox with this code:

`_, err = client.Select("INBOX", true)`

As a result this line gets printed into the console:
> imap/client: 2017/11/05 20:01:14 response has not been handled: &{* OK MYRIGHTS [acdilrsw] ACL}

With my second account (t-online.de) I get another error when accessing messages:

> imap/client: 2017/11/05 20:24:13 response has not been handled: &{* OK HIGHESTMODSEQ [893] Highest}

I tried to do some research and ended up in `client.go` at line `167`. Unfortunately I'm not an expert in GO so I (currently) dont understand the full code. That line is the bottom-most I could find thats raising that message.

Tell me if you need more information.
Thank you very much.

**Comment by c4ud3x** [comment]
I just found a report for the second one here: https://github.com/emersion/go-imap/issues/79. So I'll follow  that topic over there. First one is still open for me.

**Comment by emersion** [comment]
The first one is because there's no ACL support right now. The second one is because CONDSTORE is also missing. This is not an error, just a warning. If you don't use the ACL or CONDSTORE, you can ignore this warning.

**Comment by c4ud3x** [comment]
Thanks for the response. Is there any chance to disable or hide that warning from the console? I'm using the console to output information to me. This errors in between are a bit annoying.

From your answer I conclude the client won't get interruped in any way. Then it's ok for me.

**Comment by emersion** [comment]
Yeah, you can set `Client.ErrorLog` to a logger that discards everything.
