### ISSUE TITLE
The specified charset is not supported

### ISSUE THREAD

**Issue by francisco4challenge** [emersion/go-imap#150]
Hey i have the following string i'm trying to use in the search.
'Pedido de adição de danos à viatura 80-80-AM'

But i get the following error: 
Error: The specified charset is not supported.

In the log:

=> 'A6 UID SEARCH CHARSET UTF-8 UNSEEN SUBJECT {53}'
<= '+ Ready for additional command text.'
=> 'Pedido de adiÃÂ§ÃÂ£o de danos ÃÂ  viatura 80-80-AM\r\n'
<= 'A6 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.'

What can i do to support this characters?

**Comment by emersion** [comment]
That's strange, in this case the client is supposed to retry with charset US-ASCII:

https://github.com/emersion/go-imap/blob/v1/client/cmd_selected.go#L110

**Comment by francisco4challenge** [comment]
Would you like me to post the code?

**Comment by emersion** [comment]
What server are you using? Can you try searching with only ASCII chars?

Basically your server doesn't support UTF-8, so it kind of makes sense not to be able to execute UTF-8 searches.

**Comment by francisco4challenge** [comment]
Outlook doesn't support UTF8?

**Comment by emersion** [comment]
I've no idea. I've heard of Microsoft e-mail servers not supporting UTF-8, but I haven't checked. But the reply from the server seems to indicate that UTF-8 isn't supported.

>Can you try searching with only ASCII chars?

**Comment by francisco4challenge** [comment]
It seems like it, back to gmail. Thanks anyway
