### ISSUE TITLE
Email inside another email

### ISSUE THREAD

**Issue by delaneyj** [emersion/go-imap#154]
I have a situation where the I'm trying to read the contents of a *.eml attachment, which in itself has another email attachment (a .txt) file.

I can read the first layer not problem (and convert the body to a string to view in the logs).  However I don't know how to convert the contents into another email message.  Tried `mail.CreateReader(p.Body)` but get an `EOF` error.  Any examples of how to do this?  The Content-Type of the first layer of attachment is `message/rfc822`.

**Comment by emersion** [comment]
Do you read the contents of the `message/rfc822` part (that is, consume the nested mail reader) inside the loop that reads the outer message? I should probably add that to the docs.

If you do, it would be nice if you could extract the email and the code that reproduces the issue. Post it here, and we'll make a unit test from it.

**Comment by delaneyj** [comment]
I tried to read the Body of the top level Attachment part (x.eml)  via the `mail.CreateReader(p.Body)`.   Yes, that's inside the loop that reads the outer message.  Specifically its trying to create a new reader inside reading the top level attachment.  I hope this makes sense, parsing out IMAP is very new to me, especially in Go.

**Comment by emersion** [comment]
So I added a test and `go-message` parses nested messages correctly: https://github.com/emersion/go-message/commit/174e2ad271e6616bccfd107b308ced85074c2e3e

You have to consume completely the nested `mail.Reader` before the next call to `NextPart`, otherwise it'll get discarded. I've updated the docs to make this clear.
