### ISSUE TITLE
Support for "References" header

### ISSUE THREAD

**Issue by xplodwild** [emersion/go-imap#156]
Hello

Is there any support planned for the "References" header in the client? It would be quite useful to be able to access it to perform threading of related e-mails.

More information about the header: https://cr.yp.to/immhf/thread.html

As I have an immediate need for it, if there is nothing against supporting it, I might do a PR for it. If you have any hints or tips on how to add it cleanly, let me know so I can save you some time.

Thanks

**Comment by emersion** [comment]
This header is not part of the IMAP spec (or any IMAP extension), so I don't see what you mean by "supporting it". If you want to access its content, you can use a mail parsing library like [`go-message`](https://github.com/emersion/go-message).

**Comment by xplodwild** [comment]
It is actually part of the RFC, see https://www.ietf.org/rfc/rfc2822.txt 

```
references      0*              1               SHOULD occur in some
                                                replies - see 3.6.4
```

The `References` header is part of the email message headers, which as far as I know, are not directly accessible. The `Fetch()` method returns an `imap.Message` which has pre-parsed fields (such as `InReplyTo` and `MessageId` in the `Envelope` struct), but there is no way to retrieve headers that aren't put in the structure (or is it?)

**Comment by emersion** [comment]
It's part of the Internet Message Format RFC - but not of the IMAP RFC. Some header fields are returned as part of the message metadata as you said, but these are special cases spec'd in the IMAP RFC. Threading header fields are not supported. If you just want to retrieve the References header, you can with the current API.

There's an IMAP extension for threading though, but I'm not sure it does what you want.

**Comment by xplodwild** [comment]
Okay for the RFC - subtle difference. Could you point me to what I can use to retrieve the mail headers then? I've been looking at `Client` methods, but besides `Fetch` which returns a fixed `Message`, I couldn't find anything returning raw fields?

**Comment by emersion** [comment]
I've updated the library to make things like this easier.

`Client.Fetch` retrieves data about a message. This can be the body structure, the envelope, the flags, the date and so on. This can also be a part of the message body. For instance, you can retrieve only a section of a specific MIME part (say bytes 0 to 1024 or the third part), or only some header fields. This can be done in `go-imap` like this:

```go
// Retrieve only the date and From header fields
section := &imap.BodySectionName{
	BodyPartName: imap.BodyPartName{
		Specifier: imap.HeaderSpecifier,
		Fields: []string{"Date", "From"},
	},
}

err := c.Fetch(seqset, []imap.FetchItem{section.FetchItem()}, messages)

literal := msg.GetBody(section)
```

`literal` is a `io.Reader` that contains the header fields. This header can be parsed with another library (for this simple task [`net/textproto`](https://golang.org/pkg/net/textproto/#Reader.ReadMIMEHeader) might be enough, for more complicated stuff `go-message` can help).

Also see the `Client.Fetch` example here: https://godoc.org/github.com/emersion/go-imap/client#ex-Client-Fetch

**Comment by xplodwild** [comment]
Awesome, thank you very much :)
