### ISSUE TITLE
Goroutine seen block when use store function change flag

### ISSUE THREAD

**Issue by chenguifeng** [emersion/go-imap#158]
Hi.When i use function store to change this message flag.
It can not return so i write down this code, and it always print timeout.
Did anything wrong with my code?

```go
func setSeenFlag(c *client.Client, msg *imap.Message) (err error) {
	if c == nil {
		return fmt.Errorf("[setSeenFlag] para c is nil")
	}
	if msg == nil{
		return fmt.Errorf("[setSeenFlag] para msg is nil")
	}

	seen_Set, _ := imap.ParseSeqSet(strconv.Itoa(int(msg.SeqNum)))
	done := make(chan error, 1)

	go func() {
		done <- c.Store(seen_Set, imap.AddFlags, []interface{}{imap.SeenFlag}, nil)
	}()

	if err != nil {
		return errors.Errorf(err, "[setSeenFlag] resv down err")
	}


	select {
	case err := <- done:
		fmt.Println("recv done")
		if err != nil {
			return errors.Errorf(err, "[setSeenFlag] resv down err")
		}

	case <- time.After(2 * time.Second):
		fmt.Println("Timed out")
	}
	return nil
}
```

**Comment by emersion** [comment]
Can you enable logs, and post them here?

```go
c.SetDebug(os.Stdout)
```

**Comment by chenguifeng** [comment]
when i enable logs.It run successful.
After disable logs, try several times, it still run successful.
So weird.If l got it again, post it here.
Thanks.

**Comment by emersion** [comment]
That might be due to a network issue, or this could be a bug in go-imap. Let me know if you get more info! I'll close this issue for now, feel free to reopen if needed.

**Comment by chenguifeng** [comment]
Hi, i got this problem again.I found if i fetch one message, it can return in time.When i fetch 50 messages to find my target message, it will be time out.But so many private information here.If any Identifier can distinguish those information?

**Comment by emersion** [comment]
What's your code doing exactly? You can't fetch messages with a loop, and execute store commands in that loop for instance.

**Comment by chenguifeng** [comment]
I use fetch commands to return 50 messages. Then range those message. Store commands was inside the range.
So I should return the message’s Seqnum which i need to set flags, than use it when range was over?My key code
Is here.

seqset.AddRange(from, to)
messages := make(chan *imap.Message, 10)
section := &imap.BodySectionName{}


items := []imap.FetchItem{imap.FetchFlags}
items = append(items, section.FetchItem())
done = make(chan error, 1)
go func() {
   done <- c.Fetch(seqset, items, messages)
}()
for msg := range messages {  
   if len(msg.Flags) == 0 {
   
      section, _ := imap.ParseBodySectionName("BODY[]")
      r := msg.GetBody(section)
      if r == nil { 
         continue
      }

  
      mr, err := mail.CreateReader(r)
      
      header := mr.Header
      subject, err := header.Subject()
      
      if strings.Contains(subject, targetSubject) {
        
         for {
            p, err := mr.NextPart()
            if err == io.EOF {
               break
            } else if err != nil {
               return 
            }
            
            switch h := p.Header.(type) {
            case mail.TextHeader:
               content, err := ioutil.ReadAll(p.Body)
               if err != nil {
                  return "", errors.Errorf(err, "[getVoucher] Read message fail")
               }
               if !strings.Contains(string(content), refNo) {
                  continue
               }

                targetContent = string(content)
               //setSeenFlag 
               if err := setSeenFlag(c, msg); err != nil {
                  logger.Errorf("requestid:%s refNo:%s[getVoucher] setSeenFlag fail err:%s \n", requestid, refNo, err)
               }
               fmt.Println("end of setSeenFlag")
            case mail.AttachmentHeader:
               filename, _ := h.Filename()
               logger.Error("requestid:%s refNo:%s[getVoucher] get Attachment!filename:%s \n", requestid, refNo, filename)
            }
         }

      }

   }
}

if err := <-done; err != nil {
   return "", errors.Errorf(err, "[getVoucher] get message fail")
}

func setSeenFlag(c *client.Client, msg *imap.Message) (err error) {
   if c == nil {
      return fmt.Errorf("[setSeenFlag] para c is nil")
   }
   if msg == nil {
      return fmt.Errorf("[setSeenFlag] para msg is nil")
   }

   seen_Set, _ := imap.ParseSeqSet(strconv.Itoa(int(msg.SeqNum)))
   done := make(chan error, 1)

   go func() {
      done <- c.Store(seen_Set, imap.AddFlags, []interface{}{imap.SeenFlag}, nil)
   }()

   if err != nil {
      return errors.Errorf(err, "[setSeenFlag] resv down err")
   }
   //there can be bug set time out 2s
   select {
   case err := <-done:
      fmt.Println("[setSeenFlag]recv done")
      if err != nil {
         return errors.Errorf(err, "[setSeenFlag] resv down err")
      }

   case <-time.After(2 * time.Second):
      fmt.Println("[setSeenFlag]Timed out")
   }
   return nil
}

**Comment by emersion** [comment]
Yeah: `messages` is a channel, this means the FETCH command response is being read while you iterate over the channel. If you send a STORE command during the FETCH response, it'll wait for the FETCH to finish - thus a deadlock will occur.

You'll need to add UIDs you want to STORE in a `SeqSet` for instance, and send the STORE outside the loop, when you're sure the FETCH command is finished. This has the benefit of grouping all STORE commands together - you'll send just one STORE command instead of many.

**Comment by chenguifeng** [comment]
Think a lot.It fix my problem.
