### ISSUE TITLE
where are the mails stored? eg with the APPEND command

### ISSUE THREAD

**Issue by worddevfr** [emersion/go-imap#159]
What is the directory path that contains the messages

**Comment by emersion** [comment]
Can you explain more precisely your question?

Are you using the server part of this library?

**Comment by worddevfr** [comment]
I test the server imap and I want to know where (in which location) the server stores the messages (with the command APPEND, the server imap creates a message (mail), it is saved where this message?). Another example: the CREATE command creates a subfolder, this subfolder is created where? [Google Translate :) ]

**Comment by emersion** [comment]
It depends of the backend you use. The default `memory` backend stores messages in memory. You code implement another backend if you want to store messages on disk.
