### ISSUE TITLE
Hide the output messages

### ISSUE THREAD

**Issue by matiux** [emersion/go-imap#160]
When I select a folder with 
```
mbox, err := i.Client.Select(mailbox.Name, false)
```
I get this output messages:
```
imap/client: 2017/12/26 22:49:10 response has not been handled: &{* OK CLOSED [] Previous mailbox closed.}
imap/client: 2017/12/26 22:49:10 response has not been handled: &{* OK HIGHESTMODSEQ [1] Highest}
```

Is there a way to hide / suppress this output?

**Comment by matiux** [comment]
The first message has disappeared after adding `i.Client.Close()` to close the mailbox after using it.
But I don't still have find the solution for `HIGHESTMODSEQ` output message

**Comment by emersion** [comment]
You don't need to close the mailbox before another select. This message is just an info message sent by the server. The second one is an IMAP extension.

I've been wondering about removing this warning for quite some time. https://github.com/emersion/go-imap/commit/75afcb56d35e92b585b2281b6e411c113a0110ba does that.

**Comment by matiux** [comment]
Is there a way to set Client.ErrorLog to hide this messages?

**Comment by emersion** [comment]
You can set them to `ioutil.Discard` but you'll miss real client errors.

**Comment by matiux** [comment]
So am I constrained to receive that server messages?

**Comment by emersion** [comment]
No. Update to the latest go-imap and you shouldn't have these messages anymore.

**Comment by matiux** [comment]
I have used `dep ensure -add github.com/emersion/go-imap/client` to install...
Maybe in this way I don't have the latest version?

In Gopkg.lock I have this:
```
[[projects]]
  name = "github.com/emersion/go-imap"
  packages = [".","client","commands","responses","utf7"]
  revision = "840b16b212bff35b595e708937c6d60861cfab49"
  version = "v0.9"

```

**Comment by emersion** [comment]
You've installed v0.9. Here's an upgrade guide for v1: https://github.com/emersion/go-imap/issues/152

**Comment by matiux** [comment]
Maybe to use latest version I can't use dep...

**Comment by emersion** [comment]
You can, just upgrade to v1.

**Comment by matiux** [comment]
```
Solving failure: No versions of github.com/emersion/go-imap met constraints:
        v0.9: Could not introduce github.com/emersion/go-imap@v0.9, as it is not allowed by constraint ^1.0.0 from project github.com/acme/project.
        v1: Could not introduce github.com/emersion/go-imap@v1, as it is not allowed by constraint ^1.0.0 from project github.com/acme/project.
        failed-append: Could not introduce github.com/emersion/go-imap@failed-append, as it is not allowed by constraint ^1.0.0 from project github.com/acme/project.
        v0: Could not introduce github.com/emersion/go-imap@v0, as it is not allowed by constraint ^1.0.0 from project github.com/acme/project.
```

**Comment by emersion** [comment]
v1 is a branch, so you'll need to add a branch constraint instead.

**Comment by matiux** [comment]
Finally I solved. I did not know that in dep I could indicate the branch
```
[[constraint]]
  name = "github.com/emersion/go-imap"
  #version = "0.9.0"
  branch = "v1"
```
thanks for the patience. Now the server messages are not shown
