### ISSUE TITLE
Split storage and authentication

### ISSUE THREAD

**Issue by dolanor** [emersion/go-imap#168]
Currently, Backend is all about users (with the Login() func).
Once you got authenticated, you can get the mailbox associated to the user. What if the mailbox info is not available from the authentication backend.

What I propose is that we have
* The authentication backend (that could use LDAP, for example)
* The storage/mailbox backend (that could use maildir, for example)

And when we create a server with `server.New()` we put both backend in.
Maybe it's already working like that in the Multi backend, but since Backend only has 1 function defined, I guess not.

Maybe the code could look like:
```go
type Backend interface {
    Authenticator
    Storer
}

type Authenticator interface {
    Login(username, password string) (User, error)
}

type Storer interface {
    ListMailboxes(user User, subscribed bool) ([]Mailbox, error)
    GetMailbox(user User, name string) (Mailbox, error)
// …
}
```

It might not be the correct idea, but along those line.
It's very late for me, I hope I didn't write garbage out of my head.

**Comment by emersion** [comment]
The `Backend` is just an interface, you can wire up anything you want behind, including split storage and auth interfaces. Just write a backend that is constructed from both interfaces:

```go
func NewBackend(Authenticator, Storer) backend.Backend
```

**Comment by dolanor** [comment]
Got it.
It's just that if we want authenticate with oauth or ldap and store via imap-proxy, S3, maildir, we already explose the number of implementation of backends where maybe we could make it orthogonal. Does it make sense?

Yes my example was because it was too late, of course it has multiple mailboxes. I'm editing now

**Comment by emersion** [comment]
It does make sense, but it's outside the scope of this library. Some backends may do auth _and_ storage, some may store whether a mailbox is subscribed or not in a separate file, but we're not going to split each interface to accommodate these details.

Though, this split does make sense in standalone e-mail server projects like maddy.
