### ISSUE TITLE
Client.Close() does not close the conn on error

### ISSUE THREAD

**Issue by cseeger-epages** [emersion/go-imap#173]
I had a strange problem getting `short write` errors. Trying to eliminate the connection and reconnect solves the problem but the connection itself does not get closed properly and stays in `CLOSE_WAIT` state. 

Getting `short write` errors results in the same error when using `Client.Close()`.

It would be nice if the `func (c *Client) Close() error` can also close the connection using `conn.Close()` from `net` package if an error occurs since `conn  *imap.Conn` is not public usable on the `type Client struct`.

**Comment by cseeger-epages** [comment]
Another way would be to provide a `func (c *Client) Terminate()` function to hard kill the connection if nessessary

**Comment by emersion** [comment]
Yeah, PRs welcome!

Proposed plan:
1. Refuse to send commands when connection is closed
2. Add `Terminate`
3. Add an optional timeout for `Close`

**Comment by cseeger-epages** [comment]
Ill code it together and drop you a PR if a have some time.

**Comment by cseeger-epages** [comment]
Here is the PR for the Terminate function: https://github.com/emersion/go-imap/pull/174.
