### ISSUE TITLE
Getting raw responses

### ISSUE THREAD

**Issue by skinass** [emersion/go-imap#175]
HI.

I want to get raw responses for logging. For example i want to log raw responses from `Login()` and `Authenticate()` even if it is _ok_. How can i get them. And the same question for `Execute()`, can i get raw response in my handler ?

**Comment by emersion** [comment]
You can probably use `Client.SetDebug` for this.

**Comment by Skinass** [comment]
sometimes Client.SetDebug provides incomplete data
For example a small program with only `Client.Login()` and `Client.Logout()` has output
>__C__- W4T8Sg LOGIN testmail@host.com 123123
>__C__- pXeHOg LOGOUT
>__S__- \* BYE IMAP4rev1 Server logging out

when the real tcp exchange looks like
>__S__- \* OK <servname> IMAP4rev1 at imap.host.com:993 ready to talk with ::ffff:185.6.245.226:57620, 2018-Feb-20 15:59:20, KxODiS0qd8d1
>__C__- W4T8Sg LOGIN testmail@host.com 123123
>__S__- \* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID IDLE MOVE
>__S__- W4T8Sg OK LOGIN Completed.
>__C__- pXeHOg LOGOUT
>__S__- \* BYE IMAP4rev1 Server logging out
>__S__- pXeHOg OK LOGOUT completed

**Comment by Skinass** [comment]
Found a strange behavior.
As described before. The example bellow won't let you see anything like "123456 OK LOGIN Completed." or any other response from server.
```golang
c , _ := client.New(conn)
c.SetDebug(os.Stdout)
c.Login(user,pswd)
```

BUT.
If you add `c.debug = os.Stdout`  [here](https://github.com/emersion/go-imap/blob/v1/conn.go#L100)
So the debug behaviour gets initialised before the first read from connection, everything works fine. And Stdout provides complete log.

I propose to add a function into "client" package.
It might looks like this:
```golang
func NewWithDebug(conn net.Conn, debug io.Writer) (*Client, error){...}
```
This provides debug setup before  Client initialisation.


However this "bug" looks strange. If i am doing something wrong, please tell me)

**Comment by emersion** [comment]
Fixed in v2.
