### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by SUP3RIA** [emersion/go-imap#177]
Any tipps to avoid memmory leaks whilst running the client example concurrently with different connections? It fills pretty fast 1 Gig of Ram.

I could investigate more if this is not a known issue.

I suspect this is a issue with TLS Sessions or something.
Maybe you could help.

Thx

```
func imaplogin(domain string, name string, password string) bool {
	// Connect to server
	c, err := client.DialTLS(domain, nil)
	if err != nil {
		log.Println(err)
		return false
	}
	if err := c.Login(name, password); err != nil {
		log.Println(err)
		return false
	}
	defer c.Close()
	defer c.Logout()
	defer c.Terminate()
	return true
}
```

**Comment by emersion** [comment]
I'm interested in more details.

**Comment by SUP3RIA** [comment]
This example connects to imap servers and checks if credetials are valid similar how a mail client would do. In this case random credentials are used hence always false. That the memory fills up until killed by kernel. 

`package main

import (
	"log"
	"math/rand"
	"sync"

	"github.com/emersion/go-imap/client"
)

var wg sync.WaitGroup

func imaplogin(domain string, name string, password string) bool {
	defer wg.Done()
	// Connect to server
	c, err := client.DialTLS(domain, nil)
	if err != nil {
		log.Println(err)
		return false
	}
	if err := c.Login(name, password); err != nil {
		log.Println(err)
		return false
	}
	defer c.Logout()
	defer c.Close()
	defer c.Terminate() //just to make sure
	return true
}

var letters = []rune("abcdefghijklmno3pqrstuvw1xyzABCDEFGHI#!JKLMNOPQRSTUVWXYZ")

func randSeq(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letters[rand.Intn(len(letters))]
	}
	return string(b)
}

func main() {
	hosts := [11]string{"imap.mail.yahoo.com", "imap.aol.com", "imap-mail.outlook.com",
		"imap.mail.com", "imap.lycos.com", "imap.gmail.com", "imap.gmx.com",
		"imap.directbox.com", "imap.mail.ru", "imap.web.de", "imap.yandex.com"}
	for {
		for w := 1; w <= 500; w++ {
			for _, host := range hosts {
				name := randSeq(5) + "@test.com"
				pwd := randSeq(10)
				wg.Add(1)
				go imaplogin(host+":993", name, pwd)
			}
		}
		wg.Wait()
	}
}
`

**Comment by SUP3RIA** [comment]
You can close this. I should read next time the Go TLS dokumentation better.

`config := &tls.Config{SessionTicketsDisabled: true}`

Solves this issue for me.

**Comment by emersion** [comment]
That's good to hear!

**Comment by R2D2Dan** [comment]
Good afternoon, I noticed that I met with the same problem. When I connect to the server using func DialTLS(addr string, tlsConfig *tls.Config) my RAM starts to grow.
I use the (c *Client) Idle() function to wait for updates from the mail, when I receive updates, I start a new session with a new connection and after each connection my memory starts to grow
If there is an opportunity to help me with this problem, then tell me how, I will be very grateful.
I'm still new to GO and new to programming, so I don't quite understand this problem yet. Thank you.

**Comment by R2D2Dan** [comment]
> That's good to hear!
Good afternoon, I noticed that I met with the same problem. When I connect to the server using func DialTLS(addr string, tlsConfig *tls.Config) my RAM starts to grow.
I use the (c *Client) Idle() function to wait for updates from the mail, when I receive updates, I start a new session with a new connection and after each connection my memory starts to grow
If there is an opportunity to help me with this problem, then tell me how, I will be very grateful.
I'm still new to GO and new to programming, so I don't quite understand this problem yet. Thank you.

**Comment by dmitrymaslov99** [comment]
> R2D2Dan

I have same issue. When my connection closes, it doesn't release resources. And with each new connection, the memory usage increases
