### ISSUE TITLE
Getting flags for emails

### ISSUE THREAD

**Issue by Cycl0pe** [emersion/go-imap#179]
Hello,

My level of golang is quite limited and I have some difficulties finding a way to retrieve the flags for each email. Could you post a code example for this task?

Thanks a lot !

**Comment by fspaniol** [comment]
Hello,
Since I don't know up to which point you were able to get, I'll just assume you were not able to Fetch any messages, you can simply do the following:
```
// create the channels
messages := make(chan *imap.Message, r.maxEntries)
fail := make(chan error, 1)

// call the function to fetch the emails and only importing their flags (that's specified by imap.FetchFlags
go func() {
   fail <- r.client.Fetch(s, []imap.FetchItem{imap.FetchFlags}, messages)
}()
for m := range messages {
   fmt.Println(m.Flags)
}
if err := <-fail; err != nil {
   fmt.Println("Done")
}
```

Is this what you were looking for?
Best,
Fernando

**Comment by Cycl0pe** [comment]
Thank you Fernando!
It works like a charm!
Is there a way to fetch the messages (Body/Headers) and the flags for each email at the same time?

Thank you,

Cycl0pe

**Comment by fspaniol** [comment]
Glad it worked 👍 

Well, if you want to get the all these information for each email without concurrency, you can simply use:
```go
 fail <- r.client.Fetch(s, []imap.FetchItem{imap.FetchFlags, imap.FetchEnvelope, imap.FetchBody}, messages)
```

In fact, there's a whole lot that you can get, you can get all the information listed here:
https://tools.ietf.org/html/rfc3501#page-55

You will only have to check what their equivalente constants are in here:
https://github.com/emersion/go-imap/blob/54b9f1de1373355d254989e7e3205e18a758624e/imap.go

Now, if you want to do for all emails at the same time, you might want to have a look at Go Routines:
https://tour.golang.org/concurrency/1

The Tour of Go is really nice btw :)

Hope this helps you,
Fernando

**Comment by Cycl0pe** [comment]
Thank you Fernando!

It's perfect!

Cycl0pe
