### ISSUE TITLE
mail: missing word in phrase: charset not supported: "windows-1252"

### ISSUE THREAD

**Issue by Cycl0pe** [emersion/go-imap#182]
When retrieving some emails, I'm falling onto this error for the header for:

" mail: missing word in phrase: charset not supported: "windows-1252" "

I have seen in the wiki you can use Charset.Reader but I don't know how to use it.

Thanks for your help!

Cycl0pe

**Comment by emersion** [comment]
You can try to follow the instructions here: https://github.com/emersion/go-imap/wiki/Charset-handling. Just setting the `imap.CharsetReader` variable with a reader supporting windows-1252 should fix your issue.

**Comment by Cycl0pe** [comment]
Thanks for your response! 
Could you give me an example knowing I'm using the example here: https://github.com/emersion/go-imap/wiki/Fetching-messages

My reader is declared like that:
``mr, err := mail.CreateReader(r)``

**Comment by emersion** [comment]
Just set the `imap.CharsetReader` at the beginning of the function.

**Comment by Cycl0pe** [comment]
I tried like that but it does not work properly:

` imap.CharsetReader, _ = charset.Reader( "windows-1252", r)`

Cycl0pe

**Comment by emersion** [comment]
```go
imap.CharsetReader = charset.Reader
```

Just put this somewhere. No `( "windows-1252", r)`.

**Comment by DeadNumbers** [comment]
> Just put this somewhere. No ( "windows-1252", r).

I'm put somewhere `imap.CharsetReader = charset.Reader`, but have error `unhandled charset "koi8-u"`

**Comment by emersion** [comment]
You need to add this charset manually with `charset.RegisterEncoding`
