### ISSUE TITLE
Logout cause leak resource?

### ISSUE THREAD

**Issue by Gnouc** [emersion/go-imap#185]
[IMAP RFC](https://tools.ietf.org/html/rfc3501#page-26) states that:

```
      The LOGOUT command informs the server that the client is done with
      the connection.  The server MUST send a BYE untagged response
      before the (tagged) OK response, and then close the network
      connection.
```

So when client logout, server  will close  the network connection. But currently, `client.Logout()` only execute the command, then set client state to `imap.LogoutState`. The client underlying connection is left as-is.

On user perspective, I want to Login again after logout, but it will give an error because the client connection is closed and can't connect to server again:

```
package main

import (
	"crypto/tls"
	"log"
	"os"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
)

func main() {
	log.Println("Connecting to server...")

	// Connect to server
	c, err := client.Dial("imap.example.com:143")
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")
	c.SetDebug(os.Stdout)

	// Don't forget to logout
	defer c.Logout()

	c.StartTLS(&tls.Config{InsecureSkipVerify: true})
	// Login
	if err := c.Login("cuonglm@example.com", "xxx"); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")

	log.Println(c.Logout())
	log.Println(c.State() == imap.LogoutState)
	log.Println(c.State() == imap.NotAuthenticatedState)

	// Login
	if err := c.Login("cuonglm@example.com", "xxx"); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")
	log.Println("Done!")
}
```

give:

```
2018/05/25 22:59:53 set tcp 192.168.1.105:45178: use of closed network connection
exit status 1
```
I'm not sure it can leak resources. In my program, I have a goroutine which will connect to server periodically to check user mailbox. If I do login -> check -> logout, then my program run for a period of time before stuck. The program stuck at where client operates command with server, like `STARTTLS`, `LOGIN` ...

If I increase the max open files limit of my process, then program run longer before stuck.

If I do login -> check -> sleep -> check -> ... The program run normally without any issue.

Any idea?

---

It would be better if we can do something to create new underlying connection if the old one is closed.

**Comment by emersion** [comment]
>But currently, client.Logout() only execute the command, then set client state to imap.LogoutState. 

Hum, this is the intended behavior. `client.Logout` sends LOGOUT and waits for the server to close the connection. When this happens, the goroutine that reads messages from the server exits and the connection is closed.

If you want to forcefully close the connection, use `Terminate`.

>On user perspective, I want to Login again after logout

Reusing old connections isn't possible, and I don't want to make this possible.

**Comment by Gnouc** [comment]
@emersion 

> If you want to forcefully close the connection, use Terminate.

Thanks, that's what I want.

> Hum, this is the intended behavior. client.Logout sends LOGOUT and waits for the server to close the connection. When this happens, the goroutine that reads messages from the server exits and the connection is closed.

So if I do Logout only, there's a chance that my function which is called `client.Logout` inside quit befoe that goroutine exit, which lead to leak resource?

If yes, then I think we should document this.

**Comment by Gnouc** [comment]
@emersion If I do Terminate right before Logout, I get this error:

```
2018/05/25 23:32:49 <nil>
2018/05/25 23:32:49 tls: use of closed connection
```
So all I have  to do is using `client.Terminate` alone, or something else?

**Comment by emersion** [comment]
>So if I do Logout only, there's a chance that my function which is called client.Logout inside quit befoe that goroutine exit, which lead to leak resource?

I don't understand what you mean, can you explain?

>So all I have  to do is using client.Terminate alone, or something else?

You'll need to decide either to close normally the connection or close it forcefully. You can't do both. You can try to close normally, and close forcefully after a timeout though. Maybe `net.Conn` timeouts can help.

**Comment by Gnouc** [comment]
@emersion Example with these code

```
func (w *worker) do() {
	for email, lastUID := range w.queue {
		username, password := extractUserInfo()
		seqs, err := w.checkNewMessage(username, password, lastUID)
		if err != nil {
			return
		}
	}
}

func (w *worker) checkNewMessage(username, password string, uid uint32) (seqs []uint32, err error) {
	c, err := client.Dial(w.cfg.ImapHost)
	if err != nil {
		err = errors.Wrap(err, "client.Dial")
		return
	}
	defer c.Logout()

	c.StartTLS(&tls.Config{InsecureSkipVerify: true})
	if lErr := c.Login(username, password); err != nil {
		err = errors.Wrap(lErr, "c.Login")
		return
	}

	inbox, err := c.Select(inboxFolder, false)
	if err != nil {
		err = errors.Wrap(err, "c.Select")
		return
	}

	return
}
```

So when I return from `w.checkNewMessage`, my client inside `w.checkNewMessage` is logged out, but the goroutine which waits for connection to server close is still there. If inside `w.do()`, the `return` happen before that goroutine finish, then we leaks that goroutine, no?

**Comment by emersion** [comment]
>If inside w.do(), the return happen before that goroutine finish, then we leaks that goroutine, no?

It's not really leaked, because the goroutine will exit as soon as the server closes the connection.

**Comment by Gnouc** [comment]
@emersion I'm not sure about this. Anyway, I'm happy with `c.Terminate()`.

Thanks for great library.
