### ISSUE TITLE
How To Search

### ISSUE THREAD

**Issue by fipso** [emersion/go-imap#186]
Hello,
how can I use the imap SEARCH command ?

**Comment by emersion** [comment]
Read the RFC, grep for SEARCH.

**Comment by fipso** [comment]
Hello,
sry for the stupid question.
How can i use this libary to make the Request with the command and get the response ?

**Comment by emersion** [comment]
There's an example on the GoDoc page.

**Comment by fipso** [comment]
The Doc just explanes how to create a search certeria:
https://godoc.org/github.com/emersion/go-imap#SearchCriteria

**Comment by emersion** [comment]
Here: https://godoc.org/github.com/emersion/go-imap/client#Client.Search

Sorry, I'm mistaken, there's no example (yet). You can read the tests to see some usage examples though.

**Comment by fipso** [comment]
Thanks a lot ;D
