### ISSUE TITLE
Doubts in FetchBody

### ISSUE THREAD

**Issue by NHibiki** [emersion/go-imap#188]
Hi, 

Thanks for building up such a helpful tool, but I met up with some problems. (probably it was simply because my misunderstanding of IMAP, but let's go on first lol)

By reading the source code of `go-imap`, I found that the content cannot be returned by doing `client.Fetch(seqset, []imap.FetchItem{imap.FetchBody})`, the `Body` column of responding data remains to be `nil`. But when I tried to fetch `imap.FetchRFC822Text`, I started to get what I wanted.

So I wondered what `imap.FetchBody` really stands for?

**Comment by emersion** [comment]
Hmm, can you log the keys of `Body`?

It's possible that the server replies with a `FetchItem` different from the one you sent. You'll probably want to describe which part of the message you want with `BodySectionName` and retrieve it with `Message.GetBody`.
