### ISSUE TITLE
Failed to parse body

### ISSUE THREAD

**Issue by wenerme** [emersion/go-imap#189]
I can not get body with FetchBody, when I add FetchRFC822, the parser will fail with

```
imap/client: 2018/06/21 00:49:30 error reading response: fields are not separated by a space
imap/client: 2018/06/21 00:49:30 error reading response: line doesn't end with a CR
imap/client: 2018/06/21 00:49:30 error reading response: expected a space
```

Then hang forever.

The content is html, encoded in gbk

![image](https://user-images.githubusercontent.com/1777211/41672844-8ed010ee-74ed-11e8-9462-8ab5dbc06e90.png)

I already add charset handler

```go
	imap.CharsetReader = func(charset string, r io.Reader) (io.Reader, error) {
		switch charset {
		case "gbk":
			return simplifiedchinese.GBK.NewDecoder().Reader(r), nil
		case "gb18030":
			return simplifiedchinese.GB18030.NewDecoder().Reader(r), nil
		default:
			logrus.WithField("charset", charset).Warn("unsupported charset")
		}
		return nil, nil
	};
```

Please help me, I can not get my email body.

**Comment by emersion** [comment]
Hmm, it seems that the IMAP parser is failing. What server are you using? Can you copy paste the debug log, removing sensitive information?

**Comment by wenerme** [comment]
The server is https://exmail.qq.com I give up trying to export the emails. I will post debug log if I meet this again.
