### ISSUE TITLE
How to run code as a service?

### ISSUE THREAD

**Issue by vsile** [emersion/go-imap#192]
How to run code as a service?

I run code with `go run goserver/imap.go` and get:
 
> user@c107 ~ $ go run goserver/imap.go
2018/07/13 10:10:01 Connecting to server...
2018/07/13 10:10:01 Connected
2018/07/13 10:10:01 Logged in
2018/07/13 10:10:01 Mailboxes:
2018/07/13 10:10:01 * INBOX
2018/07/13 10:10:01 * Junk
2018/07/13 10:10:01 * Спам
2018/07/13 10:10:01 * Отправленные
2018/07/13 10:10:01 * Черновики
2018/07/13 10:10:01 * Корзина
2018/07/13 10:10:01 * INBOX/РОИ
2018/07/13 10:10:02 Flags for INBOX: [\Answered \Flagged \Deleted \Draft \Seen]
2018/07/13 10:10:02 Last 4 messages:
2018/07/13 10:10:02 * Bug: Mentions
2018/07/13 10:10:02 * Обновлен статус вашего заявления 
2018/07/13 10:10:02 * Код подтверждения для аккаунта Google
2018/07/13 10:10:02 * Важное оповещение о безопасности связанного аккаунта Google
2018/07/13 10:10:02 Done!
user@c107 ~ $

I'd like to check a new post every 1 min? How can I do that? (without cron)

**Comment by emersion** [comment]
You questions seems more like a general Go question ("how can I call a function every X minutes in Go") rather than a go-imap question. Please try searching on other websites such as StackOverflow. I'm going to close this as off-topic.
