### ISSUE TITLE
Current version for dep

### ISSUE THREAD

**Issue by trueone** [emersion/go-imap#193]
Hi!

Can u please add current version of go-imap to DEP package manager?
Dep ensure downloads the old version (0.9) and examples doesnt work

**Comment by emersion** [comment]
I'm not sure what I should do here. Would releasing an alpha be enough?

**Comment by trueone** [comment]
I'm sorry, not sure what alpha is..
My problem is, when i run "go get github.com/emersion/go-imap", i can use examples from ur wiki

**Comment by emersion** [comment]
Just configure dep or whatever to use the master branch.

**Comment by shuLhan** [comment]
Which master branch?

**Comment by dmjones** [comment]
The following works for me in Gopkg.toml:
```toml
[[constraint]]
  name = "github.com/emersion/go-imap"
  branch = "v1"
```

**Comment by emersion** [comment]
Eh, yeah, the v1 branch, sorry.
