### ISSUE TITLE
When selecting a folder the unseen field is not set.

### ISSUE THREAD

**Issue by skx** [emersion/go-imap#194]
I'm writing a simple webmail client, and most of the code is good.  However I'm having issues retrieving a list of folders with unread messages.

There are two basic approaches I can see:

* Getting the mailbox list
  * Then for every mailbox "select" it, and see if `Unseen > 0`.
  * Alternatively I can select each message then run a search for messages `criteria.WithoutFlags = []string{imap.SeenFlag}`.

The second approach works as expected, however it is slower than the first.  Assume I've connected to a mailserver and handled errors I expect this to work:

     name := "Automated-attic"   // name of folder with 101 messages, two of which are unread.
     mbox, err := con.Select(name false)
     if err == nil {
          fmt.Printf("Unseen - Mailbox %s - Unseen:%d Total:%d\n", name, mbox.Unseen, mbox.Messages)
      }

I appreciate there is some confusion over whether "Unseen" is the UID of the first/next unread message, or the count of unread messages (`SELECT` vs. `EXAMINE` as per #106).  But in either case I seem to receiving Zero when the server actually sends a non-zero result.

Here is the response from the server:

         ZJzbRA SELECT Automated-attic
         * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
         * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
         * 101 EXISTS
         * 0 RECENT
         * OK [UNSEEN 100] First unseen.
         * OK [UIDVALIDITY 1373146075] UIDs valid
         * OK [UIDNEXT 822] Predicted next UID
         ZJzbRA OK [READ-WRITE] Select completed (0.000 + 0.000 secs).

So here we see:

* 101 EXISTS
  * There are 101 messages
* 0 RECENT
  * There are zero "recent" messages
*  OK [UNSEEN 100] First unseen.
   * There is at least one unread message, with UID 100.

However when I print the structure I see this:

        Unseen - Mailbox Automated-attic - Unseen:0 Total:101

So `mbox.Unseen == 0` when I expect it to equal either `1` (count of unread) or `100` (first unread UID).

Am I missing something, or is this a problem?

**Comment by emersion** [comment]
Fields are left empty when not available. `Unseen` is the number of unread messages, `UnseenSeqNum` is the sequence number of the last unread message.

**Comment by skx** [comment]
Thank-you for your prompt reply, that solves my immediate problem.  (Getting a complete list of all available folders, and knowing whether they are all-read or contain new-items.)

I'll close this now :)
