### ISSUE TITLE
Imap server doesn't receive any new mail

### ISSUE THREAD

**Issue by localhosted** [emersion/go-imap#195]
I put the demo server on a digital ocean droplet, on port 143. I can login with Outlook, but I only see that "A little message, just for you" in my inbox.

No matter how many messages I send to my ip, there are none on the inbox. No messages sent receive an error.

**Comment by emersion** [comment]
How do you "send" messages?

**Comment by localhosted** [comment]
I sent them to `username@ipaddress` from both a hotmail.com account and from go-smtp

**Comment by emersion** [comment]
This little example uses an in-memory backend and has completely disconnected from go-smtp. You'll need to create a go-smtp backend that stores messages in a go-imap backend to do that.

**Comment by localhosted** [comment]
I don't quite understand. Isn't an imap server supposed to receive emails? Why do I need a go-smtp backend?



> [Yes. IMAP is for receiving emails.](https://github.com/emersion/go-smtp/issues/5#issuecomment-341152636)

I just want to receive emails on my server, I don't care for sending.
