### ISSUE TITLE
Cant download attachment when mail in charset gb18030.

### ISSUE THREAD

**Issue by jarlyyn** [emersion/go-imap#197]
I got a en error 
"simplifiedchinese: invalid GB18030 encoding"
when a read attachment form nextpart of a email with charset gb18038.

I read all codes and found the problem is the autoconvert of charset in  

https://github.com/emersion/go-message/blob/master/entity.go#L52

The attachment file contians binart data data cant convert form gb18038 to utf 8

I have to disable gb180830 converter by add code 
'charset.RegisterEncoding("gb18030", NopEnc) '

But it seems duty and still have problems with other charsets.

I think there should be a raw data reader or params to disable auto converting.

**Comment by emersion** [comment]
You can just unset `charset` from `Content-Type`. I'm not sure we can do something better. I don't know how other decoders handle charset errors, maybe they just replace them with a UTF-8 invalid rune? In this case, this should be reported to `golang.org/x/text/encoding`.

**Comment by jarlyyn** [comment]
The charset is corrected when parsing email body.

The issus is happend when convert a binary attachment from gb2313 to utf 8.

IMO,attachment will broken even "golang.org/x/text/encoding" package not panic.

I think charset should only be converted in text mode.

**Comment by emersion** [comment]
Can you share the email you're trying to parse?

**Comment by emersion** [comment]
Feel free to re-open if you can reproduce.

**Comment by lysfighting** [comment]
Hello, have you solved this problem? I have encountered the same problem recently. When I open the downloaded "gb18030" encoded file, I am prompted: the file is corrupt.
