### ISSUE TITLE
How would you use Socks5 dialer?

### ISSUE THREAD

**Issue by tegk** [emersion/go-imap#201]
Is there a way implemented to connect via socks5?

**Comment by tegk** [comment]
Please bare with me as I am aware that this question is not directly related to this library but could be useful for other people.

`dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:1080", nil, proxy.Direct)
	if err != nil {
		fmt.Fprintln(os.Stderr, "can't connect to the proxy:", err)
		os.Exit(1)
	}
	// Connect to server
	c, err := client.DialWithDialerTLS(dialer, "imap.server.com:993", nil)
	if err != nil {
		log.Fatal(err)
	}`

`cannot use dialer (type proxy.Dialer) as type *net.Dialer in argument to client.DialWithDialerTLS: need type assertion`

How could I perform in this case the type assertion?

**Comment by emersion** [comment]
Ah. It seems that our function signature is too restrictive. Could you open a pull request that copies the `Dialer` interface from `proxy` into our `client` package, and change `DialWithDialer` and `DialWithDialerTLS` to accept this interface instead of a `*net.Dialer`? Since `*net.Dialer` implements this interface it should not break anything.

**Comment by tegk** [comment]
Upgrading the connection works for me only as the interfaces are not compatible.

```
// DialWithDialerTLS connects to an IMAP server using an encrypted connection
// using proxy.Dialer.
//
func DialWithDialerTLSWithProxy(dialer proxy.Dialer, addr string,
	tlsConfig *tls.Config) (c *Client, err error) {

	conn, err := dialer.Dial("tcp", addr)
	if err != nil {
		return
	}
dialer.Time
	// upgrade to TLS
	conn = tls.Client(conn, tlsConfig)

	c, err = New(conn)
	c.isTLS = true
	return
}
```
Use that like this:
```
// create a socks5 dialer
	dialer, _ := proxy.SOCKS5("tcp", "127.0.0.1:1080", nil, &net.Dialer{
		Timeout:   60 * time.Second,
		KeepAlive: 30 * time.Second,
	})
	
	// Connect to server
	c, _ := client.DialWithDialerTLSWithProxy(dialer, "imap.1und1.de:993", &tls.Config{
		InsecureSkipVerify: true,
	})
```
Could you advice me how to deal with 
```
if dialer.Timeout > 0 {
		err = conn.SetDeadline(time.Now().Add(dialer.Timeout))
		if err != nil {
			return
		}
	}
```

Also InsecureSkipVerify or the Server name has to be passed as config because of the upgrading of the connection.

I am not sure if you would accept such pull request as this might brake your code. 

regards

**Comment by emersion** [comment]
>Could you advice me how to deal with dialer.Timeout

Ah, forgot this one. I'd suggest we check if the `Dialer` is a `*net.Dialer`, if so, we use `dialer.Timeout`.

**Comment by ceo** [comment]
Hello guys, any idea how to use socks5 with go-imap , or how to convert a *proxy.Dialer to a *net.Dialer to use Timeout

**Comment by emersion** [comment]
This issue has ideas for a patch to allow go-imap to use a `*proxy.Dialer`.

**Comment by ceo** [comment]
Yes im using that DialWithDialerTLSWithProxy approach that @tegk commented but i don't know how to set a Timeout there so the connection hangs for like 1 minute when tries to connect to a not working  host .

**Comment by xLivan** [comment]
There is simple workaround for using go-imap with proxy:
```go
dialer, _ := proxy.SOCKS5("tcp", "127.0.0.1:1080", nil, &net.Dialer{Timeout: 5 * time.Second}) // create a socks5 dialer with timeout
conn, _ := dialer.Dial("tcp", "imap.server:993") // connect
conn, _ = tls.Client(conn, &tls.Config{InsecureSkipVerify: true})// use tls
c, _ := client.New(conn) // create imap client
```

**Comment by emersion** [comment]
(Edited your answer to remove `&tls.Config{InsecureSkipVerify: true}` so that people don't copy-paste it blindly)

**Comment by tegk** [comment]
> Yes im using that DialWithDialerTLSWithProxy approach that @tegk commented but i don't know how to set a Timeout there so the connection hangs for like 1 minute when tries to connect to a not working host .
Could you not just edit the value in this part? `Timeout:   60 * time.Second,`

**Comment by FournyP** [comment]
Hello everyone,

I'm currently creating a program to connect to google imap server through a proxy.

I have use the @Livan-pro response to do that but I got this message :
`2021/05/05 19:22:06 socks connect tcp proxyUrl:proxyPort->imap.gmail.com:993: EOF`

In my code, I try to display mail boxes but nothing happen.

Here my code : 
```golang
func findMailConfirmation(googleAccount *ent.GoogleAccount) (*string, error) {

	proxyCredentials := &proxy.Auth{
		User:     "username",
		Password: "password",
	}

	imapConn, err := initImapConnectionWithProxy("proxyUrl:proxyPort", proxyCredentials, googleAccount)

	if err != nil {
		return nil, err
	}

	defer imapConn.Logout()

	mailboxes := make(chan *imap.MailboxInfo, 10)
	done := make(chan error, 1)
	go func() {
		done <- imapConn.List("", "*", mailboxes)
	}()

	log.Println("Mailboxes:")
	for m := range mailboxes {
		log.Println("* " + m.Name)
	}

	return nil, err
}
```

My initImapConnectionWithProxy function : 
```golang
func initImapConnectionWithProxy(address string, proxyCredentials *proxy.Auth, googleAccount *ent.GoogleAccount) (*client.Client, error) {

	dialer, err := initProxyConnection(address, proxyCredentials)

	if err != nil {
		return nil, err
	}

	return initImapConnection(dialer, googleAccount)
}
```

My initProxyConnection function : 
```golang
func initProxyConnection(address string, credentials *proxy.Auth) (proxy.Dialer, error) {

	forward := &net.Dialer{
		Timeout:   60 * time.Second,
		KeepAlive: 30 * time.Second,
	}

	return proxy.SOCKS5(TCP, address, credentials, forward) // create a socks5 dialer with timeout
}
```

My initImapConnectionfunction : 
```golang
func initImapConnection(dialer proxy.Dialer, googleAccount *ent.GoogleAccount) (*client.Client, error) {

	conn, err := dialer.Dial(TCP, GMAIL_IMAP_ADDRESS) // connect

	if err != nil {
		return nil, err
	}

	conn = tls.Client(conn, nil)      // use tls
	imapConn, err := client.New(conn) // create imap client

	if err != nil {
		return nil, err
	}

	if err = imapConn.Login(googleAccount.Username, googleAccount.Password); err != nil {
		return nil, err
	}

	return imapConn, nil
}
```

I have try with a lot of proxy, some of them return this error : 
`2021/05/05 19:25:20 socks connect tcp proxyUrl:proxyPort->imap.gmail.com:993: unexpected protocol version 72`

But I think it is because the proxy didn't support SOCKS5.

I am a beginner in golang so maybe there are some mistakes.

Someone can help me ?

Have a good day and thanks for your work.
