### ISSUE TITLE
MailBoxStatus Parse method - how to use?

### ISSUE THREAD

**Issue by jradxl** [emersion/go-imap#203]
go-imap/mailbox.go
Lines 192 to 220

Please excuse my inexperience, but I don't understand how to use this MailBoxStatus Parse method.
Is it intended as an internal only method?

Could someone give an example of how it should be used?

func (status *MailboxStatus) Parse(fields []interface{}) error {
	status.Items = make(map[StatusItem]interface{})
	var k StatusItem
	for i, f := range fields {
		if i%2 == 0 {
			if kstr, ok := f.(string); !ok {
				return fmt.Errorf("cannot parse mailbox status: key is not a string, but a %T", f)
			} else {
				k = StatusItem(strings.ToUpper(kstr))
			}
		} else {
			status.Items[k] = nil
			var err error
			switch k {
			case StatusMessages:
				status.Messages, err = ParseNumber(f)
			case StatusRecent:
				status.Recent, err = ParseNumber(f)
			case StatusUnseen:
				status.Unseen, err = ParseNumber(f)
			case StatusUidNext:
				status.UidNext, err = ParseNumber(f)
			case StatusUidValidity:
				status.UidValidity, err = ParseNumber(f)
			default:
				status.Items[k] = f
			}
			if err != nil {
				return err
			}
		}
	}
	return nil
}

Thanks

**Comment by tegk** [comment]
Could I ask why you want to use the status.Parse function?
I guess this would work:
```status.Parse([]interface{}{
		"UNSEEN", uint32(6),
		"UIDNEXT", uint32(65536),
		"UIDVALIDITY", uint32(4242),
	})```

**Comment by jradxl** [comment]
Only because I was looking at the example Client code and wondered what else was in mbox.???
Here's my code that runs the Parse method. Seems to require pairs of strings in an array, as the library code contains a ParseNumber(f)
It's purpose seems to be to nil the respective entry in Items, and load the second value of the pair into the respective field. I guess there is some use for it.

	a1 := [...]string{"MESSAGES", "123", "UidNext", "345"}
	a2 := make([]interface{}, len(a1))

	for i, v := range a1 {
		a2[i] = v
	}

	log.Println("Items before Parse:", mbox.Items)
	log.Println("Number of messages before Parse:", mbox.Messages)

	if err := mbox.Parse(a2); err != nil{
		log.Fatal(err)
	}

	log.Println("Items after Parse:", mbox.Items)
	log.Println("Number of messages after Parse:", mbox.Messages)

**Comment by emersion** [comment]
`Parse` is called by the `client` package. It shouldn't need to be used directly.
