### ISSUE TITLE
Gmail login with known username, password and authentication token

### ISSUE THREAD

**Issue by johnwatsonoklahoma** [emersion/go-imap#207]
I try to login to Gmail with given username, password and authentication token (can be viewed in Thunderbird passwords):

	package main

	import (
			"fmt"
			"github.com/emersion/go-imap/client"
			"github.com/emersion/go-sasl"
			"golang.org/x/oauth2"
	)

	func main() {
		username := "" // hey, use your own gmail account
		password := ""
		authToken := "" // you can find it in Thunderbird passwords

		c, err := client.DialTLS("imap.gmail.com:993", nil)
		if err != nil {
			fmt.Println(err)
			return
		}
		defer c.Logout()

		cfg := &oauth2.Config{
		    ClientID:     username,
		    ClientSecret: password,
		    Scopes:       []string{"https://mail.google.com/"},
		    Endpoint: oauth2.Endpoint{
		    	AuthURL:  "https://accounts.google.com/o/oauth2/auth",
		        TokenURL: "https://accounts.google.com/o/oauth2/token",
		    },
		}

		token, err := cfg.Exchange(oauth2.NoContext, authToken)
		if err != nil {
			fmt.Println("Exchange error")
			fmt.Println(err)
			return
		}

		saslClient := sasl.NewXoauth2Client(username, token.authToken)

		err = c.Authenticate(saslClient)
		if err != nil {
			fmt.Println("Authenticate error")
			fmt.Println(err)
			return
		}

	}

After running that code I get following output

    Exchange error
    oauth2: cannot fetch token: 401 Unauthorized
	Response: {
	  "error": "invalid_client",
	  "error_description": "The OAuth client was not found."
	}

How do I make it work?

**Comment by emersion** [comment]
I don't know, but this isn't a go-imap issue.

**Comment by StephanVerbeeck** [comment]
To use OAuth2, you must have registered your application through the Google APIs Console. Registration is explained in Using OAuth 2.0 to Access Google APIs.
-> https://developers.google.com/identity/protocols/oauth2
-> https://console.developers.google.com/cloud-resource-manager
-> https://www.google.com/search?q=golang+oauth2+client+example
