### ISSUE TITLE
XOAUTH2 authentication error (400)

### ISSUE THREAD

**Issue by djeckson** [emersion/go-imap#213]
While trying oauth authorization imap.google.com get this error message:
XOAUTH2 authentication error (400)
```	
        c, err := client.DialTLS("imap.gmail.com:993", nil)
	if err != nil {
		return nil, ErrConnFail
	}
	auth := sasl.NewXoauth2Client(userName, token.AccessToken)
	err = c.Authenticate(auth)
	if err != nil {
		return nil, ErrAuthFail
	}
	return c, nil
```
the user name and token is correct
error is thrown in the Authenticate method.
What could be the problem?

**Comment by djeckson** [comment]
The problem was with Scopes. Needed full access to mail, I had read only

**Comment by emersion** [comment]
Makes sense
