### ISSUE TITLE
how to manually mark mail as "unseen"?

### ISSUE THREAD

**Issue by Richardhzj** [emersion/go-imap#214]
I found a way to receive 'unseen' mail from your wiki. However, if I failed to do some operation after getting the mail and want to mark this mail as 'unseen' again in order to retry it next time. What should I do?

Is there a way to set the flag back to 'unseen'?
`_, err = c.Select("INBOX", false)
	if err != nil {
		log.Error(err)
		return
	}

	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := c.Search(criteria)
	if err != nil {
		log.Error(err)
		return
	}
	// log.Info("IDs found:", ids)
	seqSet := new(imap.SeqSet)
	for _, v := range ids {
        // read each mail
        }`

**Comment by Richardhzj** [comment]
I found the store method should work for this. But i don't know how to implement this method. Could you give me a example?   
`criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := c.Search(criteria)
	if err != nil {
		log.Error(err)
		return
	}
	// log.Info("IDs found:", ids)
	seqSet := new(imap.SeqSet)

	for _, v := range ids {
		seqSet.AddNum(v)
		messages := make(chan *imap.Message, 1)
                c.store(seqset *imap.SeqSet, item imap.StoreItem, value interface{}, ch chan *imap.Message) 
                // how to implement this store method to set the flag to "unseen"?
              }`

**Comment by djeckson** [comment]
You need to remove Seen flag

```
        _, err := client.Select(mailbox, false)
	if err != nil {
		return err
	}
	item := imap.FormatFlagsOp(imap.RemoveFlags, true)
        seenFlag:=[]interface{}{imapEmersion.SeenFlag}
	err = client.Store(seqSet, item, seenFlag, nil)```

**Comment by Richardhzj** [comment]
Thanks man, that works!

**Comment by emersion** [comment]
@djeckson Thanks!
