### ISSUE TITLE
Receiving individual attachments

### ISSUE THREAD

**Issue by djeckson** [emersion/go-imap#215]
1. When using fetch with" FetchBodyStructure " how to get the attachments list. 
2. How to get a separate attachment through "FETCH BODY.PEEK[1]"

**Comment by emersion** [comment]
>When using fetch with" FetchBodyStructure " how to get the attachments list.

You need to walk the body structure and look for parts having disposition set to "attachment". Some clients don't set this, so you'll probably want to assume the first `text/*` or `multipart/alternative` part is the body and all others are attachments. Some clients (e.g. Apple Mail) allow doing more complex stuff, with multiple inline parts.

>How to get a separate attachment through "FETCH BODY.PEEK[1]"

Once you know which part (aka. attachment) you're interested in, you need to get the path to it (e.g. `1.4.2`). Then you can fetch it with `FETCH BODY.PEEK[1.4.2]`. go-imap has a few functions to help formatting this string (`BodySectionName`, `FetchItem`).

**Comment by djeckson** [comment]
> You need to walk the body structure and look for parts having disposition set to "attachment". Some clients don't set this, so you'll probably want to assume the first `text/*` or `multipart/alternative` part is the body and all others are attachments. Some clients (e.g. Apple Mail) allow doing more complex stuff, with multiple inline parts.

If I set "FetchBodyStructure" FetchItem,  body empty

**Comment by emersion** [comment]
The body structure is different from the body itself. If you want to retrieve the body structure, it'll be put in `Message.BodyStructure`.
