### ISSUE TITLE
WINDOWS-1251 encoding

### ISSUE THREAD

**Issue by sergeymild** [emersion/go-imap#217]
Hello, i have string like this:
=?WINDOWS-1251?B?1+XqIO7hIO7v6+Dy5SDz8evz4yDEzswuUlU=?=
it's a subject in message, and it's a russia.
And it's doesn't parsed to russia word, it's remains the same

**Comment by emersion** [comment]
You'll need to read this: https://github.com/emersion/go-imap/wiki/Charset-handling
