### ISSUE TITLE
multipart header FROM for the search criteria does not found any emails

### ISSUE THREAD

**Issue by DeadNumbers** [emersion/go-imap#218]
When set more then one `From` header
```Go
       server := "imap.gmail.com:993"
       ...
	criteria := imap.NewSearchCriteria()
	criteria.Header.Add("From", "facebook")
	criteria.Header.Add("From", "twitter")
```
`client.Search(criteria)` return `0` ids. But if set just one `criteria.Header.Add("From", "twitter")` works good. What I do wrong?

![default](https://user-images.githubusercontent.com/9416005/52557027-2485fe80-2de6-11e9-9062-b61c49b00b4c.png)

**Comment by emersion** [comment]
According to the RFC:

>When multiple keys are specified, the result is the intersection (AND function) of all the messages that match those keys. 

You need to create two criteria, and wrap them in a OR clause.

**Comment by DeadNumbers** [comment]
Oh, thanx!
![default](https://user-images.githubusercontent.com/9416005/52562844-b9ddbe80-2df7-11e9-8d81-f28e96404d26.png)
