### ISSUE TITLE
Shouldn't flags matching be case-insensitive 

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-imap#224]
At least dovecot seems to do case-insensitive search for flags:
```
D0 FETCH 1 FLAGS
* 1 FETCH (FLAGS (\Seen $TEST1))
D0 OK Fetch completed (0.001 + 0.000 secs).
D1 SEARCH KEYWORD $TeSt1
* SEARCH 1
D1 OK Search completed (0.001 + 0.000 secs).
```
But backendutil.MatchFlags does case-insensitive match now.

**Comment by emersion** [comment]
We're canonicalizing flags when we receive them from the client: https://godoc.org/github.com/emersion/go-imap#CanonicalFlag

Nothing in the RFC says to perform case-insensitive matching IIRC. Or am I missing somehting?

**Comment by foxcpp** [comment]
Ah, right. Got in bad habit of testing backend methods directly thus ignoring all go-imap logic except backendutil.
