### ISSUE TITLE
Make parsing/formatting functions internal

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#226]
But then how to handle extensions?

**Comment by foxcpp** [comment]
>But then how to handle extensions?

Then we can't get [third-party extensions implementation](https://github.com/foxcpp/go-sqlmail/tree/dev/imap/children) because they often need to parse custom commands.

So I don't think it's a good idea.

**Comment by emersion** [comment]
Yeah, I agree. Maybe the functions could be in a different package (e.g. `github.com/emersion/go-imap/wire`?).

**Comment by emersion** [comment]
This is for the future anyway. I'd like to ship v1 sooner rather than later.

**Comment by emersion** [comment]
Done in v2.
