### ISSUE TITLE
unable to build without modules

### ISSUE THREAD

**Issue by Almaz1c** [emersion/go-imap#236]
hi!
Starting from some moment I can't build docker image with this package.
github.com/emersion/go-imap/backend/backendutil
src/github.com/emersion/go-imap/backend/backendutil/search.go:80:25: invalid operation: e.Header[key] (type message.Header does not support indexing)
Can you explain howw to fix this please?

**Comment by emersion** [comment]
Hmm. I think you're trying to build without Go modules. This uses the latest go-message, and fails because there are some breaking changes.

**Comment by sPooKee** [comment]
I get the same error here on a clean GOPATH:

```shell
$ ~> go get github.com/emersion/go-imap/...
# github.com/emersion/go-imap/backend/backendutil
go/src/github.com/emersion/go-imap/backend/backendutil/body.go:46:16: cannot make type message.Header
go/src/github.com/emersion/go-imap/backend/backendutil/body.go:47:15: cannot range over e.Header (type message.Header)
go/src/github.com/emersion/go-imap/backend/backendutil/body.go:61:24: cannot range over header (type message.Header)
go/src/github.com/emersion/go-imap/backend/backendutil/search.go:80:25: invalid operation: e.Header[key] (type message.Header does not support indexing)
```

**Comment by foxcpp** [comment]
You are definitely not using Go Modules, go-imap project uses it and requires modules-compatible toolchain to build.

1. Make sure you have Go 1.11 or newer. There is no modules support in earlier versions.
2. Make sure you are opting into modules. They are opt-in now and go-imap will fail to build if project you are trying to use it with lacks `go.mod` file in the root. Run `go mod init` in the project (repository) root.
2. If you are building inside GOPATH - modules support is disabled. You can force it by setting `GO111MODULE` environment variable to `on` or just build outside of GOPATH.
3. If you are unable to use modules for some reason (tooling incompatibility, unable to update Go toolchain for some reason), you have to resort to vendoring or version manager like [dep].

For vendoring - run `go mod init`, `go mod tidy` and then `go mod vendor` with modules-compatible toolchain. It will download the right version of packages to the `vendor/` directory.

Further reading: https://github.com/golang/go/wiki/Modules

@emersion, I would lock this issue, change the title to "unable to build without modules" and add the wontfix label.

[dep]: https://github.com/golang/dep

**Comment by foxcpp** [comment]
go-imap can't be built without Go modules support. If you weird compilation errors - make sure you are using Go modules. If go-imap still doesn't compiles - open the new issue.
