### ISSUE TITLE
Format fields as a string not exported

### ISSUE THREAD

**Issue by kompiuter** [emersion/go-imap#239]
Using the [*SearchCriteria.Format()](https://github.com/emersion/go-imap/blob/b7db4a2bc5cc04fb568fb036a438da43ee9a9f78/search.go#L275) method, we can go from a `*SearchCriteria` to an array of fields. However there is no way to go from the array of fields to a properly formatted search string.

This functionality is already implemented in `message_test.go`, in the [formatFields(...)](https://github.com/emersion/go-imap/blob/b7db4a2bc5cc04fb568fb036a438da43ee9a9f78/message_test.go#L36) method.

Is there any reason this isn't provided as an exported function?

**Comment by emersion** [comment]
Why do you need it?

**Comment by kompiuter** [comment]
I have a case where I need to take in a raw IMAP search string, parse it into a struct, alter it, and then return it formatted as a string.

**Comment by emersion** [comment]
I'd suggest using `imap.Reader` and `imap.Writer`.

**Comment by kompiuter** [comment]
@emersion All methods of `imap.Writer` are not exported, how do you suggest using it?

**Comment by emersion** [comment]
Hmm. Commands and responses use `imap.WriterTo`.
