### ISSUE TITLE
Quote everything that needs to be quoted

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#242]
We try to be smart with quoting and it doesn't work well.

We need to read the ABNF and make sure atoms aren't quoted and quoted strings are correctly quoted.

**Comment by foxcpp** [comment]
Relevant ABNF definitions for strings.

#### Nullable string
```
nil             = "NIL"
nstring         = string / nil
```
#### String
```
string          = quoted / literal
```

#### Quoted string
```
quoted          = DQUOTE *QUOTED-CHAR DQUOTE

QUOTED-CHAR     = <any TEXT-CHAR except quoted-specials> /
                  "\" quoted-specials

quoted-specials = DQUOTE / "\"
```

#### Literal
```
literal         = "{" number "}" CRLF *CHAR8
                    ; Number represents the number of CHAR8s
```

**Comment by emersion** [comment]
Code-wise, I think it would be nice to replace `imap.Quoted` with `string`, and to force users to explicitly use `imap.Atom` when something needs not to be quoted.

**Comment by foxcpp** [comment]
> and to force users to explicitly use imap.Atom when something needs not to be quoted.

Probably it is a good idea to rename it because many protocol contructs are not considered "atoms" but still don't need to be quoted, commands for example. `imap.RawString`, perhaps?

**Comment by emersion** [comment]
Works for me

**Comment by foxcpp** [comment]
What should be done with astrings? Always quote?

**Comment by emersion** [comment]
Yes. I'm not really worried about wasting 2 bytes :P
