### ISSUE TITLE
Check literal length

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#247]
Right now when writing a literal we blindly `io.Copy` the `io.Reader`. We should make sure the `io.Reader` contains exactly `Len` bytes.

**Comment by foxcpp** [comment]
What should be done if io.Reader doesn't contain Len bytes? We already wrote some bytes to the connection, so probably we can only pad it with more bytes to make sure it will contain Len bytes.

**Comment by emersion** [comment]
I don't think padding would be reasonable. Also doesn't work if the `io.Reader` yields more bytes than advertised.

We should just error out and close the connection.
