### ISSUE TITLE
Consider preallocating

### ISSUE THREAD

**Issue by tegk** [emersion/go-imap#276]
Preallocating is much faster usually :-)
```
search.go:276:2: Consider preallocating `fields` 
	var fields []interface{}
```
	
```
backend/memory/mailbox.go:55:2: Consider preallocating `flags` 
	var flags []string
```
	
```
backend/memory/mailbox.go:142:2: Consider preallocating `ids` 
	var ids []uint32
```
	
```
message.go:89:2: Consider preallocating `fields` 
	var fields []interface{}
```
	
```
mailbox.go:232:2: Consider preallocating `fields` 
	var fields []interface{}
	
```

**Comment by foxcpp** [comment]
Consider reading the source code before yelling about it. In many cases computing the right slice size will add a lot of obscure code and just picking "the biggest possible" will waste a lot of memory. I don't think it's worth it. Do you have performance issues with it?
