### ISSUE TITLE
maligned struct

### ISSUE THREAD

**Issue by tegk** [emersion/go-imap#278]
We could save here some bytes :-)
Read more:
https://medium.com/@felipedutratine/how-to-organize-the-go-struct-in-order-to-save-memory-c78afcf59ec2
```
backend/memory/message.go:15:14: struct of size 88 bytes could be of size 80 bytes 
type Message struct {
          
```
```
server/server.go:91:13: struct of size 168 bytes could be of size 160 bytes 
type Server struct {
            
```
```
read.go:135:13: struct of size 48 bytes could be of size 40 bytes 
type Reader struct {
```
            
```
client/client.go:65:13: struct of size 152 bytes could be of size 144 bytes 
type Client struct {


```

**Comment by foxcpp** [comment]
If memory usage is that critical that you need to save these __few__ bytes  - you might want to consider not using go-imap or Go altogether. 

Anyway, feel free to submit a PR and we will merge it if it doesn't hurt readability.

**Comment by emersion** [comment]
I prefer to keep structs with a logical order for fields (e.g. grouped fields).

**Comment by tegk** [comment]
> I prefer to keep structs with a logical order for fields (e.g. grouped fields).

This is a good example why I opened the issues. Its worth discussing if it was intended or not. I do not understand why @foxcpp and @emersion are so emotional about it.
