### ISSUE TITLE
backendutil: FetchEnvelope doen't decode headers too

### ISSUE THREAD

**Issue by cnt0** [emersion/go-imap#279]
`FetchEnvelope` uses `headerAddressList` to parse address lists.  
`headerAddressList` tries to use `ParseAddressList` from `net/mail`, but this function knows almost nothing about charsets. So in cases like this one

```From: =?ISO-8859-15?B?TWl0c3VoYSBNaXlhbWl6dQ==?= <mitsuha.miyamizu@example.org>```

the result is just an empty slice, and there's no way to recover the information

**Comment by emersion** [comment]
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.
