### ISSUE TITLE
Not detecting an attachment

### ISSUE THREAD

**Issue by vadimyer** [emersion/go-imap#282]
Some of the emails we receive got a header like:

```
Content-Disposition: inline; filename=file.txt
```

This is not being detected by the pkg as an attachment. Can we fix it somehow the right way?

**Comment by emersion** [comment]
Actually this isn't an attachment. It's supposed to be displayed in the message body.

**Comment by vadimyer** [comment]
Well in Gmail UI it's being displayed as an attachment as well.

**Comment by emersion** [comment]
"inline" means it's not meant to be displayed as an attachment. GMail's not taking into account the intent of the sender here.
