### ISSUE TITLE
Search string with apostrophe not working

### ISSUE THREAD

**Issue by dgrr** [emersion/go-imap#290]
Hello,

I am trying to fetch emails with single quote in the [SearchCriteria.Text](https://godoc.org/github.com/emersion/go-imap#SearchCriteria.Text) field. I tried by formatting the field like `"Bob\'s email"` but isn't working.

Any idea?
Thanks

**Comment by emersion** [comment]
Can you try `"Bob's email"`?

**Comment by dgrr** [comment]
No, that doesn't work

**Comment by dgrr** [comment]
That's weird. If I try looking for an email with the subject `Nat'l whatever` is successfully found.
Seems there's a problem only with `'s`.

**Comment by dgrr** [comment]
Looks like it's Google's IMAP error.
