### ISSUE TITLE
Use TCP keepalive

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#291]
See https://golang.org/pkg/net/#TCPConn.SetKeepAlive

**Comment by foxcpp** [comment]
net.Dial sets TCP keep-alive to 15 seconds by default. Though undocumented, the same value is [used](https://golang.org/src/net/tcpsock_posix.go#L148) for connections created using net.Listener.Accept. Do we need a different interval?

**Comment by emersion** [comment]
Right, this is probably enough.
