### ISSUE TITLE
网易邮箱，使用fetch方法接收后，所有未读的邮件全部被标为了已读

### ISSUE THREAD

**Issue by killer99999** [emersion/go-imap#292]
目前测试只有网易的邮箱有这个问题，qq邮箱是没有问题的，请问怎么可以解决这个问题，非常感谢。

**Comment by emersion** [comment]
Sorry, I don't speak Chinese.

**Comment by delthas** [comment]
Netease mailbox, after receiving using fetch method, all unread messages are marked as read

At present, only NetEase's mailbox has this problem, qq mailbox is no problem, how can I solve this problem, thank you very much.

**Comment by emersion** [comment]
You need to specify `Peek = true` in https://godoc.org/github.com/emersion/go-imap#BodySectionName

**Comment by killer99999** [comment]
@emersion 3q

**Comment by delthas** [comment]
(3q means "thank you")
