### ISSUE TITLE
Netease mailbox, after receiving using fetch method, all unread messages are marked as read

### ISSUE THREAD

**Issue by killer99999** [emersion/go-imap#293]
Hi,  At present, only NetEase's mailbox has this problem, qq mailbox is no problem, how can I solve this problem, thank you very much.

**Comment by emersion** [comment]
You need to specify Peek = true in https://godoc.org/github.com/emersion/go-imap#BodySectionName

**Comment by killer99999** [comment]
@emersion  3q very mush

**Comment by killer99999** [comment]
@emersion and then ,how to get the seen or unseen flag? 3q

**Comment by emersion** [comment]
`imap.FetchFlags`

**Comment by killer99999** [comment]
@emersion Hi, when I read the "Address" from qq mail, that return the Name like this "=?gb18030?B?sfk=?="  ,how can I resolve this problem .  the Subject and content  is Ok
thank you

**Comment by killer99999** [comment]
@emersion I had found the method 。3q
