### ISSUE TITLE
Use Store with UID instead of SeqNum

### ISSUE THREAD

**Issue by clement-agflow** [emersion/go-imap#294]
I am trying to add `DeletedFlag` to some specific email in order archive them using Expunge. 

To do so I am using `Client.Store` and pass to it an `imap.SeqSet` with `SeqNum` of the messages I want to archive. The problem is that the `SeqNum` for an email can change in some cases.

How can I use `UID` instead of the `SeqNum` to make sure that the right emails are archived?

**Comment by emersion** [comment]
Use `Client.UidStore`
