### ISSUE TITLE
Parse an email attachment 

### ISSUE THREAD

**Issue by S0larflare** [emersion/go-imap#297]
Hi,

I'm currently trying work through a mailbox and parse both the emails and their attachments (when they contain emails as attachments themselves). I'm struggling to get this to work consistently/properly. I'm basically trying to hack something together to try to get the attachment to be parsed as an email - is there anything built in to handle this or should I try carrying on with my weird hacks?

I'm essentially matching regex to find out what the attachment is and then trying to create another mail reader or something similar on the attachment body , which naturally doesn't work...

**Comment by emersion** [comment]
See https://github.com/emersion/go-imap/wiki/Fetching-messages
