### ISSUE TITLE
Connecting to IMAP server as a client from localhost

### ISSUE THREAD

**Issue by GildedHonour** [emersion/go-imap#305]
I run Postfix server. At localhost on my server there's no need to authenticate by providing login and password. And I have multiple mailboxes or users as well. 

I want to check INBOX for user1 and user2.

How will the code in the section "client" change then in regards to "there's no need to authenticate by providing login and password"? 

How to choose INBOX for user1 and user2?

**Comment by emersion** [comment]
>I run Postfix server

Postfix is an SMTP server, not an IMAP server.

If you need to connect to an authentication-less server, you'll probably need to use the ANONYMOUS SASL mechanism. I'm not aware of another way.

**Comment by GildedHonour** [comment]
Postfix+Dovecot

**Comment by foxcpp** [comment]
Assuming you are using anonymous sasl, the function you are looking for is https://godoc.org/github.com/emersion/go-imap/client#Client.Authenticate, you need to use it with https://godoc.org/github.com/emersion/go-sasl#NewAnonymousClient

**Comment by emersion** [comment]
Closing per https://github.com/emersion/go-imap/pull/429
