### ISSUE TITLE
Getting raw message

### ISSUE THREAD

**Issue by daletake** [emersion/go-imap#306]
Hi, I need to get the full raw message. 
This is to verify the sender DKIM (I'm using your library https://github.com/emersion/go-msgauth)
I could get all Header keys, but I have problems with body message.
These are some issues I faced:
* multipartReader struct/interface doesn't publish boundary's part
* multipartReader struct/interface doesn't publish header's parts (eg Content-Transfer:-Encoding, Content-Type)
* text was changed (spaces & encoding)
Remember that, I need exactly the raw message to validate It was not changed.
Thanks !!!

**Comment by foxcpp** [comment]
To get raw message, you should use Fetch with "BODY.PEEK[]" fetch item. This will give you io.Reader with complete message contents as presented by server.

Something like that:
```go
ch := make(chan *imap.Message, 1)
err := c.Fetch(yourSeqset, []imap.FetchItem{imap.FetchItem("BODY.PEEK[]")}, ch)
if err != nil {
  ...
}
msg := <-ch
for name, literal := range msg.Body {
  // literal is the io.Reader you want
}
```

Side note: MUAs are not expected to verify DKIM signatures. Instead you probably should be looking for Authentication-Results header added by an MTA.

**Comment by hmuschett** [comment]
hello I'm trying to do some like that, this is my code 
`	messages := make(chan *imap.Message, 10)
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []imap.FetchItem{imap.FetchBody, imap.FetchEnvelope, imap.FetchBodyStructure, imap.FetchFull}, messages)
	}()
	
	log.Println("Last 4 messages:")
	for msg := range messages {
		log.Println("* " + msg.Envelope.Subject)
		log.Println("* " + msg.Envelope.Date.Format("2006-01-02"))

		log.Println("* " + msg.InternalDate.Format("2006-01-02"))
		log.Println("* " + fmt.Sprint(msg.Size))

		log.Println("* " + msg.BodyStructure.Encoding)
		log.Println("* " + fmt.Sprint(msg.BodyStructure.Lines))

		if len(msg.Body) == 0 {
			log.Println("> not body info")
		}
		for _, value := range msg.Body {
			log.Println("> " + fmt.Sprintf("%v", value.Len()))
		}

	}`

I can see the  msg.Envelope.Subject,  msg.Envelope.Date,  msg.InternalDate, msg.Size, but I need to read the body mail then when I print some from msg.Body and msg.BodyStructure they are empty

**Comment by foxcpp** [comment]
Actual fetch item for message body would be BODY.PEEK[]. FetchBody is a variant of FetchBodyStructure, FetchFull is alias for several other fields but does not include message body either.

**Comment by emersion** [comment]
Closing per https://github.com/emersion/go-imap/pull/429

**Comment by simarmannsingh** [comment]
> To get raw message, you should use Fetch with "BODY.PEEK[]" fetch item. This will give you io.Reader with complete message contents as presented by server.
> 
> Something like that:
> 
> ```go
> ch := make(chan *imap.Message, 1)
> err := c.Fetch(yourSeqset, []imap.FetchItem{imap.FetchItem("BODY.PEEK[]")}, ch)
> if err != nil {
>   ...
> }
> msg := <-ch
> for name, literal := range msg.Body {
>   // literal is the io.Reader you want
> }
> ```
> 
> Side note: MUAs are not expected to verify DKIM signatures. Instead you probably should be looking for Authentication-Results header added by an MTA.

Just curious if this is already part of documentation? If not, would it be useful to add it to the docs, I guess go noobies like me would be really grateful. 😄
