### ISSUE TITLE
Get the UID of the current message in a range

### ISSUE THREAD

**Issue by S0larflare** [emersion/go-imap#307]
So I am getting the whole mailbox and trying to parse through the emails. The intention is to do a bit of work on the emails/their attachments and then move them to a different folder when I'm done. With that in mind I wanted to do a Uidmove, however, for that I need the UID of the mail that is being processed. I'd thought this would be part of the normal Fetch() as the message struct contains a Uid field, but it comes back as 0 every time in my code:

`        

        seqset := new(imap.SeqSet)
        seqset.AddRange(1, mbox.Messages)
        section := &imap.BodySectionName{}
        items := []imap.FetchItem{section.FetchItem()}

        messages := make(chan *imap.Message, mbox.Messages)

        go func() {
                if err := c.Fetch(seqset, items, messages); err != nil {
                        log.Fatal(err)
                }
        }()
        msg := <-messages
        if msg == nil {
                log.Fatal("Server didn't return a message")
        }

        for msg := range messages {
                log.Println("UID: ",msg.Uid)
       }
`

msg.Uid here returns 0 for every message. Can I extend the Fetch to include the UID from the server so i can reference it later?

**Comment by foxcpp** [comment]
`items` should include `imap.FetchUid`.

**Comment by S0larflare** [comment]
Thank you. I could have sworn I had tried that...Anyway, that worked as intended.

One problem though is that I misread the intention behind UidMove it would seem. I thought it would move a message based upon it's Uid, but there's nowhere to pass the Uid through to it. Is there a way to move a message by it's Uid, or if not, is there a 'best way' to move the 'current' message while iterating through the range of a whole mailbox?

**Comment by foxcpp** [comment]
You understood it right,. UidMove moves messages based on the specified UIDs set.

>UidMove is identical to Move, but seqset is interpreted as containing unique identifiers instead of message sequence numbers.

Here is the documentation for this function. I think you got confused by the fact that set of UIDs is specified in the same way as sequence numbers for regular Move.
So, basically, put your UIDs into seqset argument.

**Comment by foxcpp** [comment]
By the way, if you intend to handle a large amount of messages, it might be useful to consider one recommendation from [RFC 2683](https://tools.ietf.org/html/rfc2683). It is a good idea to merge separate ids in seqset into ranges when possible. That it, specify 1-5 instead of 1,2,3,4,5. This saves server resources since it can implement operations on ranges more efficiently. Also you are saving yourself from hitting the command length limit this way.

**Comment by emersion** [comment]
>It is a good idea to merge separate ids in seqset into ranges when possible.

`imap.SeqSet` already has some logic to do this. I don't remember how complete/efficient it is.

**Comment by S0larflare** [comment]
Sorry, still struggling with this one...

So if I do something like this:


```
for i := 0; i <= int(mbox.Messages); i++ {
                        seqSet := new(imap.SeqSet)
                        seqSet.AddNum(mbox.Messages - uint32(i))
/* Grab the message and do stuff  */
                        err = c.Move(seqSet, "INBOX/Processed")
                        if err != nil {
                                    log.Fatal(err)
                         }
} 
```


Then that would move the message, but it seemed like a massive hack, which is why I wanted to redo it as above.  So with my original code, passing seqset doesn't move the message (well, it tries to move the entire range, so would eventually move them, but I want to move to different folders if there is an error etc, I don't want them moving as a block). If I create a new seqset and either try to reference the current sequence number or reference the Uid of the message then nothing moves.

Like I said I think I've misunderstood how it is meant to work, but I can't work out how I can pass msg.Uid and have it work as intended for that specific message as the Uids I get are massively out of range of the original seqset. Ideally I'd want to do something along the lines of:


```
    seqset := new(imap.SeqSet)
    seqset.AddRange(1, mbox.Messages)
    section := &imap.BodySectionName{}
    items := []imap.FetchItem{section.FetchItem()}

    messages := make(chan *imap.Message, mbox.Messages)

    go func() {
            if err := c.Fetch(seqset, items, messages); err != nil {
                    log.Fatal(err)
            }
    }()
    msg := <-messages
    if msg == nil {
            log.Fatal("Server didn't return a message")
    }

    for msg := range messages {
            log.Println("UID: ",msg.Uid)
/* read and process the email */
            tempSeqset :=  new(imap.SeqSet)
            tempSeqset .AddNum(msg.Uid)
            err = c.Move(tempSeqset , "INBOX/Processed")
            if err != nil {
                   log.Fatal(err)
             }
   }
```

**Comment by foxcpp** [comment]
In the second example, just replace Move with UidMove. UIDs and sequence numbers are not related besides ordering (a message with bigger seqnum will have a bigger UID and vice versa)

**Comment by S0larflare** [comment]
Again, I'm sure I had tried that, but regardless you're completely right and that works. Thank you very much for your help :+1:
