### ISSUE TITLE
Error in IMAP command FETCH: Invalid arguments

### ISSUE THREAD

**Issue by crackhd** [emersion/go-imap#309]
I am trying to download emails using [Fetching messages](https://github.com/emersion/go-imap/wiki/Fetching-messages) tutorial code.

I am getting an error:

**Error in IMAP command FETCH: Invalid arguments**

My code is:

```

        // c *imap.Client
        // mbox - mailbox INBOX

	seqSet := new(imap.SeqSet)
	seqSet.AddNum(mbox.Messages)

	var section = &imap.BodySectionName{}

  items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate, section.FetchItem()}

  messages := make(chan *imap.Message)

  go func() {
    time.Sleep(time.Second * 5)
    for {
      msg := <- messages
      if msg == nil {
        log.Error().Msg("Server didn't returned message") // happens
        continue
      }

    	r := msg.GetBody(section)
    	if r == nil {
    		log.Error().Msg("Server didn't returned message body")
               continue
    	}

        // ....

    }()

   err := c.Fetch(seqSet, items, messages)

   // ...

```

**Comment by foxcpp** [comment]
Can you try the following?
```go
items := []imap.FetchItem{imap.FetchItem("BODY.PEEK[]")}
```

**Comment by crackhd** [comment]
Oh, I solved it after an hour of attempts.
The problem was that I've removed the check of a number of messages in the mailbox.

```
  if mbox.Messages == 0 {
		log.Fatal().Msg("No message in mailbox")
	}
	seqSet := new(imap.SeqSet)
	seqSet.AddNum(mbox.Messages)

  criteria := imap.NewSearchCriteria()
  criteria.WithoutFlags = []string{"\\Seen"}
  uids, err := c.Search(criteria)
  if err != nil {
      return err
  }

  if len(uids) == 0 {
    log.Error().Msg("no unread messages")
    return nil
  }

```

I really appreciate the reply. Thanks.

**Comment by foxcpp** [comment]
@emersion, perhaps something needs to be done to provide a more useful error message in this case.

**Comment by crackhd** [comment]
Absolutely correct, mistyped. Fixed this.

**Comment by crackhd** [comment]
> > `log.Error().Msg("Server didn't returned message") // happens`
> 
> This means the channel has been close. You should `break` instead of `continue`, otherwise you're entering a busy loop.
> 
> > perhaps something needs to be done to provide a more useful error message in this case
> 
> So this happens when the `SeqSet` is empty? Or am I misunderstanding?

Yes
