### ISSUE TITLE
Add BodyStructure.Walk

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#319]
Add `BodyStructure.Walk(fn func(path []int, bs *BodyStructure) (walkChildren bool))` to easily iterate over all parts. The return value decides whether to skip the part.

**Comment by foxcpp** [comment]
It might also be useful to have the ability to stop iteration early. Check how path/filepath.Walk implements this.

**Comment by emersion** [comment]
`path/filepath.Walk`'s implementation is a bit subtle, since `ErrSkip` has a different behaviour when the current file is a directory (don't visit children) and when it's not (don't visit siblings). To completely stop iteration, the only way is a custom error it seems.

I considered using an `error` return value but decided against since `BodyStructure.Walk` itself can't fail internally (that's not the case of `path/filepath.Walk` which can fail because of i/o errors). I'm not sure stopping the iteration completely is necessary as I don't think IMAP messages will ever have more than a few parts.
