### ISSUE TITLE
I got a error, message is unhandled charset "gb2312"

### ISSUE THREAD

**Issue by anxin1225** [emersion/go-imap#320]
I find page  https://github.com/emersion/go-message/blob/master/charset/charset.go in local go file. Some one of all email are ok. 
I think those not worked email was encode by GB2312, those worked was utf-8, what shoud I do?

**Comment by foxcpp** [comment]
GB2312 encoding should work fine. Can you provide more information? (e.g. at least exact errors you are getting).

**Comment by anxin1225** [comment]
I am not found encoding, in the error message header. the message content-type was multipart/alternative; boundary="----=_001_NextPart238177150474_=----".   It is not contain encoding info.

**Comment by anxin1225** [comment]
the encoding was in the subject string. look like this "=?GB2312?B?1+K7pzEwOTQ5N6GwurzW3eW3t6u159fTyczO8dPQz97U8MjOuavLvqGxx9C7u9fu0MK2pLakttS907e9yr0=?="

**Comment by anxin1225** [comment]
by the way, the error was return, when I call mail.CreateReader(msg.GetBody(section)).Header.Subject().

**Comment by anxin1225** [comment]
I think it shoud be, the encoding was not in content-type. then we do not know the message encode. 
message's subject was encode by GB2312, but we do not hanlde encode was in string, then I got this error, when I Call Subject().

**Comment by anxin1225** [comment]
WOW，I got it. 
message.CharsetReader is nil. it can not hanlde gb2312.  
then I add those code in init method
`message.CharsetReader = func(encoding string, input io.Reader) (reader io.Reader, e error) {
    return charset.Reader(encoding, input)
}`
and it worked

**Comment by anxin1225** [comment]
but, I am not sure it is the true way.

**Comment by emersion** [comment]
See https://github.com/emersion/go-imap/wiki/Charset-handling

**Comment by anxin1225** [comment]
Wow, I got it. thank all of you

**Comment by pdxrlj** [comment]
not found  this link  https://github.com/emersion/go-imap/wiki/Charset-handling
