### ISSUE TITLE
Flags are converted to RawString without any check

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#326]
If the user calls `Client.Append` with flags containing invalid chars (e.g. a space), go-imap will send garbage to the server. We should check such user-provided strings.

Maybe we can introduce a function like `func FormatRawString(s string) (RawString, error)`.

**Comment by Adirelle** [comment]
Note that the keyword flags are a special case, which may require a different validation than quoted strings.

**Comment by emersion** [comment]
Fixed in v2.
