### ISSUE TITLE
Library cannot handle NIL hierarchy delimiter

### ISSUE THREAD

**Issue by houlahaj** [emersion/go-imap#329]
Trying to do `LIST` against an IMAP server that uses a flat structure (NIL hierarchy delimiter) will fail with error `Mailbox delimiter must be a string`.

This is because the parsing of the IMAP response detects a `NIL` atom (at `read.go:220`) and puts a nil interface there in the response fields; this nil interface later fails a type assertion to string (`responses/list.go:35` -> `mailbox.go:63`), and the library rejects this because it enforces that all mailboxes require valid hierarchy delimiters.

However, RFC3501 says a `NIL` hierarchy delimiter is valid and should be used to indicate a flat hierarchy (see [RFC3501#7.2.2](https://tools.ietf.org/html/rfc3501#section-7.2.2))

An example of a significant mail server that reports a `NIL` delimiter is seznam.cz.

A quick fix (though i'm not sure about further sideeffects at this point) is to change `mailbox.go:63` to be like
```go
if info.Delimiter, ok = fields[1].(string); fields[1] != nil && !ok {
    return errors.New("Mailbox delimiter must be a string")
}
```

**Comment by emersion** [comment]
Indeed! I think `Format` and `Match` need to be fixed as well.
