### ISSUE TITLE
Add Mailbox.Close

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-imap#337]
I am working on the maildir-based backend that uses BoltDB for caches and metadata.
BoltDB DB is created per mailbox. backend.Mailbox implementation opens it on demand, but it also needs to close it at some point. Currently Close() is missing for Mailbox so I cannot do it.

Proposal: If Mailbox implements io.Closer, call Close() after use. Not sure about ListMailboxes.

**Comment by emersion** [comment]
Since BoltDB only supports one consumer at a time, you'll want to refcount mailboxes.

Maybe go-imap v2 should make ListMailboxes return a []MailboxInfo instead of a []Mailbox.

**Comment by foxcpp** [comment]
For v1 I think Close should be called for mailboxes returned by ListMailboxes too.

**Comment by emersion** [comment]
Fixed in go-imap v2.
