### ISSUE TITLE
Same Day Search Criteria

### ISSUE THREAD

**Issue by NoelHG** [emersion/go-imap#344]
I have a time.Time of the last email I looked at `lastEmail`

I want to do something like:
```
	criteria := imap.NewSearchCriteria()
	criteria.SentSince = lastEmail
```

But that doesn't work because search criteria only cares about date, not datetime. Which means same day emails will have duplicates if run multiple times.

Is this an error or am I missing something?

**Comment by emersion** [comment]
The IMAP protocol doesn't support searches with time and/or timezone. Only the date is supported. See the RFC.
