### ISSUE TITLE
Message.GetBody should return BodyStructure body too

### ISSUE THREAD

**Issue by dgrr** [emersion/go-imap#345]
Hello,

I am facing an issue related to how the emails are parsed. I need to read the attached files and/or body but in some emails the body is parsed into `BodyStructure`, I was wondering if you could make [Message.GetBody](https://godoc.org/github.com/emersion/go-imap#Message.GetBody) return a Literal to BodyStructure if no body is found in Message.Body.

Thanks.

**Comment by emersion** [comment]
BODYSTRCTURE is not a literal, it's just the MIME tree.
