### ISSUE TITLE
Stall On Empty Address

### ISSUE THREAD

**Issue by NoelHG** [emersion/go-imap#346]
if 
`log.Println(to)` => `"[]"`

then
`to[0].Address`=> causes the thread to stall (no error)

This scenario is possible on some emails with only BBC

I expected an error in this scenario

EDIT: the struct is there but it's empty

**Comment by emersion** [comment]
You'll need to provide more details. What are you doing? Where is the program stalled (press Ctrl+backslash to gte a backtrace)? Can you provide debug logs (see `Client.SetDebug`)?
