### ISSUE TITLE
Bug:  set flag for one message 

### ISSUE THREAD

**Issue by dangerousvasil** [emersion/go-imap#347]
```
for msg := range messages {

		set := new(imap.SeqSet)
// add one msg to set
		set.AddNum(msg.SeqNum)

// infinity wait here
		err := c.Store(set, imap.AddFlags, []interface{}{imap.DeletedFlag}, nil)
// never come here
		if err != nil {
			log.Fatal(err)
		}
}
```

**Comment by emersion** [comment]
While iterating over `messages`, the IMAP `FETCH` command is still in progress. Executing multiple commands at a time is not supported. You need to accumulate messages in a list or in a `SeqSet`.

**Comment by dangerousvasil** [comment]
ok i understand 
but i need do some thing in transact one by one if something wrong i must roolback

i think i need accumulate all messages in array and run it one by one.
tnks for answer

**Comment by dangerousvasil** [comment]
or read by 100 msg and channel buffer up to 100 and it work well!
