### ISSUE TITLE
Change to newer error handling model (go1.13)

### ISSUE THREAD

**Issue by arnisoph** [emersion/go-imap#348]
error handling have been extended with 1.13, maybe it makes sense to apply these new options.

I'm struggling with some weird and unexpected disconnects from Gmail side and will a simple string comparison for https://github.com/emersion/go-imap/blob/master/client/client.go#L26 (private) now. 

https://blog.golang.org/go1.13-errors

**Comment by emersion** [comment]
This should be done on a case-by-case basis, as explained in the blog post. Please open separate issues/MRs with specific use-cases explained.
