### ISSUE TITLE
Noop blocks

### ISSUE THREAD

**Issue by loeffel-io** [emersion/go-imap#349]
Noop call blocks while using `Fetch/UidFetch`

**Comment by emersion** [comment]
Multiple concurrent commands are not supported.

**Comment by loeffel-io** [comment]
Thanks for your answer, didn`t know that. How you would handle this?

**Comment by emersion** [comment]
Accumulate FETCH results in a slice, process it after FETCH has completed.

**Comment by loeffel-io** [comment]
alright, but not what i wished for. Are multiple concurrent commands planed for v2 or is this an imap limitation? 

Thank you for your answers!

**Comment by emersion** [comment]
>Are multiple concurrent commands planed for v2 or is this an imap limitation?

Maybe. Executing multiple commands at the same time needs a lot of care, some combinations don't work because of IMAP limitations.
