### ISSUE TITLE
How to Mark Email as Read after print msg body !!

### ISSUE THREAD

**Issue by shubhagrwl** [emersion/go-imap#352]
Hello,

I'm developing a new application in go where i've to store all incoming emails message body into DB. I had done all part, but i didn't know how do i mark email as seen !!
Please help us, or share if anybody have code snippet for marking email as seen after print.

Thanks & Regards,
Shubham Agarwal

**Comment by foxcpp** [comment]
https://pkg.go.dev/github.com/emersion/go-imap/client?tab=doc#Client.Store
