### ISSUE TITLE
go modules

### ISSUE THREAD

**Issue by BMOD89** [emersion/go-imap#355]
Hi, 

I tried to build the example of the client example. I would like to use git modules to manage the dependencies. 

It does not matter which commands I use, I always get `no matching versions for query "latest"`. 

I run all the commands in a clean golang:1.14 container. 

For example this: 
```
root@ec6f191047c1:/data# go mod init github.com/emersion/go-imap  
go: creating new go.mod: module github.com/emersion/go-imap  
root@ec6f191047c1:/data# go run main.go  
go: finding module for package github.com/emersion/go-imap/client  
import cycle not allowed  
package main  
	imports github.com/emersion/go-imap  
	imports github.com/emersion/go-imap  
main.go:6:2: no matching versions for query "latest"
```

Using go mod tidy doesn't work, too: 
```
root@ec6f191047c1:/data# go mod tidy
go: finding module for package github.com/emersion/go-imap/client
github.com/emersion/go-imap imports
	github.com/emersion/go-imap/client: no matching versions for query "latest"
```

Using only go get (without go mod init, from a clean container) works:
```
root@cb14a59c9d24:/data# go get github.com/emersion/go-imap/...
root@cb14a59c9d24:/data# go run main.go 
2020/04/28 20:49:10 Connecting to server...
2020/04/28 20:49:12 dial tcp: lookup mail.example.org on 8.8.8.8:53: no such host
exit status 1
```
This are my first steps with go modules. What am I doing wrong? 

Thanks a lot!

**Comment by foxcpp** [comment]
`go mod init` creates a new module tree in the current directory. But when you do ` go mod init github.com/emersion/go-imap` you say that github.com/emersion/go-smtp is __the__ module in current directory so it gets confused when you also import it. You need to have a different name.

**Comment by BMOD89** [comment]
Thanks for your reply. By reading the documentation carefully it is now clear, too. Sorry for my stupid question :smile:
