### ISSUE TITLE
Allow to serve on multiple listeners

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#36]
Symmetry with `http.Server`.

Make sure to close correctly all connections by sending an untagged `BYE` response.

**Comment by emersion** [comment]
`Server.Close` will be added to `http`: https://github.com/golang/go/issues/4674

**Comment by peter-mogensen** [comment]
If symmetry with the http.Server API is the goal, then it seems the Go 1.8 http.Server.Serve() semantics is not quite the same as the imap Server.Serve().
Namely... http.Server.Serve(net.Listener) can be called multiple times. and the server will be serving an all listeners. You don't have to make 2 Server objects to serve on 2 listeners.

**Comment by emersion** [comment]
Yeah, you're right, allowing users to call serve multiple times would be better.
