### ISSUE TITLE
Program stops after loging?

### ISSUE THREAD

**Issue by Squuv** [emersion/go-imap#360]
Im trying to check messages from multiple  accounts while trying that it stops without printing any error... help?

	func checker(username string, password string, addr string) {
		c, err := client.DialTLS(addr, nil)
		if err != nil {
			log.Println(err)
		}
		log.Println("Connected")

		defer c.Logout()

		// Login
		if err := c.Login(username, password); err != nil {
			log.Println(err)
			return
		}
		log.Println("Logged in " + username)

		// List mailboxes
		mailboxes := make(chan *imap.MailboxInfo, 10)
		done := make(chan error, 1)
		go func() {
			done <- c.List("", "*", mailboxes)
		}()

		if err := <-done; err != nil {
			log.Println(err)
			return
		}
		// Select INBOX
		mbox, err := c.Select("INBOX", false)
		if err != nil {
			log.Fatal(err)
		}
		log.Println("Flags for INBOX:", mbox.Flags)
		// code...

	func main() {
		for e == nil {
			v := strings.Split(s, ":")
			// code here....
			checker(email, password, addr)
	}
`

output:
	2020/05/23 05:03:42 Logged in ***@orange.fr

it stops after printing this. i waited like 10 mins nothing happens

**Comment by foxcpp** [comment]
You are not consuming contents of mailbox channel.

**Comment by Squuv** [comment]
@foxcpp Wdym show example pls.

**Comment by foxcpp** [comment]
```

	// List mailboxes
	mailboxes := make(chan *imap.MailboxInfo, 10)
	done := make(chan error, 1)
	go func() {
		done <- c.List("", "*", mailboxes)
	}()

	if err := <-done; err != nil {
		log.Println(err)
	}
```
You are waiting for `c.List` to complete, it sends mailbox info to `mailboxes` channel. You are not reading from it. If there are more than 10 mailboxes - it will block. It will not complete and therefore you have a deadlock.
