### ISSUE TITLE
Envelope sender should be `nil` instead of `()`

### ISSUE THREAD

**Issue by kyazdani42** [emersion/go-imap#361]
As stated in [this issue](https://github.com/jonhoo/rust-imap/issues/166), the envelope parsing does not adhere to the spec.

It might be an issue i should fill in `go-imap` but i'm not sure about that, so i post it here in the meantime.

**Comment by emersion** [comment]
Transferred issue to go-imap.

Bug is here: https://github.com/emersion/go-imap/blob/06c36afc82fb759adca934563534140091910b3b/message.go#L709

Would you be willing to send a patch?
