### ISSUE TITLE
IMAP4rev2

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-imap#375]
I think it might be an interesting idea for go-imap v2 to track IMAP4rev2 development if we manage to implement all merged extensions.
https://datatracker.ietf.org/doc/draft-ietf-extra-imap4rev2/

**Comment by foxcpp** [comment]
Extensions merged into IMAP4rev2 specification:
- UNSELECT (#342)
- UIDPLUS
- ESEARCH (create issue)
- SEARCHRES (create issue)
- ENABLE (go-imap-enable, needs merging)
- SASL-IR :heavy_check_mark: 
- IDLE (go-imap-idle, needs merging)
- LIST-STATUS (create issue?)
- MOVE (go-imap-move, needs merging)

IMAP4rev2 also indirectly merges UTF8 extension (#16) by removing UTF-7 entirely.  And BINARY extension is partially merged too.

There is also a number of other changes that can be found in draft appendix.

**Comment by Neustradamus** [comment]
SCRAM has been integrated into the RFC9051: Internet Message Access Protocol (IMAP) - Version 4rev2:
- https://tools.ietf.org/html/rfc9051

Linked to:
- https://github.com/emersion/go-imap/issues/441
- https://github.com/emersion/go-imap/issues/454
- https://github.com/emersion/go-sasl/issues/14

**Comment by emersion** [comment]
This is incorrect, SCRAM is only mentioned as an alternative to DIGEST-MD5.

Stop spamming my repositories. What you're doing doesn't help the project.

**Comment by emersion** [comment]
RFC has been published: https://www.rfc-editor.org/rfc/rfc9051.html

**Comment by emersion** [comment]
IMAP4rev2 is implemented in go-imap v2.
