### ISSUE TITLE
Correction needed in the "Using extensions" Wiki page

### ISSUE THREAD

**Issue by HansK-p** [emersion/go-imap#376]
A correction is needed on the [Using extensions](https://github.com/emersion/go-imap/wiki/Using-extensions#using-client-extensions) Wiki page.

Current example:
<pre>
type IMAPClient struct {
	*imap.Client
	*idle.IdleClient
}

func NewIMAPClient(c *imap.Client) *IMAPClient {
	return &IMAPClient{
		c,
		idle.NewClient(c),
	}
}
</pre>
The example above is using *imap.Client*, but should have used *client.Client* when defining the IMAPClient struct.

**Comment by emersion** [comment]
Thanks, fixed!
