### ISSUE TITLE
Why all examples with Fetch go through goroutine

### ISSUE THREAD

**Issue by vkuznet** [emersion/go-imap#382]
Hi,
I'm trying to understand correct way to use the client Fetch API. According to all examples in [examples_test.go](https://github.com/emersion/go-imap/blob/master/client/example_test.go) the Fetch API is used through a goroutine, e.g.
```
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, items, messages)
	}()
```
see for instance lines 69, 108, 267, etc. The interesting part is that channel done is read **only** when someone parses messages channel. My question is why is this pattern? Can it be simpler to use
```
err := c.Fetch(seqset, items, messages)
if err != nil {
   log.Fatal(err)
}
for msg := range messages {
// process messages
}
```

The reason I ask is that I found a deadlock when I try to access messages from ProtonBridge to which I connect w/o TLS and when I do have a new message my code hangs on c.Fetch call if I **do not** use goroutine, but it works fine, i.e. it fetches new email when I do use goroutine as shown above. Here is a code which reproduces this behavior (is is purely based on examples_test.go):
```
	uri := "127.0.0.1:1143"
	username := "user@protonmail.com"
	password := "someHash"
	//     c, err := client.DialTLS(uri, nil)
	c, err := client.Dial(uri)
	if err := c.Login(username, password); err != nil {
		log.Fatal(err)
	}

	// Select INBOX
	_, err = c.Select("INBOX", false)
	if err != nil {
		log.Fatal(err)
	}

	// Set search criteria
	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := c.Search(criteria)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("IDs found:", ids)

	if len(ids) > 0 {
		seqset := new(imap.SeqSet)
		seqset.AddNum(ids...)

		section := &imap.BodySectionName{}

		messages := make(chan *imap.Message, len(ids))
		items := []imap.FetchItem{section.FetchItem(), imap.FetchFlags, imap.FetchEnvelope}

		err := c.Fetch(seqset, items, messages)
		if err != nil {
			log.Fatal(err)
		}

		// proceed
		log.Println("Unseen messages:")
		for msg := range messages {
			log.Println("* " + msg.Envelope.Subject)
		}

		//         if err := <-done; err != nil {
		//             log.Fatal(err)
		//         }
	}

	log.Println("Done!")
```

**Comment by emersion** [comment]
Because this allows users to consume messages as they are received, without having to wait for all messages. If you download a whole mailbox from the server for instance, this is important.
