### ISSUE TITLE
Lowercase DispositionParams keys?

### ISSUE THREAD

**Issue by sqwishy** [emersion/go-imap#383]
So I'm using the mail client aerc and sometimes it looks for a "filename" parameter in the content disposition on a message part. In my case, the string keys in the `DispositionParams` in the `imap.Message` are all uppercase. So my email has a "FILENAME" but not a "filename". My guess is that this library is is just using what the imap server gave it in the response?

I don't really know if the mail duder is being a weirdo, or if maybe parsing the BodyStructure should lowercase the keys kind of like how `mime.ParseMediaType` does?

Below is from a debugging session to illustrate the above.

```
> github.com/emersion/go-imap.parseHeaderParamList() /home/sqwishy/go/pkg/mod/github.com/emersion/go-imap@v1.0.4/message.go:123 (PC: 0x972c38)
Values returned:
	~r1: map[string]string [
	        "FILENAME": "Super Important Document.pdf",
	        "SIZE": "1094837",
	        "CREATION-DATE": "Wed, 06 May 2020 19:39:42 GMT",
	        "MODIFICATION-DATE": "Fri, 15 May 2020 22:23:32 GMT",
	]
	~r2: error nil

   118:func encodeHeader(s string) string {
   119:	return mime.QEncoding.Encode("utf-8", s)
   120:}
   121:
   122:func parseHeaderParamList(fields []interface{}) (map[string]string, error) {
=> 123:	params, err := ParseParamList(fields)
   124:	if err != nil {
   125:	        return nil, err
   126:	}
   127:
   128:	for k, v := range params {
(dlv) p fields
[]interface {} len: 8, cap: 8, [
	"FILENAME",
	"Super Important Document.pdf",
	"SIZE",
	"1094837",
	"CREATION-DATE",
	"Wed, 06 May 2020 19:39:42 GMT",
	"MODIFICATION-DATE",
	"Fri, 15 May 2020 22:23:32 GMT",
]
```

**Comment by foxcpp** [comment]
Most strings in MIME and IMAP are case-insensitive. Need to take a look at RFC 3501.

**Comment by emersion** [comment]
>maybe parsing the BodyStructure should lowercase the keys

Yes, I agree.

**Comment by foxcpp** [comment]
> Most strings in MIME and IMAP are case-insensitive. Need to take a look at RFC 3501.

RFC 3501 just refers to RFC 2183, which defines it as case-insensitive via ABNF. But yeah, I agree lower-casing it will make it less surprising. Could you submit a PR to do so?

**Comment by sqwishy** [comment]
> Could you submit a PR to do so?

If you're asking me, I totally can. I might not have much time before next week but, if you're not in a super hurry, I'll give it a shot.

**Comment by emersion** [comment]
We aren't in hurry, take your time :)
