### ISSUE TITLE
Admin privileges

### ISSUE THREAD

**Issue by lucasdiedrich** [emersion/go-imap#396]
hello. 👋👋

Is there a way where can i authenticate with admin privileges and use another user mailbox?

Somenthing similiar to this [Python functionality](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4.proxyauth).

Thanks.

**Comment by foxcpp** [comment]
Not sure what that method for and can't find any detailed information on the Internet.

**Comment by lucasdiedrich** [comment]
Actually it does nothing, but the idea is to authenticate with admin user and access user2 mailbox to backup it.

With python i had to made this, i don't know if i can do this with authenticate in go-imap.

![image](https://user-images.githubusercontent.com/817482/95328407-e7546700-087b-11eb-85eb-aec36f3ce254.png)

**Comment by foxcpp** [comment]
You seem to be looking for a way to specify **authorization** identity in addition to **authentication** one.

This is supported by go-sasl, see sasl.NewPlainClient.

**Comment by lucasdiedrich** [comment]
Thanks @foxcpp that's probably what i need.
