### ISSUE TITLE
Plan9 support

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-imap#397]
Apparently syscall.ECONNRESET is undefined when building with GOOS=plan9.
This causes compilation to fail here: https://github.com/emersion/go-imap/blob/c8e5db3cf6c416215b98533fa0996a131574e1dd/client/client.go#L157

Context: We got somebody trying to run [foxcpp/maddy](https://github.com/foxcpp/maddy) on Plan9. Client package is imported indirectly via go-imap-compress:
```
⟩ go mod why github.com/emersion/go-imap/client
# github.com/emersion/go-imap/client
github.com/foxcpp/maddy/internal/endpoint/imap
github.com/emersion/go-imap-compress
github.com/emersion/go-imap/client
```

**Comment by foxcpp** [comment]
60288381 added problematic code.

**Comment by foxcpp** [comment]
CC @Neopallium

**Comment by emersion** [comment]
https://github.com/emersion/go-imap/pull/225/commits/8001f1c3bf53a844ca4027201830e9d3a474de17

**Comment by Neopallium** [comment]
I don't remember how I was able to cause that error to happen.

**Comment by emersion** [comment]
IIRC those appeared when running the tests: https://github.com/emersion/go-imap/issues/399

**Comment by Neopallium** [comment]
Ah.  Yes.  The hack was to consume the connection reset error and turn it into a EOF condition.
