### ISSUE TITLE
How to authenticate with this capabilities?

### ISSUE THREAD

**Issue by Labutin** [emersion/go-imap#40]
CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED

I can't use Login function. And I don't understand how to use Authenticate

Thunderbird connects to server by STARTTLS using login and password w/o encryption.

Please, help me to connect to my imap server.

**Comment by emersion** [comment]
You have to first issue a STARTTLS command, and then capabilities should include AUTH=PLAIN and you will be able to use the LOGIN command. This prevents the password from being sent in clear text over the network.

**Comment by Labutin** [comment]
Ok, look at 
`func (c *Client) StartTLS(tlsConfig *tls.Config) (err error)`

at the end

```
c.isTLS = true
c.Caps = nil
return
```

it's reset Caps.
Ok, I can get it again
`c.Capability()`

```
	log.Println(c.Caps)
	if err = c.StartTLS(&tls.Config{InsecureSkipVerify: true}); err != nil {
		log.Fatal(err)
	}
	log.Println(c.Caps)
	c.Capability()
	log.Println(c.Caps)
```

I see output:

> map[IMAP4rev1:true IDLE:true STARTTLS:true ID:true ENABLE:true LOGINDISABLED:true LITERAL+:true SASL-IR:true LOGIN-REFERRALS:true]
> map[]
> map[ENABLE:true LOGINDISABLED:true AUTH=LOGIN:true LOGIN-REFERRALS:true LITERAL+:true SASL-IR:true ID:true IDLE:true IMAP4rev1:true]

capabilities doesn't  include AUTH=PLAIN :(

**Comment by emersion** [comment]
You can set `client.Debug = true` to see the IMAP commands and responses.

Capabilities are reset after STARTTLS because they are out-of-date. So yeah, you should issue a CAPABILITY command to get the new capabilities.

It's strange that the list doesn't include AUTH=PLAIN, the protocol states that servers must send it. But the capability AUTH=LOGIN is included, so the LOGIN command should work.

What's the server you're trying to connect to?

**Comment by Labutin** [comment]
Is it possible to enable Debug on client?
I am trying to connect to Dovecot 

Dovecot v2.2.24 (a82c823) starting up for imap, pop3, lmtp (core dumps disabled)

When I issue Login

```
	if err := c.Login(opts.EmailUser, opts.EmailPasswd); err != nil {
		log.Fatal(err)
	}
```

I see error: Unsupported authentication mechanism.

And error in dovecot logs:dovecot: imap-login: Disconnected (tried to use unsupported auth mechanism): user=<>, method=PLAIN, rip=172.19.0.1, lip=172.19.0.2, TLS: Disconnected, session=<oprD08o4WIasEwAB>

As I wrote in fist post Thunderbird can connect to Dovecot and it's uses LOGIN method
dovecot: imap-login: Login: user=<test>, method=LOGIN, rip=172.19.0.1, lip=172.19.0.2, mpid=134, TLS, session=<BVQmzco4UIasEwAB>

**Comment by Labutin** [comment]
Here is full source code:

```
	log.Println("Connecting to server...")

	// Connect to server
	c, err := client.Dial(opts.IMAPServer)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")

	// Don't forget to logout
	defer c.Logout()

	log.Println(c.Caps)
	if err = c.StartTLS(&tls.Config{InsecureSkipVerify: true}); err != nil {
		log.Fatal(err)
	}
	log.Println(c.Caps)
	c.Capability()
        delete(c.Caps, "LOGINDISABLED")
	log.Println(c.Caps)
	// Login
	if err := c.Login(opts.EmailUser, opts.EmailPasswd); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")

```
and this is output

```
Connecting to server...
Connected
map[ENABLE:true LOGINDISABLED:true IMAP4rev1:true LITERAL+:true SASL-IR:true LOGIN-REFERRALS:true ID:true IDLE:true STARTTLS:true]
map[]
map[IDLE:true AUTH=LOGIN:true IMAP4rev1:true LITERAL+:true LOGIN-REFERRALS:true SASL-IR:true ID:true ENABLE:true]
Unsupported authentication mechanism.
```

If I remove

`delete(c.Caps, "LOGINDISABLED")`

output is

> Connecting to server...
> Connected
> map[IMAP4rev1:true SASL-IR:true ENABLE:true IDLE:true STARTTLS:true LOGINDISABLED:true LITERAL+:true LOGIN-REFERRALS:true ID:true]
> map[]
> map[SASL-IR:true AUTH=LOGIN:true ID:true ENABLE:true IDLE:true LOGINDISABLED:true IMAP4rev1:true LITERAL+:true LOGIN-REFERRALS:true]
> Login is disabled in current state

**Comment by emersion** [comment]
Wow, your server config is weird. Is it your own server?

I finally found out that AUTH=LOGIN is an obsolete authentication mechanism:

> The LOGIN SASL mechanism is obsoleted in favor of the PLAIN
    SASL mechanism.

See https://tools.ietf.org/html/draft-murchison-sasl-login-00

So to make this work, the thing to do is to implement AUTH=LOGIN in https://github.com/emersion/go-sasl

It would be kind of wasted time because this mechanism is obsolete. If you can change your server config to enable AUTH=PLAIN that would be better.

**Comment by Labutin** [comment]
I see. Thank you.
My config was:

> disable_plaintext_auth = yes
> auth_mechanisms = login

I have changed to:

> disable_plaintext_auth = yes
> auth_mechanisms = login plain

And now I can connect to Dovecot!!!

**Comment by emersion** [comment]
Perfect, glad it works :)
