### ISSUE TITLE
imap proxy

### ISSUE THREAD

**Issue by po1yb1ank** [emersion/go-imap#400]
Hi.
I'm struggling with proxy implementation with this project.
I need to listen for client imap commands, change them inside proxy server and then send it to remote host (gmail for example)
I can't find any ways to manipulate client commands or server responses since server provides only ```s.ListenAndServe()```.
go-imap-proxy just duplicates all commands from client to remote host if I'm right so I'm looking for any useful ways to perform this actions

**Comment by emersion** [comment]
Commands are sent to the `Backend`.

Closing because this isn't a bug.

**Comment by po1yb1ank** [comment]
Ok, commands now clear for me
As for server, is there any way to log all the server responses if i'm not using go-imap/client? I'm connecting through telnet to go-imap-proxy that proxies stuff to remote server and I need to log remote server responses to prevent client from receiving prohibited info from my proxy. Thanks a lot
