### ISSUE TITLE
its not possible to create client from server connections

### ISSUE THREAD

**Issue by po1yb1ank** [emersion/go-imap#401]
```server.Conn``` type does not implement 'net.Conn' as some methods are missing: 

- ```Write(b []byte) (n int, err error)``` 
- ```LocalAddr() Addr``` 
- ```RemoteAddr() Addr```

so something like that is not possible.

```
func CreateClientFromConn(s *server.Server){
	s.ForEachConn(func(conn server.Conn) {
		c, err := client.New(conn)
	})
}
```

I think handling all connections to server through net.listen() & accept() in order to create clients is not very convenient.

**Comment by emersion** [comment]
What are you trying to do?

You can't create a client from an existing server connection. This doesn't make sense.

You might want to learn more about the `net` package.

**Comment by po1yb1ank** [comment]
So basically I'm trying to make go-imap/client instance for any incoming connection to server in order to log server responses to each connection with ```SetDebug()``` because server Debug writes info for all incoming connections in single buffer.

**Comment by emersion** [comment]
`Client` is not for servers. This can't work.

**Comment by po1yb1ank** [comment]
So I can't use go-imap/client **and** go-imap/server(or go-imap-proxy) together, am I right?

**Comment by po1yb1ank** [comment]
UPD:
connections to server are not from go-imap/client. So I'm trying to find a way to log server responses to each connection not having a client instance for connection and I can't find any way to perform this with your code. Also a little FAQ or wiki would be very useful to stop these annoying issues :)

**Comment by emersion** [comment]
The only way to dump commands and responses for debug purposes is via `Server.Debug`.
