### ISSUE TITLE
Gmail folders list issue

### ISSUE THREAD

**Issue by aidar87** [emersion/go-imap#403]
Hi,
There are only `[Gmail]/All Mail`, `INBOX` and `[Gmail]` in result of   `c.List("", "*", mailboxes)`  method.
Seems rest of Gmail folders are in   `[Gmail]`. Why not all Gmail folders in the result of `c.List("", "*", mailboxes)`  method?

**Comment by emersion** [comment]
Sounds like an issue with the server and not go-imap itself.
