### ISSUE TITLE
difference between "plain-text" and "html"

### ISSUE THREAD

**Issue by aidar87** [emersion/go-imap#406]
Hi, is it possible to distinguish  "plain-text" and "html" ?
There is not enough information in provided [example](https://github.com/emersion/go-imap/wiki/Fetching-messages): 
 `case *mail.InlineHeader:
// This is the message's text (can be plain-text or HTML)
b, _ := ioutil.ReadAll(p.Body)
log.Println("Got text: %v", string(b))`

**Comment by emersion** [comment]
Use the header's `ContentType` method.
