### ISSUE TITLE
SELECT Command is not valid in this state

### ISSUE THREAD

**Issue by sauravmaropost** [emersion/go-imap#410]
Hi emersion,
I am facing error **err: SELECT Command is not valid in this state**. Sometime it is not showing sometime it is showing.
Could you please help in same. I have also upgraded version of you library. Same issue is showing in Search.

Thanks
Regards
Saurav Kumar

**Comment by emersion** [comment]
You can only SELECT when authenticated. See the RFC.

**Comment by sauravmaropost** [comment]
> You can only SELECT when authenticated. See the RFC.

@emersion I am facing this issue only in yahoo. I have also generated password for less authenticated apps.Could you please guide me.
Thanks

**Comment by emersion** [comment]
No, sorry, I don't have time for this. Your issue doesn't contain any hint that this is a go-imap bug, that's why this issue is closed.
