### ISSUE TITLE
SELECT Command is not valid in this state.

### ISSUE THREAD

**Issue by sauravmaropost** [emersion/go-imap#411]
Hi @emersion  
I am facing this issue only in yahoo for other email service providers like gmail, hotmail etc. It is working fine. I have also generated password for less authenticated apps.Could you please guide me.
 Thanks

Best Regards 
Saurav Kumar

**Comment by emersion** [comment]
Duplicate of https://github.com/emersion/go-imap/issues/410

Please refrain from opening multiple issues.
