### ISSUE TITLE
aliyun mail uses UidSearch() or Search() method to report "invalid command or parameters"

### ISSUE THREAD

**Issue by TravieTee** [emersion/go-imap#412]
Hello, why does the program report an error "invalid command or parameters" when I use aliyun mail to call Search() or UidSearch(), below is my code and error info

        var c *client.Client
        // imap.mxhichina.com:993
	server := param.Server.Server 
	email := param.Server.Email
	password := param.Server.Password
	folder := param.Folder

	c = connect(server, email, password)
	if c == nil {
		return nil
	}

	_, err := c.Select(folder, true)

	if err != nil {
		log.Fatal(err)
	}

	// Set search criteria
	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := c.Search(criteria)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("IDs found:", ids)

 
![image](https://user-images.githubusercontent.com/46734926/102160330-3217de00-3ec0-11eb-8b0c-e78046c53b86.png)

**Comment by emersion** [comment]
Clsing per https://github.com/emersion/go-imap/pull/429

**Comment by abicai** [comment]
@TravieTee How did you solve the problem,I have the same problem

**Comment by cuihecuihe** [comment]
@abicai @TravieTee How did you solve the problem,I have the same problem

**Comment by xuecangqiuye** [comment]
![image](https://github.com/user-attachments/assets/e627cdd7-d95b-483f-8788-03e77ab517d1)
@emersion Hi
I have the same problem, how to solve?
