### ISSUE TITLE
How to get details 1 mail and replies by uid?

### ISSUE THREAD

**Issue by haytranngoc** [emersion/go-imap#413]
Hello 
how can I get detail 1 mail and replies by uid. Thank a lot.

**Comment by foxcpp** [comment]
See THREAD extension: https://github.com/emersion/go-imap-sortthread

Of course, server should support it but most do.

**Comment by haytranngoc** [comment]
@foxcpp Sorry, if the server doesn't support it, is there any other way to do it?
