### ISSUE TITLE
How to "join" multiple SearchCriteria

### ISSUE THREAD

**Issue by oelsoso** [emersion/go-imap#414]
Hello! I have a question about using the SearchCriteria and how can be used to produce the following search command:

`(UID 123:* (OR OR TEXT "string1" TEXT "string2" TEXT "string3"))`

Also if not possible, is there a way to execute search commands using a raw string, instead of using the SearchCriteria as parameter.

**Comment by emersion** [comment]
Maybe this?

```go
uids := new(imap.SeqSet)
uids.AddRange(123, 0)
imap.SearchCriteria{
    Uid: uids,
    Or: []*imap.SearchCriteria{
        {Text: []string{"string1"}},
        {Text: []string{"string2"}},
        {Text: []string{"string3"}},
    },
}
```

**Comment by oelsoso** [comment]
That would make perfect sense, however I receive the following error:
```
cannot use []*imap.SearchCriteria literal (type []*imap.SearchCriteria) as type [][2]*imap.SearchCriteria in field value
```
From looking at the documentation, I understand that the Or field should be grouped in pairs of two *imap.SearchCriteria. I adapted the code to this (apologies for the mess, I am quite new to go):

```
package main

import (
	"log"
	"github.com/emersion/go-imap"

)

func main(){
	criteria1:=imap.NewSearchCriteria()
	criteria2:=imap.NewSearchCriteria()
	criteria_or:=imap.NewSearchCriteria()

	uids := new(imap.SeqSet)
	uids.AddRange(123, 0)
	
	criteria_or.Uid=uids
	criteria1.Text=[]string{"string1"}
	criteria2.Text=[]string{"string2"}

	criteria_or.Or=[][2]*imap.SearchCriteria{{criteria1,criteria2}}

	log.Println(criteria_or.Format())
}
```
Result:

```
[UID 123:* OR [TEXT bbbbb] [TEXT aaaa]]
```

However I am not sure if it does what I want. What this does is search for the UID range OR the TEXT match. What I wanted is to search the UID range and the OR text expressions.

**Comment by emersion** [comment]
> What this does is search for the UID range OR the TEXT match. What I wanted is to search the UID range and the OR text expressions.

Hm, this criteria should be the latter, if my reading of the RFC is correct.

**Comment by oelsoso** [comment]
Not sure what you are referring to about the latter, can you point me exactly where? To keep it short, now that I somehow got a grip of how to use the OR, I need to add the OR expression in parenthesis (AND), which should match the TEXT expression starting from the given range, and not from the entire mailbox. I have tested the example above, and it matches the text regardless of the given UID range. 

Perhaps is there a way to execute a search with a more customizable command?

**Comment by foxcpp** [comment]
RFC 3501 describes OR syntax as `OR <search-key1> <search-key2>`.

What you have is `UID 123:* OR TEXT bbbbb TEXT aaaa`.
Where search-key1 is `TEXT bbbbb` and search-key2 is `TEXT aaaa`.

So if my understanding of RFC 3501 syntax is correct, this roughly means `(uid >= 123) and ((bbbbb in mail text) or (aaaa in mail text))`.

**Comment by oelsoso** [comment]
Ok, I probably got the wrong idea about using the parenthesis. I followed this article a while back when writing the same script in Python https://www.limilabs.com/blog/imap-search-requires-parentheses.

I will be experimenting more with this, hopefully I'll have some results, but for now I think we can close this. Thank you so much for your time guys.
