### ISSUE TITLE
shared mailboxes

### ISSUE THREAD

**Issue by eqinox76** [emersion/go-imap#415]
Hey all,
i am trying to access shared mailboxes. This seems to be a imap feature but i cannot find documentation on how to login as user a@company.com and get mails from shared@company.com.

Thanks to a discussion in a [php library](https://github.com/ddeboer/imap/issues/393) i figured out how to adjust the username:
```go
client, err = client.DialTLS("outlook.office365.com", tlsConfig)
if err != nil {
	return
}

err = client.Login("a@company.com/shared@company.com", "password")
if err != nil {
	return
}
```

Maybe you can add this information to the `client.Login` documentation.

Thanks in any case for this great library!

**Comment by emersion** [comment]
This seems like something that's specific to your IMAP server. It's not in the spec.

The standardized way of doing this is to use SASL PLAIN with a different username and identity I believe.

Thanks for the heads up though, might help someone.
