### ISSUE TITLE
Get only UNSEEN emails

### ISSUE THREAD

**Issue by wborbajr** [emersion/go-imap#416]
I'm traying to download attachment only unseen emails, but I don't know where set to search at inbox all emails that are unseen status.

Is it possible to do this?

**Comment by Rmcsy** [comment]
add `SeenFlag` to `WithoutFlags` field of [SearchCriteria](https://pkg.go.dev/github.com/emersion/go-imap#SearchCriteria), then [Search](https://godocs.io/github.com/emersion/go-imap/client#example-Client-Search)

 `criteria.WithoutFlags = []string{imap.SeenFlag}`
