### ISSUE TITLE
How can I get all message in inbox 

### ISSUE THREAD

**Issue by Warhead007** [emersion/go-imap#419]
Hello. I want to know it is possible to get all message in that inbox? like this.

<a href="https://imgur.com/2Vke2UG"><img src="https://i.imgur.com/2Vke2UG.png" title="source: imgur.com" /></a>

I can get only last message only.

**Comment by foxcpp** [comment]
You are probably using `*`  seqset instead of `1:*`.

**Comment by foxcpp** [comment]
You want to do `seqSet.AddRange(1, mbox.Messages)` (or `seqSet.AddRange(1, 0)` because zero represents `*` ).

**Comment by Warhead007** [comment]
> You want to do `seqSet.AddRange(1, mbox.Messages)` (or `seqSet.AddRange(1, 0)` because zero represents `*` ).

I want to access all message in this mail (one mail subject)

<img width="1431" alt="Screen Shot 2564-03-18 at 20 50 34" src="https://user-images.githubusercontent.com/19686618/111637021-9c2b8080-882b-11eb-8f1f-02a6ed1edc50.png">

They have many message in this subject (in my first picture) can I to get all of this?

**Comment by emersion** [comment]
I'd suggest reading the RFC.
