### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by yujiri8** [emersion/go-imap#421]
The documentation for Client.Append says:

> flags and date are optional arguments and can be set to nil. 

However, `date` is a non-pointer struct type so it cannot be nil.

**Comment by emersion** [comment]
It can be set to `time.Time{}`.

**Comment by yujiri8** [comment]
That is not nil. Setting it to nil causes an error.

**Comment by foxcpp** [comment]
If you believe this is a significant problem - make a PR to improve wording.
