### ISSUE TITLE
SentBefore - how to use? 

### ISSUE THREAD

**Issue by deadElk** [emersion/go-imap#424]
the logic: find messages without some flags and older then some time.Duration 
the code is below 
and it finds nothing 
what am i doing wrong? 
thanks 

_tick                 := time.NewTicker(_timeout_worker_retry)  // every 5 seconds  
message_search_criteria := &imap.SearchCriteria{
	WithoutFlags: []string{
	imap.SeenFlag,    // Don't download \Seen messages.
	"$Label1",        // CommuniGate.
	"\\Label1",       // CommuniGate (just to be sure).
	"$" + _SERVICED,  // ANNOUNCED.
	"\\" + _SERVICED, // ANNOUNCED (just to be sure).
	// "$MDNSent",       // CommuniGate, MicroSoft.
	// "\\MDNSent",      // CommuniGate, MicroSoft (just to be sure).
	},
}

for {
select {
	case stamp, flag := <-_tick.C:
		switch flag {
		case true:
			message_search_criteria.SentBefore = stamp.Add(message_search_criteria_older_than) // subtract 5 minutes, message_search_criteria_older_than is negative time.Duration 
			switch messages_uids, err := connection.Search(message_search_criteria); {
			case err == nil && len(messages_uids) > 0:

**Comment by emersion** [comment]
Closing per https://github.com/emersion/go-imap/pull/429
