### ISSUE TITLE
Sample Backend Updater

### ISSUE THREAD

**Issue by alidehghan** [emersion/go-imap#426]
How can I write an updater for my customized backend? any document or sample?

**Comment by emersion** [comment]
Closing since this isn't a bug report.

**Comment by egcaragay** [comment]
Create global variable for channel chan backend.Update

Or something like this

//Backend

type BackEnd struct {
	Updater chan backend.Update
}

func NewBackEnd() *BackEnd {
       //...
	updates := make(chan backend.Update)
	b := &BackEnd{
		updates,
	}

	return b
}


func (b *BackEnd) Login(_ *imap.ConnInfo, username, password string) (backend.User, error) {
	//...
	bUser := User{
                //...
		Updater:  b.Updater,
	}

	return &bUser, nil
}

func (b *BackEnd) Updates() (u <-chan backend.Update) {
	return b.Updater
}

//User

type User struct {
       //...
	Updater  chan backend.Update
}

func (u *User) ListMailboxes(subscribed bool) (mailboxes []backend.Mailbox, err error) {
	//Sample getting mailboxes
        err, mbs := model.GetMailBoxes(subscribed, u.id)
	for _, mailbox := range mbs {
		mailbox.UserName = u.username
		mailbox.Updater = u.Updater
		mailboxes = append(mailboxes, mailbox)

	}

	return mailboxes, err
}

//Mailbox


type Mailbox struct {
	//...
	Updater  chan backend.Update
	UserName string 
}

func (m *Mailbox) CreateMessage(flags []string, date time.Time, body imap.Literal) error {
	//...
        // Call updater here
        go NewMailboxUpdate(m.UserName, m.Updater, m)
	return nil
}

func NewMailboxUpdate(username string, updater chan backend.Update, m backend.Mailbox) {
	u := backend.NewUpdate(username, m.Name())
	status, _ := m.Status([]imap.StatusItem{
		imap.StatusMessages,
		imap.StatusUidNext,
		imap.StatusUidValidity,
		imap.StatusRecent,
		imap.StatusUnseen,
	})
	mbu := backend.MailboxUpdate{
		Update:        u,
		MailboxStatus: status,
	}

	updater <- &mbu
}

P.S
I am new with golang, i don't know if there's something better implementation.
