### ISSUE TITLE
How can I make persistent connection with Imap client?

### ISSUE THREAD

**Issue by andiksetyawan** [emersion/go-imap#428]
I want to login using my Imap credentials once and keep the connection persistent.
I am trying to create an web email client application. I want a connection that persists so that I don't have to login for each action I have to perform in Imap server.

How do Email clients like hotmail, gmail and yahoo keep connection persistent?

**Comment by foxcpp** [comment]
This is something you should account for in your application design. Just keep imap.Client object around (and also take a look at things like go-imap-idle)
