### ISSUE TITLE
FETCH FLAGS and unilateral messages: Unexpected results

### ISSUE THREAD

**Issue by Necoro** [emersion/go-imap#430]
IMAP servers (here: Dovecot) tend to send you some information "while you're at it". go-imap in general handles them via the `Updates` channel. I stumbled now upon an issue with FETCH FLAGS and an unilateral update:

```
a66 uid fetch 213531 flags
* 2004 FETCH (UID 213531 FLAGS (\Seen))
* 1994 FETCH (FLAGS ())
a66 OK Fetch completed (0.001 + 0.000 secs).
```

In this case, a `c.UidFetch(213531, imap.FetchFlags)` _(pseudo-code)_ will yield TWO messages as a result (the one for the message asked, and another). And this was totally unexpected on my end, leading to dead-locks, because I stopped reading from the message channel after the first result.

This is either

- an implementation bug: `Fetch.Handle` should ensure to only handle requested messages and pass the rest onto the Update handler
- a documentation ... enhancement: Make it clear, that this command can return more than one asked for.

If it is decided to be the former, I can create a PR for the fix.

**Comment by emersion** [comment]
> send you some information "while you're at it"

Are you sure this isn't a unilateral update? ie. some other client has updated flags for a completely unrelated message, and the server broadcasts the update to all connected clients?

**Comment by Necoro** [comment]
@emersion: No, unilateral update is exactly what I wanted to describe.

Problem case is when such a unilateral update for flags occurs the same time the client asks for specific flags.

**Comment by foxcpp** [comment]
I would consider this an implementation bug.

**Comment by emersion** [comment]
I see

> an implementation bug: Fetch.Handle should ensure to only handle requested messages and pass the rest onto the Update handler

Yeah, this sounds reasonable.
