### ISSUE TITLE
RFE: Provide option for explicitly enabling IPv4-only or IPv6-only connections

### ISSUE THREAD

**Issue by atc0005** [emersion/go-imap#434]
I still consider myself new/intermediate to Go, so it's likely that I'm overlooking something, but I'd like to be able to explicitly specify a IPv4-only or IPv6-only connection instead of letting what is returned by DNS dictate the connection type.

In my use case I'd like to offer the user a flag (or set of flags) for only using IPv4, only IPv6 or auto (the default).

I don't see a way to override `tcp` with `tcp4` or `tcp6` in either of these locations:

- https://github.com/emersion/go-imap/blob/0e5bf8b8c24d2bb1481e94a44c18d3fa2dfbb630/client/client.go#L619-L620
- https://github.com/emersion/go-imap/blob/0e5bf8b8c24d2bb1481e94a44c18d3fa2dfbb630/client/client.go#L654-L655

As a workaround I've added a step to perform the DNS lookup directly, then loop over the results attempting a connection to each until one succeeds, which more often than not I expect would be the first result.

If I'm asking for something that is already available, please point me towards the relevant docs. I did try to review them in detail first before reporting this, but it is entirely possible I looked right over it.

Thanks in advance for your time & consideration!

**Comment by emersion** [comment]
Use `Client.New` if you need more customization around the `net.Conn` creation.
