### ISSUE TITLE
err : atom contains forbidden char （

### ISSUE THREAD

**Issue by genggengyuhuai** [emersion/go-imap#435]
when I connect to Tencent mail Server by `client.DialTLS("pop.qq.com:995", nil)` it return an error called `atom contains forbidden char :（`.

 In this function, client will greet to the server by  `c.handleGreetAndStartReading()` .
    
 by debugging this function, I find the server successfully returns this message `+OK XMail POP3 Server v1.0 Service Ready(XMail v1.0)` in the response, but `func (r *Reader) ReadAtom() (interface{}, error) ` in read.go reads the " Ready(XMail v1.0)" in the message and return an error because the content contains '(' character.  

As a result, I can't connect to the Tencent mail Server successfully.

**Comment by foxcpp** [comment]
From RFC 3501 (IMAP4rev1):
```
greeting        = "*" SP (resp-cond-auth / resp-cond-bye) CRLF
resp-cond-auth  = ("OK" / "PREAUTH") SP resp-text
                    ; Authentication condition
resp-text       = ["[" resp-text-code "]" SP] text
text            = 1*TEXT-CHAR
TEXT-CHAR       = <any CHAR except CR and LF>
```

From RFC 5234 (ABNF):
```
         CHAR           =  %x01-7F
                                ; any 7-bit US-ASCII character,
                                ;  excluding NUL
```

FWIW Tencent Mail Server seems to be breaking RFCs by including non-ASCII characters where they are not alloweed.

**Comment by genggengyuhuai** [comment]
> From RFC 3501 (IMAP4rev1):
> 
> ```
> greeting        = "*" SP (resp-cond-auth / resp-cond-bye) CRLF
> resp-cond-auth  = ("OK" / "PREAUTH") SP resp-text
>                     ; Authentication condition
> resp-text       = ["[" resp-text-code "]" SP] text
> text            = 1*TEXT-CHAR
> TEXT-CHAR       = <any CHAR except CR and LF>
> ```
> 
> From RFC 5234 (ABNF):
> 
> ```
>          CHAR           =  %x01-7F
>                                 ; any 7-bit US-ASCII character,
>                                 ;  excluding NUL
> ```
> 
> FWIW Tencent Mail Server seems to be breaking RFCs by including non-ASCII characters where they are not alloweed.

Yes I know，but this is not the reason that the library throws error. The '(' character which the greeting text contains leads to this error, but '(' is US-ASCII %x28, that is a correct character. Thanks for your reply 😀.

![Lark20210719-234349](https://user-images.githubusercontent.com/30818378/126188273-bccd6fd8-2a31-4049-869d-a65dcb6d0750.png)

**Comment by foxcpp** [comment]
Oh, I am blind. Right, greeting parsing should allow more than what atom would.

**Comment by foxcpp** [comment]
Also, it seems like you trying to connect to the POP3 server instead of IMAP4 one.

**Comment by foxcpp** [comment]
I verified the go-imap code and it handles non-atom characters in info correctly.

**Comment by genggengyuhuai** [comment]
so how can I parse the&nbsp;greeting message successfully?&nbsp; &nbsp;thanks a lot.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Max ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 凌晨1:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [emersion/go-imap] err : atom contains forbidden char （ (#435)





 
Oh, I am blind. Right, greeting parsing should allow more than what atom would.

**Comment by francisLee777** [comment]
> Oh, I am blind. Right, greeting parsing should allow more than what atom would.

so how can I parse the greeting message successfully?  thanks a lot.
