### ISSUE TITLE
Showing Invalid credentials 

### ISSUE THREAD

**Issue by bsandy999** [emersion/go-imap#436]
Below is the output getting after configuring the proper email id and password. 
Using Yahoo mail settings as an IMAP account. 

[root@stage1 go-imap]# go run main.go 
2021/07/20 20:11:37 Connecting to server...
2021/07/20 20:11:37 Connected
2021/07/20 20:11:41 LOGIN Invalid credentials
exit status 1
[root@stage1 go-imap]#

**Comment by emersion** [comment]
This doesn't sound like a go-imap bug, sorry. I don't know why Yahoo returns this error.

**Comment by johnwilson** [comment]
You need to go to https://login.yahoo.com/myaccount/security and create an app password. Use the generated password for your access credentials along with your email address.
