### ISSUE TITLE
How To Add IMAP ID

### ISSUE THREAD

**Issue by LiuMicah** [emersion/go-imap#437]
Thanks!
Netease Ltd. 163/126 Email Need To Add IMAP ID to Connection!
The Demo For Python, But I'dont Know How To Add Go-Imap!

```
rom imapclient import IMAPClient

server = IMAPClient("imap.163.com", ssl=True, port=993)
server.login("<user>", "<passwd>")

server.id_({"name": "IMAPClient", "version": "2.1.0"})

messages = server.select_folder('INBOX')
```

**Comment by emersion** [comment]
Sorry, we don't answer questions on GitHub. Please use the IRC channel.
