### ISSUE TITLE
Wiki example did not work

### ISSUE THREAD

**Issue by TheTitanrain** [emersion/go-imap#438]
I have the issue `cannot use section (type imap.BodySectionName) as type *imap.BodySectionName in argument to msg.GetBody` in line `r := msg.GetBody(section)` when trying example on https://github.com/emersion/go-imap/wiki/Fetching-messages

**Comment by emersion** [comment]
Try `&section` maybe?

**Comment by foxcpp** [comment]
Updated example to use `&section`.
https://github.com/emersion/go-imap/wiki/Fetching-messages/db1fcaac06e744b0561e8d386d5ddc03781bc2cd

**Comment by TheTitanrain** [comment]
Thanks!
