### ISSUE TITLE
Wiki page outdated

### ISSUE THREAD

**Issue by harryzcy** [emersion/go-imap#449]
The wiki page "Using authentication mechanisms" is outdated and the code no longer works. Specifically, the changes made to the sasl package means that many functions and variables can't be used. Will the wiki be updated to reflect the changes?

**Comment by foxcpp** [comment]
Updated XOAUTH example to use OAUTHBEARER instead.

**Comment by emersion** [comment]
No, XOAUTH2 is not supported anymore.

**Comment by FabianTe** [comment]
Mind me asking why XOAUTH2 is not supported?
