### ISSUE TITLE
Is there any way to setup auto reconnect when tcp disconnect

### ISSUE THREAD

**Issue by gtsigner** [emersion/go-imap#457]
im using proxy on my local codes, tcp will be closed when proxy server change. so is there any way to solve it?

![image](https://user-images.githubusercontent.com/13638996/154169657-a35196df-ad18-46e6-9a89-a4ef7912efd0.png)

**Comment by godtoy** [comment]
this error encounter in select method.

**Comment by godtoy** [comment]
![image](https://user-images.githubusercontent.com/13638996/154169798-387a9493-6ff5-43bd-9cfc-c77ba25648dd.png)

**Comment by godtoy** [comment]
the conn of the client is easy to disconnet if the network is unstable. i didn't find any issue talk about it. im very appreciate it if anyone can provide idea to fix it.

**Comment by emersion** [comment]
You'll need to handle the reconnect logic yourself. The library won't auto-reconnect.
