### ISSUE TITLE
Code should use unidirectional channels, where appropriate

### ISSUE THREAD

**Issue by ThomasHabets** [emersion/go-imap#458]
The API docs would be easier to read if e.g. [Client.Fetch](https://pkg.go.dev/github.com/emersion/go-imap/client#Client.Fetch) took a write-only channel. Then it would be clear that it's an output.

**Comment by emersion** [comment]
Indeed. Unfortunately this doesn't bode well with our (arguably bad) implementation in `responses.Fetch`, which is used for both the client and the server.

**Comment by emersion** [comment]
Closing because go-imap v2 stops using Go channels in the public API.
