### ISSUE TITLE
FetchBody should always include []

### ISSUE THREAD

**Issue by n3pheddy** [emersion/go-imap#460]
https://github.com/emersion/go-imap/blob/dcd9ee65c8c7e5d275413635eb84b525eebe75b1/imap.go#L35

The `FetchBody` constant is set to `BODY`. This matches the description on [RFC3501 7.4.2](https://datatracker.ietf.org/doc/html/rfc3501#section-7.4.2), but in practice IMAP servers are expecting `BODY[]` instead. I tested this behavior on Yandex and Gmail. Both do not return the message content for `BODY`.

I suggest to modify this to `BODY[]`, and also add a new constant `FetchBodyPeek  FetchItem = "BODY.PEEK[]"`. Most IMAP clients use `BODY.PEEK[]` when downloading messages to avoid being marked as seen. Tested this on Mozilla Thunderbird 91.6.1 (64-bit) OS X.

**Comment by Simerax** [comment]
Same for office365. Using `imap.FetchBody` does not work but `imap.FetchItem("BODY[]")` does.

**Comment by emersion** [comment]
NACK. Use `imap.BodySectionName{}.FetchItem()` instead.
