### ISSUE TITLE
mail.CreateReader issues unhandled charset "iso-8859-1" error

### ISSUE THREAD

**Issue by marhar** [emersion/go-imap#464]
While executing the example code in
https://github.com/emersion/go-imap/wiki/Fetching-messages ,
I received this error regarding an unhandled charset.

Is it possible to set a charset or otherwise handle this situation?

	// Create a new mail reader
	mr, err := mail.CreateReader(r)
	if err != nil {
		log.Fatal(err)
	}
2022/05/08 22:32:47 unknown charset: unknown charset: message: unhandled charset "iso-8859-1"

**Comment by emersion** [comment]
See the documentation: https://godocs.io/github.com/emersion/go-message

("Add this import to your package if you want to handle most common charsets by default")
