### ISSUE TITLE
Changable network for DialWithDialer/DialWithDialerTLS

### ISSUE THREAD

**Issue by eklatzer** [emersion/go-imap#466]
Hey, when using DialWithDialer and DialWithDialerTLS I would need to set the network of the first line of the funcs:
`conn, err := dialer.Dial("tcp", addr)`
Instead of tcp I would need tcp4/tcp6 to force the connection to be made via IPv4/IPv6. Would it be possible to make the value used for network changeable?

**Comment by emersion** [comment]
Can you use NewClient instead? The Dial functions are for convenience only.

**Comment by eklatzer** [comment]
I am currently using it, but I would like it, if it was changeable, maybe by having a global variable, that has `tcp` also Default-Value, but can be changed?

**Comment by eklatzer** [comment]
I am currently using it, but I would like it, if it was changeable, maybe by having a global variable, that has `tcp` as default value, but that can be changed?

**Comment by emersion** [comment]
Nope, sorry. This would be a bad design.
