### ISSUE TITLE
About Chinese mail garbled

### ISSUE THREAD

**Issue by BeanKaKa** [emersion/go-imap#467]
你好，我在使用Header.get()时遇到了乱码，我尝试使用imap.CharsetReader = charset.Reader 去解决他，但不行，这是一封中文邮件。（感谢提醒，代码已贴出）
Hello, I am using Header.Get() encountered garbled code. I tried to use imap CharsetReader = charset. Reader went to solve him, but no, this is a Chinese email (thanks for reminding, the code has been posted)

**Comment by BeanKaKa** [comment]
Hello, I am using Header.Get() encountered garbled code. I tried to use imap CharsetReader = charset. Reader went to solve him, but no, this is a Chinese email

**Comment by iredmail** [comment]
将具体的错误信息贴出来，否则别人没法帮忙。这是基本要求。

**Comment by iredmail** [comment]
最好能贴完整代码来重现这个问题，这样别人容易重现问题并解决之。

**Comment by BeanKaKa** [comment]
`	 var c *client.Client
        mbox, err := conn.Select("INBOX", false)
	if err != nil {
		log.Fatal(err)
	}

	// Get the last message
	if mbox.Messages == 0 {
		log.Fatal("No message in mailbox")
	}
	seqset := new(imap.SeqSet)
	seqset.AddRange(mbox.Messages, mbox.Messages)

	// Get the whole message body
	section := &imap.BodySectionName{}
	items := []imap.FetchItem{section.FetchItem()}

	messages := make(chan *imap.Message, 1)
	done := make(chan error, 1)
	go func() {
		done <- conn.Fetch(seqset, items, messages)
	}()
	imap.CharsetReader = charset.Reader
	log.Println("Last message:")
	msg := <-messages
	r := msg.GetBody(section)
	if r == nil {
		log.Fatal("Server didn't returned message body")
	}

	if err := <-done; err != nil {
		log.Fatal(err)
	}

	m, err := mail.ReadMessage(r)
	if err != nil {
		log.Fatal(err)
	}

	header := m.Header
	log.Println("Date:", header.Get("Date"))
	log.Println("From:", header.Get("From"))
	log.Println("To:", header.Get("To"))
	log.Println("Subject:", header.Get("Subject"))

	body, err := ioutil.ReadAll(m.Body)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(body)
}
`
上面是我使用的代码，我尝试将 
`items := []imap.FetchItem{section.FetchItem()}`
修改为
`items := []imap.FetchItem{section.FetchItem(), imap.FetchEnvelope}`
并使用 msg.Envelope.Subject 来输出标题，它是正常输出
当我使用  header.Get("Subject") 时，它输出的是 =?gb18030?B?ztKy3Q==?=

**Comment by iredmail** [comment]
你管这叫乱码？😂看点 RFC wend再来啊。

凡是含有 non-ascii 字符集的内容都要经过 encode，这是 encode 之后的内容，你需要自行 decode。

**Comment by BeanKaKa** [comment]
> 

感谢，我以为使用`header.Get`也会和`msg.Envelope.Subject`一样输出中文不用转编码😂，我直接用envelope吧
