### ISSUE TITLE
Reading emails

### ISSUE THREAD

**Issue by ivanjaros** [emersion/go-imap#473]
How am I supposed to actually get to the content of the email like actual text, attachments or embedded assets? That whole(cyclical) `BodyStructure ` thing doesn't make any sense to me. Could you provide examples in the readme file?

**Comment by mlnoga** [comment]
That would be really helpful.

**Comment by emersion** [comment]
There are examples in the wiki.

**Comment by MarcoWel** [comment]
@emersion 
> There are examples in the wiki.

- The GitHub Wiki is still for v1: https://github.com/emersion/go-imap/wiki/Fetching-messages
- The new docs do not have an example nor any kind of actual documentation about Walk(): https://pkg.go.dev/github.com/emersion/go-imap#BodyStructure.Walk
- The examples do not contain Walk() at all: https://github.com/emersion/go-imap/blob/v2/imapclient/client_test.go

I am trying to get this to work with go-imap v2, but I have no clue how to use the Walk() function. I would prefer it to work like in v1 where you were not forced to use a Walk() function at all.

**Comment by mkashifbaloch** [comment]
agree there is no doc available

**Comment by skamensky** [comment]
I'm new to this library so I tried using v2 right away (also v2 is the default branch),

It looks like you need to traverse the hierarchy with `BodyStructure` (which also contains parameters and mediatype), and get the actual body data from `BodySection` which contains bytes like so  `map[*imap.FetchItemBodySection][]byte`. However, it's not clear to me how to map the BodySection to the mediatype of BodyStructure. I tried using the `path` from the `Walk` function, but that turned out to be a bust.

In the end I went to version 1 which works just fine.

**Comment by emersion** [comment]
Added an example for go-message usage with v2: https://github.com/emersion/go-imap/commit/9f55f6d977543451aba8dd3a5b9495c0429cc9f2

**Comment by themachine2025** [comment]
The example is not working. I've just tested with a multipart email (like all/most emails nowadays) received in gmail.
The body of the part is always an empty string(no error is returned when `io.ReadAll(p.Body)` ) and for some reasons NextPart() returns only one part  : the text/plain part. The HTML part  (text/html) is never returned. Is there any other "flag" or setting required to force it fetch the body as well ?

Here is a snippet froim the code I use

```

fetchOptions := &imap.FetchOptions{
		Envelope:    true,
		UID:         true,
		BodySection: []*imap.FetchItemBodySection{{}}, // Fetch the entire message
	}
	fetchCmd := client.Fetch(uidSet, fetchOptions)
	defer fetchCmd.Close()
	for {
		msg := fetchCmd.Next()
		if msg == nil {
			break
		}
		log.Errorf("fetchCmd.Next")
		// Extract the message body
		var bodySection imapclient.FetchItemDataBodySection
		var uidData imapclient.FetchItemDataUID
		var envelope imapclient.FetchItemDataEnvelope
		var bodySectionOK, uidDataOK, envelopeOK bool
		for {
			log.Errorf("Msg  NextPart")
			item := msg.Next()
			if item == nil {
				break
			}
			if !bodySectionOK {
				bodySection, bodySectionOK = item.(imapclient.FetchItemDataBodySection)
			}
			if !uidDataOK {
				uidData, uidDataOK = item.(imapclient.FetchItemDataUID)
			}
			if !envelopeOK {
				envelope, envelopeOK = item.(imapclient.FetchItemDataEnvelope)
			}
		}
		switch {
		case !bodySectionOK:
			return fmt.Errorf("bodySectionOK section not found for this message %v", msg.SeqNum)
		case !uidDataOK:
			return fmt.Errorf("uidDataOK section not found for this message %v", msg.SeqNum)
		case !envelopeOK:
			return fmt.Errorf("envelopeOK section not found for this message %v", msg.SeqNum)
		}

		// Process the message using the go-message library
		if err := processMessage(bodySection.Literal); err != nil {
			log.Errorf("Error processing message: %v", err)
			return err
		}




func processMessage(body io.Reader) error {
	log.Errorf("Process message %v", msgUID)
	// Create a mail reader
	if body == nil {
		return fmt.Errorf("processMessage  body is nil?")
	}
	msg, err := mail.CreateReader(body)
	if err != nil {
		return err
	}
	// Print a few header fields
	h := msg.Header
	 
	// Process the message's parts
	for {
		p, err := msg.NextPart()
		if err == io.EOF {
			break
		} else if err != nil {
			log.Error(err)
			return err
		}
		log.Errorf("part %q", p.Header)

		var body []byte
		 
		switch h := p.Header.(type) {
		case *mail.InlineHeader:
			// This is the message's text (plain-text or HTML)
			body, err = io.ReadAll(p.Body)
			if err != nil {
				log.Error(err)
				return err
			}
// it seems we always get an empty string HERE:
			if string(body) == "" {
				return fmt.Errorf("invalid body")
			}
			log.Errorf("body %s", body)
		case *mail.AttachmentHeader:
			// This is an attachment
			fileName, _ = h.Filename()
			body, err = io.ReadAll(p.Body)
			if err != nil {
				log.Error(err)
				return err
			}
		default:
			err = fmt.Errorf("processMessage unknown header type %T", p.Header)
			log.Error(err)
			return err
		}
		contentType, params, err := h.ContentType()
		if err != nil {
			log.Error(err)
		}
		log.Errorf("content-type %s body is %s", contentType, body)
		 
	}
	 
	return nil
}

```

**Comment by themachine2025** [comment]
After further debugging I've found that `bodySection.Literal` is empty . Either gmail is not sending it or the library messes it up somewhere
