### ISSUE TITLE
Fetch feed nils into the channel

### ISSUE THREAD

**Issue by ivanjaros** [emersion/go-imap#474]
```
seqset := new(imap.SeqSet)
seqset.AddRange(mbox.UnseenSeqNum, mbox.Messages)
errCh <- p.cl.Fetch(seqset, []imap.FetchItem{imap.FetchEnvelope}, rawMsgCh)
```

will feed nils into the channel. How come?

**Comment by emersion** [comment]
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.
