### ISSUE TITLE
Enable adds quote mark to caps

### ISSUE THREAD

**Issue by christianWilling** [emersion/go-imap#476]
it sends the arguments with quote marks like `gOanqA ENABLE "CONDSTORE"` but some servers dousnt support this.
According to the spec is schould be `gOanqAENABLE CONDSTORE` 

so `enable.go` sould look like this:
```go
func (cmd *Enable) Command() *imap.Command {
	args := make([]interface{}, len(cmd.Caps))
	for i,c := range cmd.Caps {
		args[i] = imap.RawString(c)
	}

	return &imap.Command{
		Name:      "ENABLE",
		Arguments: args,
	}
}
```

**Comment by emersion** [comment]
Would you be willing to send a pull request to fix this?

**Comment by christianWilling** [comment]
yes no problem #477
