### ISSUE TITLE
Exchange 2013: The specified charset is not supported.

### ISSUE THREAD

**Issue by chris-garrett** [emersion/go-imap#48]
It looks like ms exchange does not like searching with UTF-8. I have found a few pages out there talking about it. 

1. https://social.technet.microsoft.com/Forums/en-US/00bb2ec5-9951-40b4-8ec3-97e5a8f1a59f/imap-search-with-utf8?forum=exchangesvrsecuremessaging

2. MatterMail (which wraps mxk/go-imap) is trying UTF-8 first and then falling back to US-ASCII. https://github.com/rodrigocorsi2/mattermail/issues/7

**Comment by emersion** [comment]
This happens here: https://github.com/emersion/go-imap/blob/master/client/cmd_selected.go#L95

Maybe add a `Charset` field in `imap.SearchCriteria`?

**Comment by chris-garrett** [comment]
I don't know much at all about IMAP, is there a way to determine the servers capabilities?

**Comment by emersion** [comment]
> US-ASCII MUST be supported; other [CHARSET]s MAY be supported.
If the server does not support the specified [CHARSET], it MUST
      return a tagged NO response (not a BAD).  This response SHOULD
      contain the BADCHARSET response code, which MAY list the
      [CHARSET]s supported by the server.
-- (RFC 3501 page 50)

So if the server replies with `BADCHARSET` we should retry with ascii.

**Comment by chris-garrett** [comment]
Ok, I will take a look at this.
