### ISSUE TITLE
Support respecting IMAP transfer quotas

### ISSUE THREAD

**Issue by nate-anderson** [emersion/go-imap#482]
It would be great to be able to limit the data fetched by a client. Gmail has a 2500mb/day transfer limit for IMAP, for example - I would like my client to leave at least 250mb for other clients to use, so I would like to be able to pass a maximum transfer amount to the client on instantiation, _or_ check the client's used bandwidth periodically.

**Comment by emersion** [comment]
This is the library's user responsibility, not go-imap's.

**Comment by nate-anderson** [comment]
@emersion thanks for responding - I don't see any mechanism the library exposes for tracking the actual data transferred from the IMAP server. The library use could approximate this by measuring the data returned by the library, but there is probably overhead as part of the protocol that would not be covered by this strategy

**Comment by emersion** [comment]
You can implement your own rate limiter or bandwidth limiter as a `net.Conn` wrapper and pass it to `NewClient`.
