### ISSUE TITLE
Login failed at outlook

### ISSUE THREAD

**Issue by FredericoBender** [emersion/go-imap#487]
I'm trying to make login at outlook with the following code snippet, but returns to me "LOGIN failed"

```
package main

import (
	"log"
	"testing"

	"github.com/emersion/go-imap/client"
)

// TestHelloName calls greetings.Hello with a name, checking
// for a valid return value.
func TestHelloName(t *testing.T) {
	c, err := client.DialTLS("outlook.office365.com:993", nil)
	if err != nil {
		log.Fatal(err)
	}
	defer c.Logout()

	if err := c.Login("your_email@outlook.com", "password_here"); err != nil {
		log.Fatal("Making login:", err)
	}
}
```
I tried to find the problem but I couldn't, also in the "command.go" file, inside the WriteTo() function, when I show the variable called "fields", the result seems to be right 

--> [ Ij0qma   LOGIN   myEmail@outlook.com   myPassword]

can you check the problem?

**Comment by atc0005** [comment]
@FredericoBender You'll likely need to use OAuth to login.

Some references:

- https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online
- https://developers.google.com/gmail/xoauth2_protocol 
- https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#sasl-xoauth2

**Comment by MattiaLeoni** [comment]
> I'm trying to make login at outlook with the following code snippet, but returns to me "LOGIN failed"
> 
> ```
> package main
> 
> import (
> 	"log"
> 	"testing"
> 
> 	"github.com/emersion/go-imap/client"
> )
> 
> // TestHelloName calls greetings.Hello with a name, checking
> // for a valid return value.
> func TestHelloName(t *testing.T) {
> 	c, err := client.DialTLS("outlook.office365.com:993", nil)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer c.Logout()
> 
> 	if err := c.Login("your_email@outlook.com", "password_here"); err != nil {
> 		log.Fatal("Making login:", err)
> 	}
> }
> ```
> 
> I tried to find the problem but I couldn't, also in the "command.go" file, inside the WriteTo() function, when I show the variable called "fields", the result seems to be right
> 
> --> [ Ij0qma LOGIN [myEmail@outlook.com](mailto:myEmail@outlook.com) myPassword]
> 
> can you check the problem?

I solved this by getting an older version of go-sasl repo, where xoauth2 was still implemented, and copying the file with the xoauth2 login method.

You'll need to retrieve the microsoft graph token for this to work.

```
if imapUser.imap_type == "o365" {
  auth := sasl.NewXoauth2Client(imapUser.username, imapUser.msToken)
  err := c.Authenticate(auth)
    if err != nil {
      //error
    }
}
```

**Comment by FredericoBender** [comment]
Did anything change recently? I had to switch to [https://github.com/BrianLeishman/go-imap](url)
as it still works normally. Is Xoauth2 a new requirement going forward?

The following code snippet using this other repository works fine!


`
package main

import (
	"github.com/BrianLeishman/go-imap"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	imap.Verbose = true
	imap.RetryCount = 3
	im, err := imap.New("YOUR_EMAIL@outlook.com.br", "Password here", "outlook.office365.com", 993)
	check(err)
	defer im.Close()
}

`

**Comment by MattiaLeoni** [comment]
> Did anything change recently? I had to switch to [https://github.com/BrianLeishman/go-imap](url) as it still works normally. Is Xoauth2 a new requirement going forward?

You can check the changes for o365 authentication here: [https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)

**Comment by emersion** [comment]
Closing since this is not a go-imap issue.

**Comment by happyphper** [comment]
![Image](https://github.com/user-attachments/assets/6d34b097-e978-4b5a-92f7-5091e34c207f)

我发现当尝试 3 次 NOOP 时，尝试列出收件箱，一直是 User is authenticated but not connected。但当我尝试 10 次 NOOP 时，他是成功的。
----
I found that when I attempted NOOP 3 times and tried to list the inbox, it kept showing “User is authenticated but not connected.” However, when I attempted NOOP 10 times, it succeeded.
