### ISSUE TITLE
When running concurrently -> dial tcp  i/o timeout

### ISSUE THREAD

**Issue by cubscoutsday** [emersion/go-imap#489]
`client.DialWithDialerTLS(&net.Dialer{Timeout: time.Second * time.Duration(10)}, host, &tls.Config{InsecureSkipVerify: true})`
when running concurrently in goroutines results to error dial tcp  i/o timeout even when server is up .
How can i  fix it

**Comment by emersion** [comment]
This doesn't sound like a go-imap issue, sorry.
