### ISSUE TITLE
Moved messages remain in the original mailbox

### ISSUE THREAD

**Issue by nelbermora** [emersion/go-imap#493]
Hello, I'm implementing an Imap Server. I am trying to develop the MoveMessages method (move a message from one folder to another) with go-imap (Server). I create a copy of the message in the destination, then I mark the current message to delete it using flags, finally I execute the Expunge method. But the message is not deleted in the original mbox. The expunge method deletes the mail temporarily, when I need to move another message, I see again in the original mbox, all the initial mails. So the email is created in the destination but is not deleted from de initial mbox.

```
func (mbox *Mailbox) MoveMessages(uid bool, seqset *imap.SeqSet, destName string) error {
	err := mbox.CopyMessages(uid, seqset, destName)
	if err != nil {
		return err
	}

	err = mbox.UpdateMessagesFlags(uid, seqset, "+FLAGS", []string{imap.DeletedFlag})
	if err != nil {
		return err
	}

	err = mbox.Expunge()
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by emersion** [comment]
This is a weird way to implement MOVE. Backends aren't supposed to fall back to COPY+STORE+EXPUNGE like clients do.

Anyways, each of these functions are the backend's, so up to the backend to implement correctly.

**Comment by nelbermora** [comment]
Ok, but expunge function is not working properly, mailbox is not expunged

**Comment by emersion** [comment]
The expunge function is your function with your own code.

**Comment by nelbermora** [comment]
Yes you are right,  but if I use the "backend memory" library, the error persists. And that function is not my code.

**Comment by nelbermora** [comment]
Here 
https://github.com/emersion/go-imap/tree/master/backend/memory

Even using this code,  the expunge function is not working properly
