### ISSUE TITLE
How do images appear in the email content?

### ISSUE THREAD

**Issue by Binzaga** [emersion/go-imap#494]
The html of the email content I got is as follows:
<div class="__aliyun_email_body_block"><div  style="line-height:1.7;font-family:Tahoma,Arial,STHeiti,SimSun;font-size:14.0px;color:#000000;"><div  style="clear:both;"><br ></div><div  style="clear:both;">test<br ><img  height="439" src="cid:__aliyun167869746473819901" width="697" style="vertical-align:bottom;"><br >test again</div></div></div>

How can I display this picture (cid:__aliyun167869746473819901)？

**Comment by emersion** [comment]
Sorry, this issue tracker is not for questions. Moreover this isn't even a question about the library, it's a question about email in general.

**Comment by Binzaga** [comment]
html is as follows:
`<div class="__aliyun_email_body_block"><div  style="line-height:1.7;font-family:Tahoma,Arial,STHeiti,SimSun;font-size:14.0px;color:#000000;"><div  style="clear:both;"><br ></div><div  style="clear:both;">test<br ><img  height="439" src="cid:__aliyun167869746473819901" width="697" style="vertical-align:bottom;"><br >test again</div></div></div>`

**Comment by Binzaga** [comment]
What method should I use to get the binary stream of this file?
