### ISSUE TITLE
Give Mailbox Attr without Create Special Use

### ISSUE THREAD

**Issue by Omkar-Waingankar** [emersion/go-imap#519]
When trying to create a Trash folder with an imap.MailboxAttrTrash attribute, I get the following error: `panic: imap: BAD Expected end-of-line, found more character(s): ( Command should be '<tag> CREATE <mailbox>`. When I create the Mailbox without specifying any CreateOptions, everything works perfectly (but of course the mailbox doesn't have the attribute).

Here is the code snippet that I am using, and I am using the greenmail docker image as my local IMAP emulator:
```
func createTrash(user string) {
	// Connect to IMAP server
	conn, err := tls.Dial("tcp", "localhost:3993", &tls.Config{
		NextProtos:         []string{"imap"},
		InsecureSkipVerify: true, //nolint:gosec // Localhost, no cert
	})
	if err != nil {
		panic(err)
	}

	c := imapclient.New(conn, nil)

	// Login
	if err = c.Login(user, user).Wait(); err != nil {
		panic(err)
	}

	// Create trash folder
	err = c.Create("Trash", &imap.CreateOptions{
		SpecialUse: []imap.MailboxAttr{
			imap.MailboxAttrTrash,
		},
	}).Wait()
	if err != nil {
		panic(err)
	}

	// Log out
	err = c.Logout().Wait()
	if err != nil {
		panic(err)
	}
}
```

**Comment by emersion** [comment]
Does your server support `CREATE-SPECIAL-USE`? The docs for this field mention that this capability is required.

**Comment by Omkar-Waingankar** [comment]
My apologies, you are correct - I misunderstood that comment. If you have any thoughts for how to give a Mailbox this attribute without the Create Special Use capability, I'm all ears.

**Comment by emersion** [comment]
I don't know any way of doing this without the ext.
