### ISSUE TITLE
STARTTLS Deadlock

### ISSUE THREAD

**Issue by oogali** [emersion/go-imap#521]
In the v2 branch (1ff67fe) of the project, I encountered a bug where the client hangs during TLS negotiation. After investigating, I discovered that the [issue is caused by an attempt to invalidate the original capability set which triggers a new request for capabilities (attempting to send the `CAPABILITY` command)](https://github.com/emersion/go-imap/blob/v2/imapclient/client.go#L669) while the `STARTTLS` command is still in progress. This creates a deadlock, as `beginCommand` cannot acquire the already-held mutex.

To resolve this in my local environment, I modified the code to not execute the invalidation attempt when encountering a `startTLSCommand` struct, which prevented the hang. Since the server (Dovecot) sends a new set of capabilities upon a successful login, I do not believe this modification will cause any loss of functionality.

Local changes:
```
diff --git a/imapclient/client.go b/imapclient/client.go
index 0387c74..b488595 100644
--- a/imapclient/client.go
+++ b/imapclient/client.go
@@ -666,7 +666,7 @@ func (c *Client) readResponseTagged(tag, typ string) (*startTLSCommand, error) {

        if cmdErr == nil && code != "CAPABILITY" {
                switch cmd.(type) {
-               case *startTLSCommand, *loginCommand, *authenticateCommand, *unauthenticateCommand:
+               case *loginCommand, *authenticateCommand, *unauthenticateCommand:
                        // These commands invalidate the capabilities
                        c.setCaps(nil)
                }
```

Capabilities re-advertised upon successful login:
```
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot ready.
T1 STARTTLS
T1 OK Begin TLS negotiation now.
T2 LOGIN "testuser" "testpass"
T2 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY LITERAL+ NOTIFY SPECIAL-USE] Logged in

```

My code triggering the issue:
```
	capabilities := client.Caps()
	if capabilities.Has(imap.CapStartTLS) {
		serverName := strings.SplitN(c.hostname, ":", 2)[0]
		tlscfg := tls.Config{
			ServerName: serverName,
			NextProtos: []string{"imap"},
		}

		if err := client.StartTLS(&tlscfg); err != nil {
			conn.Close()
			return errors.Wrap(err, "could not initiate tls session")
		}
	}
```

**Comment by emersion** [comment]
Hmmm. A regression likely caused by https://github.com/emersion/go-imap/commit/b723ce41085f34edd0dc6f590931a8e56260d295.

Maybe the `Capability` call can be started in a new goroutine to avoid this. We don't care about synchronizing the command marshalling here.

**Comment by emersion** [comment]
Hrm, we can't do this sadly, since we store the `*CapabilityCommand` so that we can wait for it while pending…
