### ISSUE TITLE
How to use IDLE in v2 version?

### ISSUE THREAD

**Issue by peter-teslenko** [emersion/go-imap#527]
I send IDLE command like this
```
	if _, err := a.imapClient.Select(reportsMbox, &imap.SelectOptions{ReadOnly: false}).Wait(); err != nil {
		return errors.New(fmt.Sprintf("failed to select %s: %v", reportsMbox, err))
	}

	idleCmd, err := a.imapClient.Idle()
	if err != nil {
		return err
	}
```
But what I should do next? a.imapClient.Wait() says "imapclient: IdleCommand.Close must be called before Wait"
but  a.imapClient.Close() sends DONE and exits from IDLE mode. How can I receive updates?

**Comment by emersion** [comment]
This bug tracker is not for questions.
