### ISSUE TITLE
v2: `Envelope.Subject` sometimes gets `=?` encoded data

### ISSUE THREAD

**Issue by Vovan-VE** [emersion/go-imap#528]
2.0.0-alpha.4

Using `imapclient` to fetch messages, `Envelope.Subject` sometimes returns encoded subject like:
```
=?koi8-r?B?UkU6IPrE0sHX09TX1crUxS4=?=
```
instead of `RE: Здравствуйте.` in this example. Exact conditions are unknown yet, unfortunely, because it's very rare.

The same messages in the same app instance parsed with `github.com/emersion/go-message/mail` `CreateReader()...` have correct results. Charsets are imported:
```go
import _ "github.com/emersion/go-message/charset"
```

**Comment by emersion** [comment]
Do you also set `imapclient.Options.WordDecoder` to `&mime.WordDecoder{CharsetReader: message.CharsetReader}`?

This is probably something which should be added to the docs or the wiki.

**Comment by Vovan-VE** [comment]
No, didn't discover it yet. I'll try, thanks.

**Comment by Vovan-VE** [comment]
It looks like `WordDecoder` helped. Thanks!
