### ISSUE TITLE
DialTLS with self-signed certificate

### ISSUE THREAD

**Issue by djdejawu** [emersion/go-imap#552]
github.com/emersion/go-imap/v2 v2.0.0-alpha.7

`c, err := imapclient.DialTLS(Hostname, options)`
023/10/27 20:16:33 tls: failed to verify certificate: x509: certificate signed by unknown authority
exit status 1

How to dialTLS with `&tls.Config{InsecureSkipVerify: true}`?

**Comment by emersion** [comment]
You need to create the `net.Conn` manually then call `NewClient`.

**Comment by djdejawu** [comment]
What??? Why you don't apply the same as in v1 version?
