### ISSUE TITLE
Trouble Implementing Proxies in IMAP Client

### ISSUE THREAD

**Issue by tcortega** [emersion/go-imap#558]
Hello,

I am encountering difficulties in configuring proxies (both SOCKS4 and HTTP types) with my IMAP client. I have thoroughly reviewed Issue #201 but still face challenges in getting the proxies to work as expected.

Currently, I'm using the proxy settings configured on Windows as a workaround. However, I am keen on integrating proxy settings directly into my code. I would greatly appreciate if someone could provide code snippets or detailed instructions to assist in this matter.

Thank you in advance for your help.

**Comment by emersion** [comment]
Sorry, this issue tracker is not for questions.

**Comment by tcortega** [comment]
> Sorry, this issue tracker is not for questions.

Is there anywhere to ask questions? There are no docs regarding this and there are no discussion tabs here on github for the repo.

**Comment by emersion** [comment]
The IRC channel is the place to ask questions.

**Comment by tcortega** [comment]
> The IRC channel is the place to ask questions.

And where can I find the IRC channel?

**Comment by emersion** [comment]
#emersion on Libera Chat. It's linked when you click "new issue", then "ask a question".
