### ISSUE TITLE
NumUnseen is used instead of NumDeleted

### ISSUE THREAD

**Issue by kaz-as** [emersion/go-imap#564]
Suppose that [here](../tree/v2/imapserver/imapmemserver/mailbox.go#L84) data.NumDeleted should be set, not data.NumUnseen.

**Comment by emersion** [comment]
Indeed, good catch! Would you be willing to send a patch to fix this?

**Comment by kaz-as** [comment]
Thank you! Here is a [patch](https://github.com/emersion/go-imap/files/13613504/fix_NumUnseen_instead_of_NumDeleted.patch)

**Comment by emersion** [comment]
Would you mind sending this as a pull request?

**Comment by kaz-as** [comment]
Ok, [pull request](../pull/566)
