### ISSUE TITLE
v2 client: Envelope.MessageID returns raw value?

### ISSUE THREAD

**Issue by Vovan-VE** [emersion/go-imap#565]
Hello again!

`v2.0.0-alpha.7`. Both of `Envelope.MessageID` and `Envelope.InReplyTo` on its own de-facto produced the following variations of output:
- `<AAA@BBB>`
- `<AAA>`
- `AAA`
- `Aaa/BbB+cCC` (its base64 without `=` padding)
- `\t<AAA@BBB>` (`\t` = TAB char)
- `<AAA@BBB>>` (extra `>` in the end is probably as it was given in inut stream).

Unfortunely, I have no info about what was given as input in every case above.
The TAB `\t` characret, the extra `>` after `<...>` looks strange, like the whole value is a raw header value. I have no ideas how `Envelope.MessageID` and `Envelope.InReplyTo` should to work by design, so sorry if I'm wrong.
But maybe you will see the problem here and decide what to do with this.

**Comment by emersion** [comment]
Yeah, we don't do anything special with these fields, we just forward what we get from the server. Note that the field may also include comments, such as `<foo@example.org> (this is a comment)`.
