### ISSUE TITLE
Fetching a partial BODY returns an error

### ISSUE THREAD

**Issue by hartshorne** [emersion/go-imap#58]
When fetching `BODY.PEEK[]<0.8>`, the client fails when parsing the server's `BODY[]<0> {8}` response.

### server.go:

	package main

	import (
		"github.com/emersion/go-imap/backend/memory"
		"github.com/emersion/go-imap/server"
		"log"
	)

	func main() {
		bkd := memory.New()
		s := server.New(bkd)
		s.Addr = ":3000"
		s.AllowInsecureAuth = true
		log.Println("Starting IMAP server at localhost:3000")
		if err := s.ListenAndServe(); err != nil {
			log.Fatal(err)
		}
	}

### client.go:

	package main

	import (
		"github.com/emersion/go-imap"
		"github.com/emersion/go-imap/client"
		"log"
		"os"
	)

	func main() {
		c, _ := client.Dial("localhost:3000")
		c.SetDebug(os.Stderr)
		c.Login("username", "password")
		c.Select("INBOX", false)
		seqset, _ := imap.NewSeqSet("1:*")
		messages := make(chan *imap.Message)
		done := make(chan error, 1)
		go func() {
			done <- c.Fetch(seqset, []string{"BODY.PEEK[]<0.8>"}, messages)
		}()
		for msg := range messages {
			log.Println("MESSAGE: %v", msg) // expected: a message
		}
		if err := <-done; err != nil {
			log.Fatal(err) // got: Invalid body section name: partial must have two fields
		}
	}

### stderr:

	Kj3K0Q LOGIN username password
	5SektA SELECT INBOX
	* FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
	* OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
	* 1 EXISTS
	* 0 RECENT
	* OK [UNSEEN 0] 
	* OK [UIDNEXT 7] Predicted next UID
	* OK [UIDVALIDITY 1] UIDs valid
	5SektA OK [READ-WRITE] SELECT completed
	SwWRDQ FETCH 1:* (BODY.PEEK[]<0.8>)
	* 1 FETCH (BODY[]<0> {8}
	From: co)
	<0>
	SwWRDQ OK FETCH completed
	2016/09/23 21:44:08 Invalid body section name: partial must have two fields
	exit status 1

**Comment by emersion** [comment]
Thanks for reporting this bug! Fixed and added a test for it.
