### ISSUE TITLE
v2 Invokes Client.conn.Close multiple times producing errors

### ISSUE THREAD

**Issue by resolutecake** [emersion/go-imap#582]
Having multiple threads, failing commands and direct CLOSE causes Client.conn.Close to be invoked multiple times

in Go, io.Writer can only be closed once

The impact is mysterious errors in the code, and peculiar get-arounds not addressing the root cause

A known error to be returned is net.ErrClosed

**Comment by emersion** [comment]
I don't think invoking Close multiple times is an issue. It'll return net.ErrClosed, and we just need to handle that, like #563 does.
