### ISSUE TITLE
v1 branch overwritten?

### ISSUE THREAD

**Issue by drjeffnorris** [emersion/go-imap#588]
Hi - I've really appreciated go-imap!

Not sure exactly what happened, but https://github.com/emersion/go-imap/tree/v1, which used to point to the v1 branch and showed the v1 README, now just shows the v2 README.  Also, v1 wiki documents like https://github.com/emersion/go-imap/wiki/Fetching-messages#fetching-the-whole-message-body are now inaccessible.

**Comment by foxcpp** [comment]
Looks like some GitHub glitch. v1 README is clearly here: https://github.com/emersion/go-imap/blob/v1/README.md
![изображение](https://github.com/emersion/go-imap/assets/37885127/1937af05-9639-43b8-88de-68efd3ed5358)

Though not correctly displayed on github.com/emersion/go-imap/tree/v1:
![изображение](https://github.com/emersion/go-imap/assets/37885127/b5ea3a2f-dde0-4861-994d-026222dfbc2c)

**Comment by emersion** [comment]
Yeah, v1 hasn't been touched AFAIK.
