### ISSUE TITLE
Set timeout for Dial()

### ISSUE THREAD

**Issue by 64chevy** [emersion/go-imap#597]
Sometimes the connection stays for infinite time and doesn't give any error or timeout. Is there no way to set connection timeout for non-TLS dialer? 

Not sure how client.Timeout can help because its set later after the dialer is connected.

**Comment by emersion** [comment]
Eh right, completely forgot about this, a9d7ec54a300 should help.

**Comment by staz9** [comment]
Thank you. I still use the v1, is it not possible to implement it in that as well?
