### ISSUE TITLE
oauth2 server

### ISSUE THREAD

**Issue by aep** [emersion/go-imap#625]
first of all thanks for maintaining this. the server seems to work out of the box with roundcube and thunderbird so far.

the server doesnt support oauth2, but i'm not sure if its worth looking into contributing it.
Maybe you have opinions on that. The client seems to be done.

so far it looks like roundcube can do it , dovecot can do it, but thunderbird cant.

**Comment by emersion** [comment]
To add support for the OAUTHBEARER SASL mechanism, library users can implement [`SessionSASL`](https://pkg.go.dev/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapserver#SessionSASL).

Note that clients will need more work unrelated to go-imap to be able to use OAuth when connecting to the server. Specifically, most clients supporting OAuth will need the specific OAuth server to be configured (server URL, client ID, etc).
