### ISSUE TITLE
【outlook】从 2024 年 9 月 16 日起，如果应用使用的登录技术安全性较低，则将无法再访问你的电子邮件。

### ISSUE THREAD

**Issue by easylolicon** [emersion/go-imap#628]
确保你信息的安全是 Microsoft 的首要任务。为了确保你的帐户安全无忧，Microsoft 将不再支持使用第三方电子邮件和日历应用，这些应用要求仅使用 Microsoft 帐户用户名和密码登录。你需要使用支持 Microsoft 新式验证方法的邮件或日历应用，以增强安全性。如果你不采取任何措施，从 2024 年 9 月 16 日起，第三方电子邮件应用将无法再访问你的 Outlook.com、Hotmail 或 Live.com 电子邮件地址。

需要采取什么措施？

如果你收到这封电子邮件，则表明你当前使用的电子邮件或日历应用是采用不太安全的身份验证方法来连接到你的 Outlook.com 电子邮件帐户。你需要将第三方邮件和日历应用升级到支持新式验证方法的版本。

Microsoft 提供了适用于电脑、Mac、iOS 和 Android 设备的免费 Outlook 版本，你可以轻松下载这些版本并将其连接到你的电子邮件帐户。使用更新后的 Outlook 应用程序版本可确保你以最安全的方式进行连接。

如何设置 Gmail、Apple Mail 或其他第三方邮件应用程序？

许多非 Microsoft 应用程序在使用新式验证方法连接到 Outlook.com 电子邮件帐户方面都有自己的步骤。如需帮助，请参阅“现在需要使用新式验证方法才能继续在非 Microsoft 电子邮件应用中同步 Outlook 电子邮件”一文。但是，你可能需要与这些应用程序的创建者联系以获取说明。在许多情况下，只需删除帐户并将其重新添加到该应用程序的最新版本，即可将帐户配置为使用新式验证方法。

**Comment by emersion** [comment]
Sorry, issues need to be written in English.
