### ISSUE TITLE
[Feature Request] Add a in-memory session/server for integration/regression testing

### ISSUE THREAD

**Issue by ar-sematell** [emersion/go-imap#631]
I'm currently implementing integration tests using the IMAP client while transforming the email data to a domain object.
I have a set of testdata email `.eml` files, that are easily used for testing edge cases and regressions.

I currently had to create a copy of the private `message` struct from the `imapmemserver`, add the file content inside `buf` to simulate this behavior.

I think it would be really nice to have a test server capable of loading `.eml` files for testing purposes.

Thanks for your work!

**Comment by emersion** [comment]
It's already possible to add messages to imapmemserver. See e.g. client tests: https://github.com/emersion/go-imap/blob/1299a86d6644be9fde8c1d3dcb0977f7e27eb44a/imapclient/client_test.go#L168
