### ISSUE TITLE
[V2] Got empty email ID list by c.UIDSearch() or c.Search()

### ISSUE THREAD

**Issue by wms15391** [emersion/go-imap#632]
Hi, I need to search emails that not saved.
I can get email info with imap.SeqSetNum(1) and c.Fetch, so connect successful
No err but  c.UIDSearch() or c.Search() return [].
By other way I can get them like php-imap, I found UID of this mailbox so large such as 1712632320

**Comment by emersion** [comment]
Will need more details here, such as a link to the code and network logs.

**Comment by wms15391** [comment]
I set ReturnMin,ReturnMax,ReturnAll,ReturnCount of &imap.SearchOptions false.
Now it work, thanks
