### ISSUE TITLE
Aliyun mail uses UidSearch() or Search() method reporting "invalid command or parameters"

### ISSUE THREAD

**Issue by xuecangqiuye** [emersion/go-imap#638]
I'm using v2 version.
I saw the same problem at #412, but it seems that it doesn't have a solution for this problem.
Can you tell that if this problem is caused by Aliyun mail server or by my mistaken usage?

![image](https://github.com/user-attachments/assets/40cb4e78-9d92-46ef-8956-11c459f07aa8)

**Comment by emersion** [comment]
Can you obtain debug logs?

**Comment by xuecangqiuye** [comment]
Thanks for your reply!
Sorry for taking so long, here is the log

```
* OK AliYun IMAP Server Ready
T2 CAPABILITY
T1 OK LOGIN completed
T3 CAPABILITY
T4 SELECT INBOX
* CAPABILITY IMAP4rev1 IDLE XLIST UIDPLUS ID SASL-IR AUTH=XOAUTH AUTH=XOAUTH2 AUTH=EXTERNAL
T2 OK CAPABILITY completed
* CAPABILITY IMAP4rev1 IDLE XLIST UIDPLUS ID SASL-IR AUTH=XOAUTH AUTH=XOAUTH2 AUTH=EXTERNAL
T3 OK CAPABILITY completed
* 33 EXISTS
* 0 RECENT
* OK [UNSEEN 32]
* OK [UIDNEXT 75] Predicted next UID.
* OK [UIDVALIDITY 2] UIDs valid.
* FLAGS (\Answered \Seen \Deleted \Draft \Flagged)
* OK [PERMANENTFLAGS (\Answered \Seen \Deleted \Draft \Flagged)] Limited.
T4 OK [READ-WRITE] SELECT completed
T5 UID SEARCH (SUBJECT "test134")
T5 BAD invalid command or parameters

```

**Comment by emersion** [comment]
Hm. That command looks correct to me. I'm not sure why the server refuses it.

**Comment by xuecangqiuye** [comment]
> Hm. That command looks correct to me. I'm not sure why the server refuses it.

So it may be a server problem.
Thanks a lot!

**Comment by Android-KitKat** [comment]
> So it may be a server problem.

It was indeed a server issue.
I found some relevant information to help anyone who encounters the same situation in the future.

[阿里邮箱IMAP场景示例：获取邮件信息（SELECT、SEARCH和FETCH）-阿里云帮助中心](https://help.aliyun.com/document_detail/2857997.html#310f840abd8tk)
