### ISSUE TITLE
FETCH command Close() panics: FetchItemDataBodySection.Literal is nil in discard()

### ISSUE THREAD

**Issue by Vovan-VE** [emersion/go-imap#644]
`v2.0.0-beta.3`, Go 1.20

In some unknown edge case, when `FETCH` command's `Close()` is called, the `FetchItemDataBodySection.discard()` has `Literal` field set to `nil`:

https://github.com/emersion/go-imap/blob/ee36cf4658d87d2230b6bde0b0c2177b6b4eff96/imapclient/fetch.go#L323-L325

Crash
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4b4639]

goroutine 109 [running]:
io.discard.ReadFrom({}, {0x0, 0x0})
        io/io.go:651 +0x59
io.copyBuffer({0x19c84e0, 0x21f4120}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        io/io.go:413 +0x14b
io.Copy(...)
        io/io.go:386
github.com/emersion/go-imap/v2/imapclient.FetchItemDataBodySection.discard(...)
        github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:324
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).Next(0xc001a0d640)
        github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:253 +0x3f
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).discard(...)
        github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:263
github.com/emersion/go-imap/v2/imapclient.(*FetchCommand).Next(0xc001cd9480)
        github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:195 +0x87
github.com/emersion/go-imap/v2/imapclient.(*FetchCommand).Close(0xc001cd9480)
        github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:206 +0x29
...
```

`FetchOptions`:
```go
cmd := client.Fetch(wantedUids, &imap.FetchOptions{
	UID:      true,
	Envelope: true,
	Flags:    true,
	BodySection: []*imap.FetchItemBodySection{{
		Peek: true,
	}},
})
defer func() {
	if err := cmd.Close(); err != nil {
		log.Printf("FETCH command Close error: %v", err)
	}
}()
...
```

**Comment by emersion** [comment]
Yeah, `NIL` is valid in the RFC grammar. It seems semantically different from the empty string (invalid body section vs. valid empty body section). Probably we should document that the field can be nil and add nil checks?

**Comment by Vovan-VE** [comment]
@emersion , Oh, I don't know all details. You are creator here :muscle: .

**Comment by dmitriblov** [comment]
Hi salut, I'm still facing the same issue.
Here is my error below.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xc8054]

goroutine 2214 [running]:
io.discard.ReadFrom({}, {0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:666 +0x54
io.copyBuffer({0x355de0, 0x61d100}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
github.com/emersion/go-imap/v2/imapclient.FetchItemDataBodySection.discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:324
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).Next(0xc0000bd4a0)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:253 +0x46
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:263
created by github.com/emersion/go-imap/v2/imapclient.(*Client).handleFetch.func1 in goroutine 5
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:498 +0x178
exit status 2`

I'm trying to return FetchItemDataBodySection inside a Goroutines. I already checked if body_section.Literal is nil but I'm still getting the same error.

`literal := body_section.Literal
if literal == nil {
return
}`

Here is my code below

`all_seq_nums := result.AllSeqNums()
count := len(all_seq_nums)
if count > 0 {
  thread, _ := strconv.Atoi(thread)
  semaphore := make(chan struct{}, thread)
  var wg sync.WaitGroup

  for seq_num := uint32(0); seq_num < uint32(count) ; seq_num++ {
    wg.Add(1)
    semaphore <- struct{}{}
    go func(seq_num uint32) {
      defer wg.Done()
      defer func() { <-semaphore }()

      seq_set := imap.SeqSetNum(all_seq_nums[seq_num])
      fetch_options := &imap.FetchOptions{
        BodySection: []*imap.FetchItemBodySection{{}},
      }
      fetch_cmd := client.Fetch(seq_set, fetch_options)
      if fetch_cmd == nil {
        return
      }

      msg := fetch_cmd.Next()
      if msg == nil {
        fmt.Print("\n[-]  Message not found, skipping...")
        return
      }

      var body_section imapclient.FetchItemDataBodySection
      ok := false
      for {
        item := msg.Next()
        if item == nil {
          break
        }
        body_section, ok = item.(imapclient.FetchItemDataBodySection)
        if ok {
          break
        }
      }

      if ok {
        literal := body_section.Literal
        if literal == nil {
          return
        }

        mr, err := mail.CreateReader(literal)
        if err == nil {
          for {
            p, err := mr.NextPart()
            if err == io.EOF {
              break
            }

            switch p.Header.(type) {
            case *mail.InlineHeader:
              b, _ := io.ReadAll(p.Body)
              parse_message(string(b), imap_credential, mailbox_folder, all_seq_nums[seq_num])
            }
          }
        }
      }
      
      fetch_cmd.Close()
    }(seq_num)
  }

  wg.Wait()`

**Comment by ghost** [comment]
Hi salut, I'm still facing the same issue.
Here is my error below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xc8054]

goroutine 2214 [running]:
io.discard.ReadFrom({}, {0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:666 +0x54
io.copyBuffer({0x355de0, 0x61d100}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
github.com/emersion/go-imap/v2/imapclient.FetchItemDataBodySection.discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:324
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).Next(0xc0000bd4a0)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:253 +0x46
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:263
created by github.com/emersion/go-imap/v2/imapclient.(*Client).handleFetch.func1 in goroutine 5
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:498 +0x178
exit status 2
```

I'm trying to return FetchItemDataBodySection inside a Goroutines. I already checked if body_section.Literal is nil but I'm still getting the same error.

```
literal := body_section.Literal
if literal == nil {
return
}
```

Here is my code below

```
all_seq_nums := result.AllSeqNums()
count := len(all_seq_nums)
if count > 0 {
  thread, _ := strconv.Atoi(thread)
  semaphore := make(chan struct{}, thread)
  var wg sync.WaitGroup

  for seq_num := uint32(0); seq_num < uint32(count) ; seq_num++ {
    wg.Add(1)
    semaphore <- struct{}{}
    go func(seq_num uint32) {
      defer wg.Done()
      defer func() { <-semaphore }()

      seq_set := imap.SeqSetNum(all_seq_nums[seq_num])
      fetch_options := &imap.FetchOptions{
        BodySection: []*imap.FetchItemBodySection{{}},
      }
      fetch_cmd := client.Fetch(seq_set, fetch_options)
      if fetch_cmd == nil {
        return
      }

      msg := fetch_cmd.Next()
      if msg == nil {
        fmt.Print("\n[-]  Message not found, skipping...")
        return
      }

      var body_section imapclient.FetchItemDataBodySection
      ok := false
      for {
        item := msg.Next()
        if item == nil {
          break
        }
        body_section, ok = item.(imapclient.FetchItemDataBodySection)
        if ok {
          break
        }
      }

      if ok {
        literal := body_section.Literal
        if literal == nil {
          return
        }

        mr, err := mail.CreateReader(literal)
        if err == nil {
          for {
            p, err := mr.NextPart()
            if err == io.EOF {
              break
            }

            switch p.Header.(type) {
            case *mail.InlineHeader:
              b, _ := io.ReadAll(p.Body)
              parse_message(string(b), imap_credential, mailbox_folder, all_seq_nums[seq_num])
            }
          }
        }
      }
      
      fetch_cmd.Close()
    }(seq_num)
  }

  wg.Wait()
}
```

**Comment by ghost** [comment]
What could be the possible issue?

**Comment by emersion** [comment]
Would you be willing to send a patch to add a nil check?

**Comment by ghost** [comment]
You mean this?

```
literal := body_section.Literal
if literal == nil {
  return
}
```
