### ISSUE TITLE
v2：When I use imapclient to add a flag to an email, the program remains in a waiting state without releasing

### ISSUE THREAD

**Issue by xiaoquanidea** [emersion/go-imap#647]
I also asked a question on irc, but after waiting for a long time, no one replied.

When I use imapclient to add a flag to an email, the program remains in a waiting state without releasing. In the webmail interface, the flag only appears about 15 seconds later, and even after the flag is successfully applied, the store method still remains in a waiting state.

![image](https://github.com/user-attachments/assets/38b1c97a-c9f3-441c-ab02-73b9a4c086df)

**Comment by xiaoquanidea** [comment]
I debugged and took a look，It seems that because "cmd.msgs" chan has not received the message.
![image](https://github.com/user-attachments/assets/accdfc79-ec9a-4ae1-81fc-b27d9a17457d)

**Comment by nyufeng** [comment]
Hi. Can you tell me the question's resovle ?

**Comment by xiaoquanidea** [comment]
> Hi. Can you tell me the question's resovle ?你好。你能告诉我问题的解决方案吗？



> Hi. Can you tell me the question's resovle ?

command使用完要及时释放，如果拉取的command不释放，又在程序里面使用imap client调用，框架内部使用队列执行命令，如果上一个命令不释放，会一直占用，无法执行后面的命令。
