### ISSUE TITLE
CAPABILITY Interferes with LOGIN Command

### ISSUE THREAD

**Issue by qjebbs** [emersion/go-imap#651]
Backgroud:

1. When the imapclient starts, it sends a CAPABILITY command to the server if the server greets it without CAPABILITY. The command is executed in another goroutine.
2. Some server (`imaphz.qiye.163.com` here) seems to ignore new commands when the current command is still being processed.

UPDATE:

`imaphz.qiye.163.com` is not the one to blame, the [RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501#section-5.5) specification says:

```
Therefore, 
if the client sends any command other than FETCH, STORE, or SEARCH, it
MUST wait for the completion result response before sending a command
with message sequence numbers.
```

Consider the following code:

```go
// conn is a net.Conn to imaphz.qiye.163.com
c = imapclient.New(conn, &imapclient.Options{
    DebugWriter: os.Stdout,
})
c.WaitGreeting()
err := c.Login(userName, password).Wait()
if  err != nil {
	return nil, fmt.Errorf("login %q: %w", userName, err)
}
```

The `LOGIN` and  background spawned `CAPABILITY` are executed in different goroutines. The order of the commands is not guaranteed. So I see a random failure when initializing the imapclient.

1. If the `CAPABILITY` command is executed first, and the `LOGIN` command is executed before the `CAPABILITY` command finishes, the server seems to ignore the `LOGIN` command. The command receives nothing and reports an unexpected EOF error after 60 seconds.

    ```
    * OK IMAP4 ready
    T1 CAPABILITY
    T2 LOGIN "xxx@xxx.com" "xxxx"
    * CAPABILITY IMAP4rev1 XAPPLEPUSHSERVICE XLIST SPECIAL-USE AUTH=PLAIN ID
    T1 OK completed
    --- FAIL: TestIMAPLogin (60.13s)
        imap_test.go:57: login "xxx@xxx.com": unexpected EOF
    FAIL
    ```

1. If the `LOGIN` command happens to be executed first, the server will respond. (`CAPABILITY` command is ignored until timeout. Though the client initialized with success)

    ```
    * OK IMAP4 ready
    T1 LOGIN "xxx@xxx.com" "xxxx"
    T2 CAPABILITY
    T1 NO ERR.LOGIN.PASSERR
    T3 LOGOUT
    --- FAIL: TestIMAPLogin (0.20s)
        imap_test.go:57: login "xxx@xxx.com": imap: NO ERR.LOGIN.PASSERR
    ```

~~Though It's the server's fault, I can't change the server's behavior. Is there a way to fix this issue? Maybe to lock up imapclient before a background command finishes (not accept new ones)?~~

## Workaround

UPDATE: In theory, there is no workaround to this problem

**Comment by qjebbs** [comment]
The Workaround is not working.

I see another server `imap-n.global-mail.cn` disconnects if client send `CAPABILITY` before `LOGIN`.

Should we move the `c.setCaps(nil)` to somewhere after the `LOGIN` command?

```go
if !c.greetingRecv {
	// ...
	if c.greetingErr == nil && code != "CAPABILITY" {
		c.setCaps(nil) // request initial capabilities
	}
}
```

**Comment by qjebbs** [comment]
~~Realized that it not the client library's responsibility for this issue, and there exits a workaround for this library. Closing...~~

**Comment by qjebbs** [comment]
It turns out `imaphz.qiye.163.com` is the one that complies with the [RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501#section-5.5) specification

```
Therefore, 
if the client sends any command other than FETCH, STORE, or SEARCH, it
MUST wait for the completion result response before sending a command
with message sequence numbers.
```

We need a global lock to wait for the async, background-spawned `CAPABILITY` done.

**Comment by emersion** [comment]
This paragraph only applies to the "selected" state. If the connection isn't in the "selected" state, an untagged EXPUNGE response cannot be sent by the server.

**Comment by qjebbs** [comment]
> This paragraph only applies to the "selected" state. If the connection isn't in the "selected" state, an untagged EXPUNGE response cannot be sent by the server.

Sorry, I didn't read it carefully.

What's your suggestion for the situation when we work with the server like this topic? If global lock is not an option, I would say, make the background spawned CAPABILITY command synchronized and blocked?

**Comment by emersion** [comment]
Does it help to call `c.Caps()` before `c.Login()`?

**Comment by qjebbs** [comment]
> Does it help to call `c.Caps()` before `c.Login()`?

I am afraid it doesn't.

`c.Caps()` is similar to what I so called workaround, by spawning another capability command and waiting. It solves half of the problem, making sure login command not being ignored. 

But if it happens this capability command is ignored, the login will be delayed for ~~60 seconds~~ `respReadTimeout`. Making background capability command synchronized and blocking will solve all the problem.

**Comment by qjebbs** [comment]
sleep 300ms would be a better solution to this sever

**Comment by emersion** [comment]
> c.Caps() is similar to what I so called workaround, by spawning another capability command and waiting.

`Caps()` will not send a new capability command if one is already in progress. `Caps()` is supposed to just wait for the pending command to complete in that case.

**Comment by qjebbs** [comment]
Yes, you're right, I missed the `pendingCapCh`. 

For my situation, my code would be:

```go
c.Caps()
err := c.Login(userName, password).Wait()
```

Then `c.Caps()` and background `c.setCaps()` are in different gorountines. I wonder if the locking of `c.mutex` should cover the whole command spawning of these two functions? 

There are still possibilities to spawn two `CAPABILITY` and one of them timed out:

1. `setCaps()` spawns a CAPABILITY command at `Position A`
2. Before `setCaps()` locks the `c.mutex`, `c.Caps` locks it first, finds `c.pendingCapCh` is nil
3. `Caps()` spawns another CAPABILITY command at `Position B`

Similar for  `Caps()` goes first:

1. `Caps()` spawns a CAPABILITY command at `Position B`
2. `c.setCaps()` has no lock or checking `c.pendingCapCh` before spawning
3.  `c.setCaps()` spawns another CAPABILITY command at `Position A`

```go
func (c *Client) setCaps(caps imap.CapSet) {
	var capCh chan struct{}
	if caps == nil {
		// Position A: spawn CAPABILITY
	}

	c.mutex.Lock()
	c.caps = caps
	c.pendingCapCh = capCh
	c.mutex.Unlock()
}
func (c *Client) Caps() imap.CapSet {
	// ...
	c.mutex.Lock()
	caps := c.caps
	capCh := c.pendingCapCh
	c.mutex.Unlock()
	// ...
	if capCh == nil {
		// Position  B: spawn CAPABILITY
		c.mutex.Lock()
		c.pendingCapCh = capCh
		c.mutex.Unlock()
	}
	// ...
}
```

**Comment by emersion** [comment]
Yes, multiple CAPABILITY commands may be sent, but this is intentional to avoid locking the mutex for a long time (waiting on a network operation when sending the command). It shouldn't be a big deal to send multiple CAPABILITY commands.

**Comment by qjebbs** [comment]
OK. Thanks! It's bearable for me that the `c.Caps()` blocks for a `respReadTimeout` time in rare cases. 
<details>
<summary>
BTW, this code doesn't seem to increase the mutex locking time.
Since `c.Capability()` are all `go func` to another goroutine, waiting response or even the sending the command doesn't contribute to the mutex locking time.
</summary>


```go
func (c *Client) Caps() imap.CapSet {
	if err := c.WaitGreeting(); err != nil {
		return nil
	}

	c.mutex.Lock()
	caps := c.caps
	capCh := c.pendingCapCh

	if caps != nil {
		c.mutex.Unlock()
		return caps
	}

	if capCh == nil {
		capCmd := c.Capability()
		capCh := make(chan struct{})
		go func() {
			capCmd.Wait()
			close(capCh)
		}()
		c.pendingCapCh = capCh
	}
	c.mutex.Unlock()

	timer := time.NewTimer(respReadTimeout)
	defer timer.Stop()
	select {
	case <-timer.C:
		return nil
	case <-capCh:
		// ok
	}

	// TODO: this is racy if caps are reset before we get the reply
	c.mutex.Lock()
	defer c.mutex.Unlock()
	return c.caps
}

func (c *Client) setCaps(caps imap.CapSet) {
	c.mutex.Lock()
	defer c.mutex.Unlock()
	// If the capabilities are being reset, request the updated capabilities
	// from the server
	var capCh chan struct{}
	if caps == nil {
		capCh = make(chan struct{})

		// We need to send the CAPABILITY command in a separate goroutine:
		// setCaps might be called with Client.encMutex locked
		go func() {
			c.Capability().Wait()
			close(capCh)
		}()
	}

	c.caps = caps
	c.pendingCapCh = capCh
}
```
</details>

**Comment by emersion** [comment]
`Capability()` will block when sending the command, and is not in a separate goroutine.

**Comment by qjebbs** [comment]
Sorry, my fault again. The following code should work as expected:

- Never create 2nd `CAPABILITY`
- Not increase the `c.mutex` locking time

```go
c.mutex.Lock()
caps := c.caps
capCh := c.pendingCapCh

if caps != nil {
	c.mutex.Unlock()
	return caps
}

if capCh == nil {
	capCh := make(chan struct{})
	go func() {
		c.Capability().Wait()
		close(capCh)
	}()
	c.pendingCapCh = capCh
}
c.mutex.Unlock()
```
