### ISSUE TITLE
Part.size does no contain real size of attach

### ISSUE THREAD

**Issue by ior308** [emersion/go-imap#660]
Dear,

  is it possibile to get the real size of attach and not MIME code or quote printable size using imap.FetchBodyStructure ?

Thank you.
Regards.

**Comment by emersion** [comment]
Sorry, this issue tracker is not for general questions about IMAP.

**Comment by ior308** [comment]
What do you mean with "general questions about IMAP." ? 

Using imap library and reading Part.size value I got a bad value about attachment size, because MIME code or quote printable.

Where I have to track this kind of error ?

Regards

**Comment by emersion** [comment]
There is no bug here. The body structure contains the encoded size.
