### ISSUE TITLE
use v2  in socks5 or http proxy,but return err:unexpected EOF

### ISSUE THREAD

**Issue by jarvis657** [emersion/go-imap#661]
As mentioned in the subject, I am using v2 and I'm unable to successfully log in through either a SOCKS5 proxy or an HTTP proxy. Here is my code:

	dialer, err := proxy.SOCKS5("tcp", "xxxx:17777", &proxy.Auth{
		User:     "user",
		Password: "xxxx",
	}, proxy.Direct)
	if err != nil {
		fmt.Fprintln(os.Stderr, "can't connect to the proxy:", err)
		os.Exit(1)
	}
	conn, err := dialer.Dial("tcp", emailConfig.EmailImap)
	// Connect to server
        //	//options := &imapclient.Options{
	//	TLSConfig: &tls.Config{InsecureSkipVerify: true},
	//	//DebugWriter: os.Stdout,
	//	//UnilateralDataHandler: nil,
	//	WordDecoder: &mime.WordDecoder{CharsetReader: charset.Reader},
	//}
	//c := imapclient.New(conn, options)  set or not, same error  
        // c, err := imapclient.NewStartTLS(conn, options)    same error  
	c := imapclient.New(conn, nil)
	if err != nil {
		log.Fatal(err)
	}
	if err := c.Login(mailAccount, emailConfig.EmailFromPass).Wait(); err != nil {
		log.Fatalf("failed to login: %v", err) 
	}
	
print : failed to login: unexpected EOF

**Comment by jarvis657** [comment]
github.com/emersion/go-imap/v2 v2.0.0-beta.4
i used

**Comment by jarvis657** [comment]
![image](https://github.com/user-attachments/assets/346b7554-9e93-4c67-9d2c-074232414218)
if i change code like this ,return err:imap: BAD [CLIENTBUG] syntax: unexpected char: 's'

	dialer, _ := proxy.SOCKS5("tcp", "ip:port", &proxy.Auth{
		User:     "user",
		Password: "pass",
	}, &net.Dialer{Timeout: 20 * time.Second, KeepAlive: 30 * time.Second}) // create a socks5 dialer with timeout

	conn, _ := dialer.Dial("tcp", emailConfig.EmailImap) // connect
	conn = tls.Client(conn, &tls.Config{
		InsecureSkipVerify: true,
	}) // use tls
	options := &imapclient.Options{
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
		//DebugWriter: os.Stdout,
		//UnilateralDataHandler: nil,
		WordDecoder: &mime.WordDecoder{CharsetReader: charset.Reader},
	}
	c, err := imapclient.NewStartTLS(conn, options)
	//c, err := imapclient.DialTLS(emailConfig.EmailImap, options)
	if err != nil {
		log.Fatalf("failed to dial %v IMAP server: %v\n", mailAccount, err)
	}
	
The SOCKS5 proxy is functioning correctly because another Go program of ours can call another service through this proxy and run normally.

**Comment by jarvis657** [comment]
> ![image](https://private-user-images.githubusercontent.com/2919226/396365252-346b7554-9e93-4c67-9d2c-074232414218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjM4MzUsIm5iZiI6MTczNDQyMzUzNSwicGF0aCI6Ii8yOTE5MjI2LzM5NjM2NTI1Mi0zNDZiNzU1NC05ZTkzLTRjNjctOWQyYy0wNzQyMzI0MTQyMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDgxODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2RlZmJiYmU2OWE5MGRmMGRmYTFmMjk0NzliYTM5NzY3ZjA4OWVhOTgwZTQ2NDgwNTM4Mzg2MThjZThhNTYxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yht5Ufo01ccoyjMaZgGBudge31BPGGYgr-7AP41XuAs) if i change code like this ,return err:imap: BAD [CLIENTBUG] syntax: unexpected char: 's'
> 
> ```
> dialer, _ := proxy.SOCKS5("tcp", "ip:port", &proxy.Auth{
> 	User:     "user",
> 	Password: "pass",
> }, &net.Dialer{Timeout: 20 * time.Second, KeepAlive: 30 * time.Second}) // create a socks5 dialer with timeout
> 
> conn, _ := dialer.Dial("tcp", emailConfig.EmailImap) // connect
> conn = tls.Client(conn, &tls.Config{
> 	InsecureSkipVerify: true,
> }) // use tls
> options := &imapclient.Options{
> 	TLSConfig: &tls.Config{InsecureSkipVerify: true},
> 	//DebugWriter: os.Stdout,
> 	//UnilateralDataHandler: nil,
> 	WordDecoder: &mime.WordDecoder{CharsetReader: charset.Reader},
> }
> c, err := imapclient.NewStartTLS(conn, options)
> //c, err := imapclient.DialTLS(emailConfig.EmailImap, options)
> if err != nil {
> 	log.Fatalf("failed to dial %v IMAP server: %v\n", mailAccount, err)
> }
> ```
> 
> The SOCKS5 proxy is functioning correctly because another Go program of ours can call another service through this proxy and run normally.



	c, err := imapclient.NewStartTLS(conn, options) chang to c := imapclient.New(conn, options) ok...
	ok....i think ,the api confused~~

**Comment by emersion** [comment]
Seems like this has been resolved, and isn't a go-imap bug in the first place.
