### ISSUE TITLE
go-imap depends on go-sasl, which is not installed by default

### ISSUE THREAD

**Issue by Ch00k** [emersion/go-imap#69]
The example client code, provided in the README, fails with the following error:
```
/Users/ay/.gopath/src/github.com/emersion/go-imap/commands/authenticate.go:11:2: cannot find package "github.com/emersion/go-sasl" in any of:
        /usr/local/Cellar/go/1.7.3/libexec/src/github.com/emersion/go-sasl (from $GOROOT)
        /Users/ay/.gopath/src/github.com/emersion/go-sasl (from $GOPATH)
```
Perhaps a not should be added to the README that `go-sasl` should also be installed.

**Comment by emersion** [comment]
How did you install go-imap? If you have used `go get` the dependency should have also been installed at the same time.

**Comment by Ch00k** [comment]
Not sure if I'm doing something wrong (I'm quite new to Go and its ecosystem). This how I reproduce it:
```
~ 0$ ll $GOPATH
total 0
drwxr-xr-x   2 ay   68 Nov  3 07:57 .
drwxr-xr-x+ 67 ay 2.3K Nov  2 15:02 ..
~ 0$ go get github.com/emersion/go-imap
~ 0$ ll $GOPATH/src/github.com/emersion/
total 0
drwxr-xr-x  3 ay  102 Nov  3 07:57 .
drwxr-xr-x  3 ay  102 Nov  3 07:57 ..
drwxr-xr-x 40 ay 1.4K Nov  3 07:57 go-imap
~ 0$ ll $GOPATH/pkg/darwin_amd64/github.com/emersion/
total 408K
drwxr-xr-x 4 ay  136 Nov  3 07:57 .
drwxr-xr-x 3 ay  102 Nov  3 07:57 ..
drwxr-xr-x 3 ay  102 Nov  3 07:57 go-imap
-rw-r--r-- 1 ay 407K Nov  3 07:57 go-imap.a
~ 0$
```
I don't see `go-sasl` installed.

**Comment by emersion** [comment]
Ahh, you're right, `go get github.com/emersion/go-imap` only downloads dependencies for the `imap` package, not for the `client` and `server` subpackages. So you have to `go get github.com/emersion/go-imap/...` instead. I'll fix the README, thanks for reporting this issue!
