### ISSUE TITLE
Implement IMAP4 non-synchronizing literals

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#7]
~~See https://tools.ietf.org/html/rfc2088~~

**Comment by jstedfast** [comment]
See also: https://tools.ietf.org/html/rfc7888

**Comment by emersion** [comment]
Oh yeah, you're right, the RFC I mentioned has been obsoleted. Thanks :)

**Comment by jstedfast** [comment]
no problem :)

I just implemented LITERAL- last night for my own IMAP library :)

They are so easy to miss!

**Comment by emersion** [comment]
The server side of this has been implemented in https://github.com/emersion/go-imap/pull/258

**Comment by foxcpp** [comment]
It includes LITERAL+ only though.

**Comment by emersion** [comment]
Oh, right. I don't think there's any point in supporting LITERAL-.

**Comment by jstedfast** [comment]
LITERAL- is really meant to be used for not needing to synchronize when sending literals in common cases (e.g. mailbox names, SEARCH expressions, etc) but still having the ability to enforce synchronization during operations like APPEND (at least for messages that have size > 4k or so).

That's how GMail makes use of LITERAL-.

**Comment by emersion** [comment]
The RFC says that APPENDLIMIT should cover the APPEND case.

**Comment by foxcpp** [comment]
>The server side of this has been implemented in #258 

I wonder how client support should look like. Use non-synchronizing literals for small ones (and probably support LITERAL- in the client then)?

**Comment by emersion** [comment]
Maybe we could:

1. Add LITERAL- support
2. Move over the APPENDLIMIT extension to this repo
3. Add LITERAL+ support
