### ISSUE TITLE
Make ErrorLog an interface

### ISSUE THREAD

**Issue by ferhatelmas** [emersion/go-imap#74]
Having `ErrorLog` as an interface would make replacement very easy.

**Comment by emersion** [comment]
You can do this to use a custom logger:
```go
s.ErrorLog = stdlog.New(w, "imap/server: ", 0)
```
Most log libraries expose a function to create an `io.Writer` from a logger.

It would be better to be able to use directly an interface from `log`, but there isn't any. So the only solution would be to define our own interface. Maybe in another repo?

**Comment by ferhatelmas** [comment]
Yes, it's one way but it doesn't satisfy my needs.

I think another repo will be overkill. Client package can provide its interface which is automatically implemented by standard logger (`log.Logger`). 

I can give a try to do implement it this way.

**Comment by emersion** [comment]
Okay, that's fine then. The interface should contain only the bare minimum (maybe only `Print*` functions?). Also, it would be better to define it in the `imap` package as it's also used by the server.

Send me a PR, I'll be happy to merge it!
