### ISSUE TITLE
Client: Only one message returned

### ISSUE THREAD

**Issue by manishrjain** [emersion/go-imap#83]
I've noticed that if you ask for more messages than present in the mailbox, only one message is returned. OTOH, if you ask for lesser messages than present in the mailbox, the number returned is correct.

**Comment by emersion** [comment]
Are you using:
```go
seqset.AddRange(mbox.Messages - n, mbox.Messages)
```
?

If so, you should make sure there's no unsigned in underflow (n >= mbox.Messages). I should probably change the README to warn people about this.

**Comment by manishrjain** [comment]
I see. Looks like the code is using uint32. Can it be switched to using int32 instead? That way, the code can be made a bit more robust to input.

**Comment by emersion** [comment]
IMAP itself uses uint32 for numbers, so it makes sense to use them in the library (so IMAP's MAXINT is the same as the library's one). We could use int64 instead, but I'm not sure about it.

**Comment by manishrjain** [comment]
I think it's best to maintain compatibility between IMAP RFC and this library. So, `uint32` makes sense.

**Comment by emersion** [comment]
Okay. 20f394d07e6bb07495f405d3776cd06e5e30136a updates README to check bounds.
