### ISSUE TITLE
UTF-8 isn't being parsed correctly

### ISSUE THREAD

**Issue by manishrjain** [emersion/go-imap#85]
I see message subjects like these:

```
=?UTF-8?Q?Is_Trump_a_=E2=80=9Cclimate-slayer=E2=80=9D=3F_=C2=BB?=
=?UTF-8?Q?JUST_IN:_PITCHING_LINEUP_FOR_TOMORROW_=F0=9F=8E=89_=F0=9F=8E=89?=
=?UTF-8?Q?DAY_7_=E2=80=A2_16_Days_of_Kanga_Care_Deals!?=
```

Seems like UTF-8 strings aren't being parsed correctly by the client.

**Comment by emersion** [comment]
These are quoted-printable encoded headers. I don't think that it's the job of this library to parse them (ie. it isn't in this RFC, but in the RFC defining RFC822 messages). You can use `mime/quotedprintable`.

There are many RFC822 message parsing and formatting functions that could be useful for IMAP, SMTP and other protocols (for instance, decoding properly message encoding + charset). I already have a subpackage that contains some of these functions: https://github.com/emersion/go-pgpmail/tree/master/message

Maybe having a `message` package in another repo would be useful?

**Comment by emersion** [comment]
Hum, after thinking of it:
1. Decoding/encoding message bodies is _not_ this library's job
2. But decoding/encoding things like the envelope could be done in this library, I'm not sure about it...

**Comment by manishrjain** [comment]
If you think this job is out of scope of this library, then it's probably best to keep it that way. It would decrease the surface area of this library and you trade features for robustness.

**Comment by emersion** [comment]
I'll consider decoding header fields again as soon as decoding SEARCH fields is also needed (#97).

I'll probably add an `imap.CharsetReader` variable to allow users to support more charsets.
