### ISSUE TITLE
How can I get the  body and attachment of  message?

### ISSUE THREAD

**Issue by changyu72** [emersion/go-imap#91]
How can I get the  body and attachment of  message?,please help.

**Comment by emersion** [comment]
Hi!

I added an example to fetch a whole message: https://godoc.org/github.com/emersion/go-imap/client#example-Client-Fetch

If the message has attachments, you'll need to use the mime/multipart package to read attachments: https://golang.org/pkg/mime/multipart/#example_NewReader

It's not easy to parse and decode a multipart message, so I plan to create a library for that - though there are already some lying around (but they are not streaming 😢).

**Comment by emersion** [comment]
Note: I've finally created a library to parse and format easily mail messages: https://github.com/emersion/go-message
